(* Generated by gen_bindings - low-level OCaml interface *)

module Adapter_Type : sig
  type t =
  | Discrete_gpu
  | Integrated_gpu
  | Cpu
  | Unknown

  val to_int : t -> int
end

module Address_Mode : sig
  type t =
  | Undefined
  | Clamp_to_edge
  | Repeat
  | Mirror_repeat

  val to_int : t -> int
end

module Backend_Type : sig
  type t =
  | Undefined
  | Null
  | Webgpu
  | D3d11
  | D3d12
  | Metal
  | Vulkan
  | Opengl
  | Opengles

  val to_int : t -> int
end

module Blend_Factor : sig
  type t =
  | Undefined
  | Zero
  | One
  | Src
  | One_minus_src
  | Src_alpha
  | One_minus_src_alpha
  | Dst
  | One_minus_dst
  | Dst_alpha
  | One_minus_dst_alpha
  | Src_alpha_saturated
  | Constant
  | One_minus_constant
  | Src1
  | One_minus_src1
  | Src1_alpha
  | One_minus_src1_alpha

  val to_int : t -> int
end

module Blend_Operation : sig
  type t =
  | Undefined
  | Add
  | Subtract
  | Reverse_subtract
  | Min
  | Max

  val to_int : t -> int
end

module Buffer_Binding_Type : sig
  type t =
  | Binding_not_used
  | Undefined
  | Uniform
  | Storage
  | Read_only_storage

  val to_int : t -> int
end

module Buffer_Map_State : sig
  type t =
  | Unmapped
  | Pending
  | Mapped

  val to_int : t -> int
end

module Callback_Mode : sig
  type t =
  | Wait_any_only
  | Allow_process_events
  | Allow_spontaneous

  val to_int : t -> int
end

module Compare_Function : sig
  type t =
  | Undefined
  | Never
  | Less
  | Equal
  | Less_equal
  | Greater
  | Not_equal
  | Greater_equal
  | Always

  val to_int : t -> int
end

module Compilation_Info_Request_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

  val to_int : t -> int
end

module Compilation_Message_Type : sig
  type t =
  | Error
  | Warning
  | Info

  val to_int : t -> int
end

module Composite_Alpha_Mode : sig
  type t =
  | Auto
  | Opaque
  | Premultiplied
  | Unpremultiplied
  | Inherit

  val to_int : t -> int
end

module Create_Pipeline_Async_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Validation_error
  | Internal_error
  | Unknown

  val to_int : t -> int
end

module Cull_Mode : sig
  type t =
  | Undefined
  | None
  | Front
  | Back

  val to_int : t -> int
end

module Device_Lost_Reason : sig
  type t =
  | Unknown
  | Destroyed
  | Instance_dropped
  | Failed_creation

  val to_int : t -> int
end

module Error_Filter : sig
  type t =
  | Validation
  | Out_of_memory
  | Internal

  val to_int : t -> int
end

module Error_Type : sig
  type t =
  | No_error
  | Validation
  | Out_of_memory
  | Internal
  | Unknown

  val to_int : t -> int
end

module Feature_Level : sig
  type t =
  | Compatibility
  | Core

  val to_int : t -> int
end

module Feature_Name : sig
  type t =
  | Undefined
  | Depth_clip_control
  | Depth32_float_stencil8
  | Timestamp_query
  | Texture_compression_bc
  | Texture_compression_bc_sliced_3d
  | Texture_compression_etc2
  | Texture_compression_astc
  | Texture_compression_astc_sliced_3d
  | Indirect_first_instance
  | Shader_f16
  | Rg11b10_ufloat_renderable
  | Bgra8_unorm_storage
  | Float32_filterable
  | Float32_blendable
  | Clip_distances
  | Dual_source_blending

  val to_int : t -> int
end

module Filter_Mode : sig
  type t =
  | Undefined
  | Nearest
  | Linear

  val to_int : t -> int
end

module Front_Face : sig
  type t =
  | Undefined
  | Ccw
  | Cw

  val to_int : t -> int
end

module Index_Format : sig
  type t =
  | Undefined
  | Uint16
  | Uint32

  val to_int : t -> int
end

module Load_Op : sig
  type t =
  | Undefined
  | Load
  | Clear

  val to_int : t -> int
end

module Map_Async_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Aborted
  | Unknown

  val to_int : t -> int
end

module Mipmap_Filter_Mode : sig
  type t =
  | Undefined
  | Nearest
  | Linear

  val to_int : t -> int
end

module Optional_Bool : sig
  type t =
  | False
  | True
  | Undefined

  val to_int : t -> int
end

module Pop_Error_Scope_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Empty_stack

  val to_int : t -> int
end

module Power_Preference : sig
  type t =
  | Undefined
  | Low_power
  | High_performance

  val to_int : t -> int
end

module Present_Mode : sig
  type t =
  | Undefined
  | Fifo
  | Fifo_relaxed
  | Immediate
  | Mailbox

  val to_int : t -> int
end

module Primitive_Topology : sig
  type t =
  | Undefined
  | Point_list
  | Line_list
  | Line_strip
  | Triangle_list
  | Triangle_strip

  val to_int : t -> int
end

module Query_Type : sig
  type t =
  | Occlusion
  | Timestamp

  val to_int : t -> int
end

module Queue_Work_Done_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

  val to_int : t -> int
end

module Request_Adapter_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Unavailable
  | Error
  | Unknown

  val to_int : t -> int
end

module Request_Device_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

  val to_int : t -> int
end

module S_Type : sig
  type t =
  | Shader_source_spirv
  | Shader_source_wgsl
  | Render_pass_max_draw_count
  | Surface_source_metal_layer
  | Surface_source_windows_hwnd
  | Surface_source_xlib_window
  | Surface_source_wayland_surface
  | Surface_source_android_native_window
  | Surface_source_xcb_window

  val to_int : t -> int
end

module Sampler_Binding_Type : sig
  type t =
  | Binding_not_used
  | Undefined
  | Filtering
  | Non_filtering
  | Comparison

  val to_int : t -> int
end

module Status : sig
  type t =
  | Success
  | Error

  val to_int : t -> int
end

module Stencil_Operation : sig
  type t =
  | Undefined
  | Keep
  | Zero
  | Replace
  | Invert
  | Increment_clamp
  | Decrement_clamp
  | Increment_wrap
  | Decrement_wrap

  val to_int : t -> int
end

module Storage_Texture_Access : sig
  type t =
  | Binding_not_used
  | Undefined
  | Write_only
  | Read_only
  | Read_write

  val to_int : t -> int
end

module Store_Op : sig
  type t =
  | Undefined
  | Store
  | Discard

  val to_int : t -> int
end

module Surface_Get_Current_Texture_Status : sig
  type t =
  | Success_optimal
  | Success_suboptimal
  | Timeout
  | Outdated
  | Lost
  | Out_of_memory
  | Device_lost
  | Error

  val to_int : t -> int
end

module Texture_Aspect : sig
  type t =
  | Undefined
  | All
  | Stencil_only
  | Depth_only

  val to_int : t -> int
end

module Texture_Dimension : sig
  type t =
  | Undefined
  | N1d
  | N2d
  | N3d

  val to_int : t -> int
end

module Texture_Format : sig
  type t =
  | Undefined
  | R8_unorm
  | R8_snorm
  | R8_uint
  | R8_sint
  | R16_uint
  | R16_sint
  | R16_float
  | Rg8_unorm
  | Rg8_snorm
  | Rg8_uint
  | Rg8_sint
  | R32_float
  | R32_uint
  | R32_sint
  | Rg16_uint
  | Rg16_sint
  | Rg16_float
  | Rgba8_unorm
  | Rgba8_unorm_srgb
  | Rgba8_snorm
  | Rgba8_uint
  | Rgba8_sint
  | Bgra8_unorm
  | Bgra8_unorm_srgb
  | Rgb10_a2_uint
  | Rgb10_a2_unorm
  | Rg11_b10_ufloat
  | Rgb9_e5_ufloat
  | Rg32_float
  | Rg32_uint
  | Rg32_sint
  | Rgba16_uint
  | Rgba16_sint
  | Rgba16_float
  | Rgba32_float
  | Rgba32_uint
  | Rgba32_sint
  | Stencil8
  | Depth16_unorm
  | Depth24_plus
  | Depth24_plus_stencil8
  | Depth32_float
  | Depth32_float_stencil8
  | Bc1_rgba_unorm
  | Bc1_rgba_unorm_srgb
  | Bc2_rgba_unorm
  | Bc2_rgba_unorm_srgb
  | Bc3_rgba_unorm
  | Bc3_rgba_unorm_srgb
  | Bc4_r_unorm
  | Bc4_r_snorm
  | Bc5_rg_unorm
  | Bc5_rg_snorm
  | Bc6h_rgb_ufloat
  | Bc6h_rgb_float
  | Bc7_rgba_unorm
  | Bc7_rgba_unorm_srgb
  | Etc2_rgb8_unorm
  | Etc2_rgb8_unorm_srgb
  | Etc2_rgb8a1_unorm
  | Etc2_rgb8a1_unorm_srgb
  | Etc2_rgba8_unorm
  | Etc2_rgba8_unorm_srgb
  | Eac_r11_unorm
  | Eac_r11_snorm
  | Eac_rg11_unorm
  | Eac_rg11_snorm
  | Astc_4x4_unorm
  | Astc_4x4_unorm_srgb
  | Astc_5x4_unorm
  | Astc_5x4_unorm_srgb
  | Astc_5x5_unorm
  | Astc_5x5_unorm_srgb
  | Astc_6x5_unorm
  | Astc_6x5_unorm_srgb
  | Astc_6x6_unorm
  | Astc_6x6_unorm_srgb
  | Astc_8x5_unorm
  | Astc_8x5_unorm_srgb
  | Astc_8x6_unorm
  | Astc_8x6_unorm_srgb
  | Astc_8x8_unorm
  | Astc_8x8_unorm_srgb
  | Astc_10x5_unorm
  | Astc_10x5_unorm_srgb
  | Astc_10x6_unorm
  | Astc_10x6_unorm_srgb
  | Astc_10x8_unorm
  | Astc_10x8_unorm_srgb
  | Astc_10x10_unorm
  | Astc_10x10_unorm_srgb
  | Astc_12x10_unorm
  | Astc_12x10_unorm_srgb
  | Astc_12x12_unorm
  | Astc_12x12_unorm_srgb

  val to_int : t -> int
end

module Texture_Sample_Type : sig
  type t =
  | Binding_not_used
  | Undefined
  | Float
  | Unfilterable_float
  | Depth
  | Sint
  | Uint

  val to_int : t -> int
end

module Texture_View_Dimension : sig
  type t =
  | Undefined
  | N1d
  | N2d
  | N2d_array
  | Cube
  | Cube_array
  | N3d

  val to_int : t -> int
end

module Vertex_Format : sig
  type t =
  | Uint8
  | Uint8x2
  | Uint8x4
  | Sint8
  | Sint8x2
  | Sint8x4
  | Unorm8
  | Unorm8x2
  | Unorm8x4
  | Snorm8
  | Snorm8x2
  | Snorm8x4
  | Uint16
  | Uint16x2
  | Uint16x4
  | Sint16
  | Sint16x2
  | Sint16x4
  | Unorm16
  | Unorm16x2
  | Unorm16x4
  | Snorm16
  | Snorm16x2
  | Snorm16x4
  | Float16
  | Float16x2
  | Float16x4
  | Float32
  | Float32x2
  | Float32x3
  | Float32x4
  | Uint32
  | Uint32x2
  | Uint32x3
  | Uint32x4
  | Sint32
  | Sint32x2
  | Sint32x3
  | Sint32x4
  | Unorm10__10__10__2
  | Unorm8x4_b_g_r_a

  val to_int : t -> int
end

module Vertex_Step_Mode : sig
  type t =
  | Vertex_buffer_not_used
  | Undefined
  | Vertex
  | Instance

  val to_int : t -> int
end

module Wait_Status : sig
  type t =
  | Success
  | Timed_out
  | Unsupported_timeout
  | Unsupported_count
  | Unsupported_mixed_sources

  val to_int : t -> int
end

module WGSL_Language_Feature_Name : sig
  type t =
  | Readonly_and_readwrite_storage_textures
  | Packed4x8_integer_dot_product
  | Unrestricted_pointer_parameters
  | Pointer_composite_access

  val to_int : t -> int
end
module Buffer_Usage : sig
  type t =
  | None
  | Map_read
  | Map_write
  | Copy_src
  | Copy_dst
  | Index
  | Vertex
  | Uniform
  | Storage
  | Indirect
  | Query_resolve

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Color_Write_Mask : sig
  type t =
  | None
  | Red
  | Green
  | Blue
  | Alpha
  | All

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Map_Mode : sig
  type t =
  | None
  | Read
  | Write

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Shader_Stage : sig
  type t =
  | None
  | Vertex
  | Fragment
  | Compute

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Texture_Usage : sig
  type t =
  | None
  | Copy_src
  | Copy_dst
  | Texture_binding
  | Storage_binding
  | Render_attachment

  val to_int : t -> int
  val list_to_int : t list -> int
end
module Adapter_Info : sig
  type t = nativeint
  val adapter_info_create : unit -> t
  val adapter_info_free : t -> unit
  val adapter_info_set_vendor : t -> string -> unit
  val adapter_info_set_architecture : t -> string -> unit
  val adapter_info_set_device : t -> string -> unit
  val adapter_info_set_description : t -> string -> unit
  val adapter_info_set_backend_type : t -> int -> unit
  val adapter_info_set_adapter_type : t -> int -> unit
  val adapter_info_set_vendor_ID : t -> int -> unit
  val adapter_info_set_device_ID : t -> int -> unit
  val adapter_info_get_vendor : t -> string
  val adapter_info_get_architecture : t -> string
  val adapter_info_get_device : t -> string
  val adapter_info_get_description : t -> string
  val adapter_info_get_backend_type : t -> int
  val adapter_info_get_adapter_type : t -> int
  val adapter_info_get_vendor_ID : t -> int
  val adapter_info_get_device_ID : t -> int
end

module Bind_Group_Descriptor : sig
  type t = nativeint
  val bind_group_descriptor_create : unit -> t
  val bind_group_descriptor_free : t -> unit
  val bind_group_descriptor_set_label : t -> string -> unit
  val bind_group_descriptor_set_layout : t -> nativeint -> unit
  val bind_group_descriptor_set_entries : t -> nativeint array -> unit
  val bind_group_descriptor_get_label : t -> string
  val bind_group_descriptor_get_layout : t -> nativeint
  val bind_group_descriptor_get_entries : t -> nativeint
end

module Bind_Group_Entry : sig
  type t = nativeint
  val bind_group_entry_create : unit -> t
  val bind_group_entry_free : t -> unit
  val bind_group_entry_set_binding : t -> int -> unit
  val bind_group_entry_set_buffer : t -> nativeint -> unit
  val bind_group_entry_set_offset : t -> int64 -> unit
  val bind_group_entry_set_size : t -> int64 -> unit
  val bind_group_entry_set_sampler : t -> nativeint -> unit
  val bind_group_entry_set_texture_view : t -> nativeint -> unit
  val bind_group_entry_get_binding : t -> int
  val bind_group_entry_get_buffer : t -> nativeint
  val bind_group_entry_get_offset : t -> int64
  val bind_group_entry_get_size : t -> int64
  val bind_group_entry_get_sampler : t -> nativeint
  val bind_group_entry_get_texture_view : t -> nativeint
end

module Bind_Group_Layout_Descriptor : sig
  type t = nativeint
  val bind_group_layout_descriptor_create : unit -> t
  val bind_group_layout_descriptor_free : t -> unit
  val bind_group_layout_descriptor_set_label : t -> string -> unit
  val bind_group_layout_descriptor_set_entries : t -> nativeint array -> unit
  val bind_group_layout_descriptor_get_label : t -> string
  val bind_group_layout_descriptor_get_entries : t -> nativeint
end

module Bind_Group_Layout_Entry : sig
  type t = nativeint
  val bind_group_layout_entry_create : unit -> t
  val bind_group_layout_entry_free : t -> unit
  val bind_group_layout_entry_set_binding : t -> int -> unit
  val bind_group_layout_entry_set_visibility : t -> int -> unit
  val bind_group_layout_entry_set_buffer : t -> nativeint -> unit
  val bind_group_layout_entry_set_sampler : t -> nativeint -> unit
  val bind_group_layout_entry_set_texture : t -> nativeint -> unit
  val bind_group_layout_entry_set_storage_texture : t -> nativeint -> unit
  val bind_group_layout_entry_get_binding : t -> int
  val bind_group_layout_entry_get_visibility : t -> int
  val bind_group_layout_entry_get_buffer : t -> nativeint
  val bind_group_layout_entry_get_sampler : t -> nativeint
  val bind_group_layout_entry_get_texture : t -> nativeint
  val bind_group_layout_entry_get_storage_texture : t -> nativeint
end

module Blend_Component : sig
  type t = nativeint
  val blend_component_create : unit -> t
  val blend_component_free : t -> unit
  val blend_component_set_operation : t -> int -> unit
  val blend_component_set_src_factor : t -> int -> unit
  val blend_component_set_dst_factor : t -> int -> unit
  val blend_component_get_operation : t -> int
  val blend_component_get_src_factor : t -> int
  val blend_component_get_dst_factor : t -> int
end

module Blend_State : sig
  type t = nativeint
  val blend_state_create : unit -> t
  val blend_state_free : t -> unit
  val blend_state_set_color : t -> nativeint -> unit
  val blend_state_set_alpha : t -> nativeint -> unit
  val blend_state_get_color : t -> nativeint
  val blend_state_get_alpha : t -> nativeint
end

module Buffer_Binding_Layout : sig
  type t = nativeint
  val buffer_binding_layout_create : unit -> t
  val buffer_binding_layout_free : t -> unit
  val buffer_binding_layout_set_type : t -> int -> unit
  val buffer_binding_layout_set_has_dynamic_offset : t -> bool -> unit
  val buffer_binding_layout_set_min_binding_size : t -> int64 -> unit
  val buffer_binding_layout_get_type : t -> int
  val buffer_binding_layout_get_has_dynamic_offset : t -> bool
  val buffer_binding_layout_get_min_binding_size : t -> int64
end

module Buffer_Descriptor : sig
  type t = nativeint
  val buffer_descriptor_create : unit -> t
  val buffer_descriptor_free : t -> unit
  val buffer_descriptor_set_label : t -> string -> unit
  val buffer_descriptor_set_usage : t -> int -> unit
  val buffer_descriptor_set_size : t -> int64 -> unit
  val buffer_descriptor_set_mapped_at_creation : t -> bool -> unit
  val buffer_descriptor_get_label : t -> string
  val buffer_descriptor_get_usage : t -> int
  val buffer_descriptor_get_size : t -> int64
  val buffer_descriptor_get_mapped_at_creation : t -> bool
end

module Color : sig
  type t = nativeint
  val color_create : unit -> t
  val color_free : t -> unit
  val color_set_r : t -> float -> unit
  val color_set_g : t -> float -> unit
  val color_set_b : t -> float -> unit
  val color_set_a : t -> float -> unit
  val color_get_r : t -> float
  val color_get_g : t -> float
  val color_get_b : t -> float
  val color_get_a : t -> float
end

module Color_Target_State : sig
  type t = nativeint
  val color_target_state_create : unit -> t
  val color_target_state_free : t -> unit
  val color_target_state_set_format : t -> int -> unit
  val color_target_state_set_blend : t -> nativeint -> unit
  val color_target_state_set_write_mask : t -> int -> unit
  val color_target_state_get_format : t -> int
  val color_target_state_get_blend : t -> nativeint
  val color_target_state_get_write_mask : t -> int
end

module Command_Buffer_Descriptor : sig
  type t = nativeint
  val command_buffer_descriptor_create : unit -> t
  val command_buffer_descriptor_free : t -> unit
  val command_buffer_descriptor_set_label : t -> string -> unit
  val command_buffer_descriptor_get_label : t -> string
end

module Command_Encoder_Descriptor : sig
  type t = nativeint
  val command_encoder_descriptor_create : unit -> t
  val command_encoder_descriptor_free : t -> unit
  val command_encoder_descriptor_set_label : t -> string -> unit
  val command_encoder_descriptor_get_label : t -> string
end

module Compilation_Info : sig
  type t = nativeint
  val compilation_info_create : unit -> t
  val compilation_info_free : t -> unit
  val compilation_info_set_messages : t -> nativeint array -> unit
  val compilation_info_get_messages : t -> nativeint
end

module Compilation_Message : sig
  type t = nativeint
  val compilation_message_create : unit -> t
  val compilation_message_free : t -> unit
  val compilation_message_set_message : t -> string -> unit
  val compilation_message_set_type : t -> int -> unit
  val compilation_message_set_line_num : t -> int64 -> unit
  val compilation_message_set_line_pos : t -> int64 -> unit
  val compilation_message_set_offset : t -> int64 -> unit
  val compilation_message_set_length : t -> int64 -> unit
  val compilation_message_get_message : t -> string
  val compilation_message_get_type : t -> int
  val compilation_message_get_line_num : t -> int64
  val compilation_message_get_line_pos : t -> int64
  val compilation_message_get_offset : t -> int64
  val compilation_message_get_length : t -> int64
end

module Compute_Pass_Descriptor : sig
  type t = nativeint
  val compute_pass_descriptor_create : unit -> t
  val compute_pass_descriptor_free : t -> unit
  val compute_pass_descriptor_set_label : t -> string -> unit
  val compute_pass_descriptor_set_timestamp_writes : t -> nativeint -> unit
  val compute_pass_descriptor_get_label : t -> string
  val compute_pass_descriptor_get_timestamp_writes : t -> nativeint
end

module Compute_Pass_Timestamp_Writes : sig
  type t = nativeint
  val compute_pass_timestamp_writes_create : unit -> t
  val compute_pass_timestamp_writes_free : t -> unit
  val compute_pass_timestamp_writes_set_query_set : t -> nativeint -> unit
  val compute_pass_timestamp_writes_set_beginning_of_pass_write_index : t -> int -> unit
  val compute_pass_timestamp_writes_set_end_of_pass_write_index : t -> int -> unit
  val compute_pass_timestamp_writes_get_query_set : t -> nativeint
  val compute_pass_timestamp_writes_get_beginning_of_pass_write_index : t -> int
  val compute_pass_timestamp_writes_get_end_of_pass_write_index : t -> int
end

module Compute_Pipeline_Descriptor : sig
  type t = nativeint
  val compute_pipeline_descriptor_create : unit -> t
  val compute_pipeline_descriptor_free : t -> unit
  val compute_pipeline_descriptor_set_label : t -> string -> unit
  val compute_pipeline_descriptor_set_layout : t -> nativeint -> unit
  val compute_pipeline_descriptor_set_compute : t -> nativeint -> unit
  val compute_pipeline_descriptor_get_label : t -> string
  val compute_pipeline_descriptor_get_layout : t -> nativeint
  val compute_pipeline_descriptor_get_compute : t -> nativeint
end

module Constant_Entry : sig
  type t = nativeint
  val constant_entry_create : unit -> t
  val constant_entry_free : t -> unit
  val constant_entry_set_key : t -> string -> unit
  val constant_entry_set_value : t -> float -> unit
  val constant_entry_get_key : t -> string
  val constant_entry_get_value : t -> float
end

module Depth_Stencil_State : sig
  type t = nativeint
  val depth_stencil_state_create : unit -> t
  val depth_stencil_state_free : t -> unit
  val depth_stencil_state_set_format : t -> int -> unit
  val depth_stencil_state_set_depth_write_enabled : t -> int -> unit
  val depth_stencil_state_set_depth_compare : t -> int -> unit
  val depth_stencil_state_set_stencil_front : t -> nativeint -> unit
  val depth_stencil_state_set_stencil_back : t -> nativeint -> unit
  val depth_stencil_state_set_stencil_read_mask : t -> int -> unit
  val depth_stencil_state_set_stencil_write_mask : t -> int -> unit
  val depth_stencil_state_set_depth_bias : t -> int -> unit
  val depth_stencil_state_set_depth_bias_slope_scale : t -> float -> unit
  val depth_stencil_state_set_depth_bias_clamp : t -> float -> unit
  val depth_stencil_state_get_format : t -> int
  val depth_stencil_state_get_depth_write_enabled : t -> int
  val depth_stencil_state_get_depth_compare : t -> int
  val depth_stencil_state_get_stencil_front : t -> nativeint
  val depth_stencil_state_get_stencil_back : t -> nativeint
  val depth_stencil_state_get_stencil_read_mask : t -> int
  val depth_stencil_state_get_stencil_write_mask : t -> int
  val depth_stencil_state_get_depth_bias : t -> int
  val depth_stencil_state_get_depth_bias_slope_scale : t -> float
  val depth_stencil_state_get_depth_bias_clamp : t -> float
end

module Device_Descriptor : sig
  type t = nativeint
  val device_descriptor_create : unit -> t
  val device_descriptor_free : t -> unit
  val device_descriptor_set_label : t -> string -> unit
  val device_descriptor_set_required_features : t -> int array -> unit
  val device_descriptor_set_required_limits : t -> nativeint -> unit
  val device_descriptor_set_default_queue : t -> nativeint -> unit
  val device_descriptor_set_device_lost_callback_info : t -> nativeint -> unit
  val device_descriptor_set_uncaptured_error_callback_info : t -> nativeint -> unit
  val device_descriptor_get_label : t -> string
  val device_descriptor_get_required_features : t -> nativeint
  val device_descriptor_get_required_limits : t -> nativeint
  val device_descriptor_get_default_queue : t -> nativeint
  val device_descriptor_get_device_lost_callback_info : t -> nativeint
  val device_descriptor_get_uncaptured_error_callback_info : t -> nativeint
end

module Extent_3D : sig
  type t = nativeint
  val extent_3D_create : unit -> t
  val extent_3D_free : t -> unit
  val extent_3D_set_width : t -> int -> unit
  val extent_3D_set_height : t -> int -> unit
  val extent_3D_set_depth_or_array_layers : t -> int -> unit
  val extent_3D_get_width : t -> int
  val extent_3D_get_height : t -> int
  val extent_3D_get_depth_or_array_layers : t -> int
end

module Fragment_State : sig
  type t = nativeint
  val fragment_state_create : unit -> t
  val fragment_state_free : t -> unit
  val fragment_state_set_module : t -> nativeint -> unit
  val fragment_state_set_entry_point : t -> string -> unit
  val fragment_state_set_constants : t -> nativeint array -> unit
  val fragment_state_set_targets : t -> nativeint array -> unit
  val fragment_state_get_module : t -> nativeint
  val fragment_state_get_entry_point : t -> string
  val fragment_state_get_constants : t -> nativeint
  val fragment_state_get_targets : t -> nativeint
end

module Future : sig
  type t = nativeint
  val future_create : unit -> t
  val future_free : t -> unit
  val future_set_id : t -> int64 -> unit
  val future_get_id : t -> int64
end

module Future_Wait_Info : sig
  type t = nativeint
  val future_wait_info_create : unit -> t
  val future_wait_info_free : t -> unit
  val future_wait_info_set_future : t -> nativeint -> unit
  val future_wait_info_set_completed : t -> bool -> unit
  val future_wait_info_get_future : t -> nativeint
  val future_wait_info_get_completed : t -> bool
end

module Instance_Capabilities : sig
  type t = nativeint
  val instance_capabilities_create : unit -> t
  val instance_capabilities_free : t -> unit
  val instance_capabilities_set_timed_wait_any_enable : t -> bool -> unit
  val instance_capabilities_set_timed_wait_any_max_count : t -> int64 -> unit
  val instance_capabilities_get_timed_wait_any_enable : t -> bool
  val instance_capabilities_get_timed_wait_any_max_count : t -> int64
end

module Instance_Descriptor : sig
  type t = nativeint
  val instance_descriptor_create : unit -> t
  val instance_descriptor_free : t -> unit
  val instance_descriptor_set_features : t -> nativeint -> unit
  val instance_descriptor_get_features : t -> nativeint
end

module Limits : sig
  type t = nativeint
  val limits_create : unit -> t
  val limits_free : t -> unit
  val limits_set_max_texture_dimension_1D : t -> int -> unit
  val limits_set_max_texture_dimension_2D : t -> int -> unit
  val limits_set_max_texture_dimension_3D : t -> int -> unit
  val limits_set_max_texture_array_layers : t -> int -> unit
  val limits_set_max_bind_groups : t -> int -> unit
  val limits_set_max_bind_groups_plus_vertex_buffers : t -> int -> unit
  val limits_set_max_bindings_per_bind_group : t -> int -> unit
  val limits_set_max_dynamic_uniform_buffers_per_pipeline_layout : t -> int -> unit
  val limits_set_max_dynamic_storage_buffers_per_pipeline_layout : t -> int -> unit
  val limits_set_max_sampled_textures_per_shader_stage : t -> int -> unit
  val limits_set_max_samplers_per_shader_stage : t -> int -> unit
  val limits_set_max_storage_buffers_per_shader_stage : t -> int -> unit
  val limits_set_max_storage_textures_per_shader_stage : t -> int -> unit
  val limits_set_max_uniform_buffers_per_shader_stage : t -> int -> unit
  val limits_set_max_uniform_buffer_binding_size : t -> int64 -> unit
  val limits_set_max_storage_buffer_binding_size : t -> int64 -> unit
  val limits_set_min_uniform_buffer_offset_alignment : t -> int -> unit
  val limits_set_min_storage_buffer_offset_alignment : t -> int -> unit
  val limits_set_max_vertex_buffers : t -> int -> unit
  val limits_set_max_buffer_size : t -> int64 -> unit
  val limits_set_max_vertex_attributes : t -> int -> unit
  val limits_set_max_vertex_buffer_array_stride : t -> int -> unit
  val limits_set_max_inter_stage_shader_variables : t -> int -> unit
  val limits_set_max_color_attachments : t -> int -> unit
  val limits_set_max_color_attachment_bytes_per_sample : t -> int -> unit
  val limits_set_max_compute_workgroup_storage_size : t -> int -> unit
  val limits_set_max_compute_invocations_per_workgroup : t -> int -> unit
  val limits_set_max_compute_workgroup_size_x : t -> int -> unit
  val limits_set_max_compute_workgroup_size_y : t -> int -> unit
  val limits_set_max_compute_workgroup_size_z : t -> int -> unit
  val limits_set_max_compute_workgroups_per_dimension : t -> int -> unit
  val limits_get_max_texture_dimension_1D : t -> int
  val limits_get_max_texture_dimension_2D : t -> int
  val limits_get_max_texture_dimension_3D : t -> int
  val limits_get_max_texture_array_layers : t -> int
  val limits_get_max_bind_groups : t -> int
  val limits_get_max_bind_groups_plus_vertex_buffers : t -> int
  val limits_get_max_bindings_per_bind_group : t -> int
  val limits_get_max_dynamic_uniform_buffers_per_pipeline_layout : t -> int
  val limits_get_max_dynamic_storage_buffers_per_pipeline_layout : t -> int
  val limits_get_max_sampled_textures_per_shader_stage : t -> int
  val limits_get_max_samplers_per_shader_stage : t -> int
  val limits_get_max_storage_buffers_per_shader_stage : t -> int
  val limits_get_max_storage_textures_per_shader_stage : t -> int
  val limits_get_max_uniform_buffers_per_shader_stage : t -> int
  val limits_get_max_uniform_buffer_binding_size : t -> int64
  val limits_get_max_storage_buffer_binding_size : t -> int64
  val limits_get_min_uniform_buffer_offset_alignment : t -> int
  val limits_get_min_storage_buffer_offset_alignment : t -> int
  val limits_get_max_vertex_buffers : t -> int
  val limits_get_max_buffer_size : t -> int64
  val limits_get_max_vertex_attributes : t -> int
  val limits_get_max_vertex_buffer_array_stride : t -> int
  val limits_get_max_inter_stage_shader_variables : t -> int
  val limits_get_max_color_attachments : t -> int
  val limits_get_max_color_attachment_bytes_per_sample : t -> int
  val limits_get_max_compute_workgroup_storage_size : t -> int
  val limits_get_max_compute_invocations_per_workgroup : t -> int
  val limits_get_max_compute_workgroup_size_x : t -> int
  val limits_get_max_compute_workgroup_size_y : t -> int
  val limits_get_max_compute_workgroup_size_z : t -> int
  val limits_get_max_compute_workgroups_per_dimension : t -> int
end

module Multisample_State : sig
  type t = nativeint
  val multisample_state_create : unit -> t
  val multisample_state_free : t -> unit
  val multisample_state_set_count : t -> int -> unit
  val multisample_state_set_mask : t -> int -> unit
  val multisample_state_set_alpha_to_coverage_enabled : t -> bool -> unit
  val multisample_state_get_count : t -> int
  val multisample_state_get_mask : t -> int
  val multisample_state_get_alpha_to_coverage_enabled : t -> bool
end

module Origin_3D : sig
  type t = nativeint
  val origin_3D_create : unit -> t
  val origin_3D_free : t -> unit
  val origin_3D_set_x : t -> int -> unit
  val origin_3D_set_y : t -> int -> unit
  val origin_3D_set_z : t -> int -> unit
  val origin_3D_get_x : t -> int
  val origin_3D_get_y : t -> int
  val origin_3D_get_z : t -> int
end

module Pipeline_Layout_Descriptor : sig
  type t = nativeint
  val pipeline_layout_descriptor_create : unit -> t
  val pipeline_layout_descriptor_free : t -> unit
  val pipeline_layout_descriptor_set_label : t -> string -> unit
  val pipeline_layout_descriptor_set_bind_group_layouts : t -> nativeint array -> unit
  val pipeline_layout_descriptor_get_label : t -> string
  val pipeline_layout_descriptor_get_bind_group_layouts : t -> nativeint
end

module Primitive_State : sig
  type t = nativeint
  val primitive_state_create : unit -> t
  val primitive_state_free : t -> unit
  val primitive_state_set_topology : t -> int -> unit
  val primitive_state_set_strip_index_format : t -> int -> unit
  val primitive_state_set_front_face : t -> int -> unit
  val primitive_state_set_cull_mode : t -> int -> unit
  val primitive_state_set_unclipped_depth : t -> bool -> unit
  val primitive_state_get_topology : t -> int
  val primitive_state_get_strip_index_format : t -> int
  val primitive_state_get_front_face : t -> int
  val primitive_state_get_cull_mode : t -> int
  val primitive_state_get_unclipped_depth : t -> bool
end

module Programmable_Stage_Descriptor : sig
  type t = nativeint
  val programmable_stage_descriptor_create : unit -> t
  val programmable_stage_descriptor_free : t -> unit
  val programmable_stage_descriptor_set_module : t -> nativeint -> unit
  val programmable_stage_descriptor_set_entry_point : t -> string -> unit
  val programmable_stage_descriptor_set_constants : t -> nativeint array -> unit
  val programmable_stage_descriptor_get_module : t -> nativeint
  val programmable_stage_descriptor_get_entry_point : t -> string
  val programmable_stage_descriptor_get_constants : t -> nativeint
end

module Query_Set_Descriptor : sig
  type t = nativeint
  val query_set_descriptor_create : unit -> t
  val query_set_descriptor_free : t -> unit
  val query_set_descriptor_set_label : t -> string -> unit
  val query_set_descriptor_set_type : t -> int -> unit
  val query_set_descriptor_set_count : t -> int -> unit
  val query_set_descriptor_get_label : t -> string
  val query_set_descriptor_get_type : t -> int
  val query_set_descriptor_get_count : t -> int
end

module Queue_Descriptor : sig
  type t = nativeint
  val queue_descriptor_create : unit -> t
  val queue_descriptor_free : t -> unit
  val queue_descriptor_set_label : t -> string -> unit
  val queue_descriptor_get_label : t -> string
end

module Render_Bundle_Descriptor : sig
  type t = nativeint
  val render_bundle_descriptor_create : unit -> t
  val render_bundle_descriptor_free : t -> unit
  val render_bundle_descriptor_set_label : t -> string -> unit
  val render_bundle_descriptor_get_label : t -> string
end

module Render_Bundle_Encoder_Descriptor : sig
  type t = nativeint
  val render_bundle_encoder_descriptor_create : unit -> t
  val render_bundle_encoder_descriptor_free : t -> unit
  val render_bundle_encoder_descriptor_set_label : t -> string -> unit
  val render_bundle_encoder_descriptor_set_color_formats : t -> int array -> unit
  val render_bundle_encoder_descriptor_set_depth_stencil_format : t -> int -> unit
  val render_bundle_encoder_descriptor_set_sample_count : t -> int -> unit
  val render_bundle_encoder_descriptor_set_depth_read_only : t -> bool -> unit
  val render_bundle_encoder_descriptor_set_stencil_read_only : t -> bool -> unit
  val render_bundle_encoder_descriptor_get_label : t -> string
  val render_bundle_encoder_descriptor_get_color_formats : t -> nativeint
  val render_bundle_encoder_descriptor_get_depth_stencil_format : t -> int
  val render_bundle_encoder_descriptor_get_sample_count : t -> int
  val render_bundle_encoder_descriptor_get_depth_read_only : t -> bool
  val render_bundle_encoder_descriptor_get_stencil_read_only : t -> bool
end

module Render_Pass_Color_Attachment : sig
  type t = nativeint
  val render_pass_color_attachment_create : unit -> t
  val render_pass_color_attachment_free : t -> unit
  val render_pass_color_attachment_set_view : t -> nativeint -> unit
  val render_pass_color_attachment_set_depth_slice : t -> int -> unit
  val render_pass_color_attachment_set_resolve_target : t -> nativeint -> unit
  val render_pass_color_attachment_set_load_op : t -> int -> unit
  val render_pass_color_attachment_set_store_op : t -> int -> unit
  val render_pass_color_attachment_set_clear_value : t -> nativeint -> unit
  val render_pass_color_attachment_get_view : t -> nativeint
  val render_pass_color_attachment_get_depth_slice : t -> int
  val render_pass_color_attachment_get_resolve_target : t -> nativeint
  val render_pass_color_attachment_get_load_op : t -> int
  val render_pass_color_attachment_get_store_op : t -> int
  val render_pass_color_attachment_get_clear_value : t -> nativeint
end

module Render_Pass_Depth_Stencil_Attachment : sig
  type t = nativeint
  val render_pass_depth_stencil_attachment_create : unit -> t
  val render_pass_depth_stencil_attachment_free : t -> unit
  val render_pass_depth_stencil_attachment_set_view : t -> nativeint -> unit
  val render_pass_depth_stencil_attachment_set_depth_load_op : t -> int -> unit
  val render_pass_depth_stencil_attachment_set_depth_store_op : t -> int -> unit
  val render_pass_depth_stencil_attachment_set_depth_clear_value : t -> float -> unit
  val render_pass_depth_stencil_attachment_set_depth_read_only : t -> bool -> unit
  val render_pass_depth_stencil_attachment_set_stencil_load_op : t -> int -> unit
  val render_pass_depth_stencil_attachment_set_stencil_store_op : t -> int -> unit
  val render_pass_depth_stencil_attachment_set_stencil_clear_value : t -> int -> unit
  val render_pass_depth_stencil_attachment_set_stencil_read_only : t -> bool -> unit
  val render_pass_depth_stencil_attachment_get_view : t -> nativeint
  val render_pass_depth_stencil_attachment_get_depth_load_op : t -> int
  val render_pass_depth_stencil_attachment_get_depth_store_op : t -> int
  val render_pass_depth_stencil_attachment_get_depth_clear_value : t -> float
  val render_pass_depth_stencil_attachment_get_depth_read_only : t -> bool
  val render_pass_depth_stencil_attachment_get_stencil_load_op : t -> int
  val render_pass_depth_stencil_attachment_get_stencil_store_op : t -> int
  val render_pass_depth_stencil_attachment_get_stencil_clear_value : t -> int
  val render_pass_depth_stencil_attachment_get_stencil_read_only : t -> bool
end

module Render_Pass_Descriptor : sig
  type t = nativeint
  val render_pass_descriptor_create : unit -> t
  val render_pass_descriptor_free : t -> unit
  val render_pass_descriptor_set_label : t -> string -> unit
  val render_pass_descriptor_set_color_attachments : t -> nativeint array -> unit
  val render_pass_descriptor_set_depth_stencil_attachment : t -> nativeint -> unit
  val render_pass_descriptor_set_occlusion_query_set : t -> nativeint -> unit
  val render_pass_descriptor_set_timestamp_writes : t -> nativeint -> unit
  val render_pass_descriptor_get_label : t -> string
  val render_pass_descriptor_get_color_attachments : t -> nativeint
  val render_pass_descriptor_get_depth_stencil_attachment : t -> nativeint
  val render_pass_descriptor_get_occlusion_query_set : t -> nativeint
  val render_pass_descriptor_get_timestamp_writes : t -> nativeint
end

module Render_Pass_Max_Draw_Count : sig
  type t = nativeint
  val render_pass_max_draw_count_create : unit -> t
  val render_pass_max_draw_count_free : t -> unit
  val render_pass_max_draw_count_set_max_draw_count : t -> int64 -> unit
  val render_pass_max_draw_count_get_max_draw_count : t -> int64
end

module Render_Pass_Timestamp_Writes : sig
  type t = nativeint
  val render_pass_timestamp_writes_create : unit -> t
  val render_pass_timestamp_writes_free : t -> unit
  val render_pass_timestamp_writes_set_query_set : t -> nativeint -> unit
  val render_pass_timestamp_writes_set_beginning_of_pass_write_index : t -> int -> unit
  val render_pass_timestamp_writes_set_end_of_pass_write_index : t -> int -> unit
  val render_pass_timestamp_writes_get_query_set : t -> nativeint
  val render_pass_timestamp_writes_get_beginning_of_pass_write_index : t -> int
  val render_pass_timestamp_writes_get_end_of_pass_write_index : t -> int
end

module Render_Pipeline_Descriptor : sig
  type t = nativeint
  val render_pipeline_descriptor_create : unit -> t
  val render_pipeline_descriptor_free : t -> unit
  val render_pipeline_descriptor_set_label : t -> string -> unit
  val render_pipeline_descriptor_set_layout : t -> nativeint -> unit
  val render_pipeline_descriptor_set_vertex : t -> nativeint -> unit
  val render_pipeline_descriptor_set_primitive : t -> nativeint -> unit
  val render_pipeline_descriptor_set_depth_stencil : t -> nativeint -> unit
  val render_pipeline_descriptor_set_multisample : t -> nativeint -> unit
  val render_pipeline_descriptor_set_fragment : t -> nativeint -> unit
  val render_pipeline_descriptor_get_label : t -> string
  val render_pipeline_descriptor_get_layout : t -> nativeint
  val render_pipeline_descriptor_get_vertex : t -> nativeint
  val render_pipeline_descriptor_get_primitive : t -> nativeint
  val render_pipeline_descriptor_get_depth_stencil : t -> nativeint
  val render_pipeline_descriptor_get_multisample : t -> nativeint
  val render_pipeline_descriptor_get_fragment : t -> nativeint
end

module Request_Adapter_Options : sig
  type t = nativeint
  val request_adapter_options_create : unit -> t
  val request_adapter_options_free : t -> unit
  val request_adapter_options_set_feature_level : t -> int -> unit
  val request_adapter_options_set_power_preference : t -> int -> unit
  val request_adapter_options_set_force_fallback_adapter : t -> bool -> unit
  val request_adapter_options_set_backend_type : t -> int -> unit
  val request_adapter_options_set_compatible_surface : t -> nativeint -> unit
  val request_adapter_options_get_feature_level : t -> int
  val request_adapter_options_get_power_preference : t -> int
  val request_adapter_options_get_force_fallback_adapter : t -> bool
  val request_adapter_options_get_backend_type : t -> int
  val request_adapter_options_get_compatible_surface : t -> nativeint
end

module Sampler_Binding_Layout : sig
  type t = nativeint
  val sampler_binding_layout_create : unit -> t
  val sampler_binding_layout_free : t -> unit
  val sampler_binding_layout_set_type : t -> int -> unit
  val sampler_binding_layout_get_type : t -> int
end

module Sampler_Descriptor : sig
  type t = nativeint
  val sampler_descriptor_create : unit -> t
  val sampler_descriptor_free : t -> unit
  val sampler_descriptor_set_label : t -> string -> unit
  val sampler_descriptor_set_address_mode_u : t -> int -> unit
  val sampler_descriptor_set_address_mode_v : t -> int -> unit
  val sampler_descriptor_set_address_mode_w : t -> int -> unit
  val sampler_descriptor_set_mag_filter : t -> int -> unit
  val sampler_descriptor_set_min_filter : t -> int -> unit
  val sampler_descriptor_set_mipmap_filter : t -> int -> unit
  val sampler_descriptor_set_lod_min_clamp : t -> float -> unit
  val sampler_descriptor_set_lod_max_clamp : t -> float -> unit
  val sampler_descriptor_set_compare : t -> int -> unit
  val sampler_descriptor_set_max_anisotropy : t -> int -> unit
  val sampler_descriptor_get_label : t -> string
  val sampler_descriptor_get_address_mode_u : t -> int
  val sampler_descriptor_get_address_mode_v : t -> int
  val sampler_descriptor_get_address_mode_w : t -> int
  val sampler_descriptor_get_mag_filter : t -> int
  val sampler_descriptor_get_min_filter : t -> int
  val sampler_descriptor_get_mipmap_filter : t -> int
  val sampler_descriptor_get_lod_min_clamp : t -> float
  val sampler_descriptor_get_lod_max_clamp : t -> float
  val sampler_descriptor_get_compare : t -> int
  val sampler_descriptor_get_max_anisotropy : t -> int
end

module Shader_Module_Descriptor : sig
  type t = nativeint
  val shader_module_descriptor_create : unit -> t
  val shader_module_descriptor_free : t -> unit
  val shader_module_descriptor_set_label : t -> string -> unit
  val shader_module_descriptor_get_label : t -> string
end

module Shader_Source_SPIRV : sig
  type t = nativeint
  val shader_source_SPIRV_create : unit -> t
  val shader_source_SPIRV_free : t -> unit
  val shader_source_SPIRV_set_code_size : t -> int -> unit
  val shader_source_SPIRV_set_code : t -> nativeint -> unit
  val shader_source_SPIRV_get_code_size : t -> int
  val shader_source_SPIRV_get_code : t -> nativeint
end

module Shader_Source_WGSL : sig
  type t = nativeint
  val shader_source_WGSL_create : unit -> t
  val shader_source_WGSL_free : t -> unit
  val shader_source_WGSL_set_code : t -> string -> unit
  val shader_source_WGSL_get_code : t -> string
end

module Stencil_Face_State : sig
  type t = nativeint
  val stencil_face_state_create : unit -> t
  val stencil_face_state_free : t -> unit
  val stencil_face_state_set_compare : t -> int -> unit
  val stencil_face_state_set_fail_op : t -> int -> unit
  val stencil_face_state_set_depth_fail_op : t -> int -> unit
  val stencil_face_state_set_pass_op : t -> int -> unit
  val stencil_face_state_get_compare : t -> int
  val stencil_face_state_get_fail_op : t -> int
  val stencil_face_state_get_depth_fail_op : t -> int
  val stencil_face_state_get_pass_op : t -> int
end

module Storage_Texture_Binding_Layout : sig
  type t = nativeint
  val storage_texture_binding_layout_create : unit -> t
  val storage_texture_binding_layout_free : t -> unit
  val storage_texture_binding_layout_set_access : t -> int -> unit
  val storage_texture_binding_layout_set_format : t -> int -> unit
  val storage_texture_binding_layout_set_view_dimension : t -> int -> unit
  val storage_texture_binding_layout_get_access : t -> int
  val storage_texture_binding_layout_get_format : t -> int
  val storage_texture_binding_layout_get_view_dimension : t -> int
end

module Supported_Features : sig
  type t = nativeint
  val supported_features_create : unit -> t
  val supported_features_free : t -> unit
  val supported_features_set_features : t -> int array -> unit
  val supported_features_get_features : t -> nativeint
end

module Supported_WGSL_Language_Features : sig
  type t = nativeint
  val supported_WGSL_language_features_create : unit -> t
  val supported_WGSL_language_features_free : t -> unit
  val supported_WGSL_language_features_set_features : t -> int array -> unit
  val supported_WGSL_language_features_get_features : t -> nativeint
end

module Surface_Capabilities : sig
  type t = nativeint
  val surface_capabilities_create : unit -> t
  val surface_capabilities_free : t -> unit
  val surface_capabilities_set_usages : t -> int -> unit
  val surface_capabilities_set_formats : t -> int array -> unit
  val surface_capabilities_set_present_modes : t -> int array -> unit
  val surface_capabilities_set_alpha_modes : t -> int array -> unit
  val surface_capabilities_get_usages : t -> int
  val surface_capabilities_get_formats : t -> nativeint
  val surface_capabilities_get_present_modes : t -> nativeint
  val surface_capabilities_get_alpha_modes : t -> nativeint
end

module Surface_Configuration : sig
  type t = nativeint
  val surface_configuration_create : unit -> t
  val surface_configuration_free : t -> unit
  val surface_configuration_set_device : t -> nativeint -> unit
  val surface_configuration_set_format : t -> int -> unit
  val surface_configuration_set_usage : t -> int -> unit
  val surface_configuration_set_width : t -> int -> unit
  val surface_configuration_set_height : t -> int -> unit
  val surface_configuration_set_view_formats : t -> int array -> unit
  val surface_configuration_set_alpha_mode : t -> int -> unit
  val surface_configuration_set_present_mode : t -> int -> unit
  val surface_configuration_get_device : t -> nativeint
  val surface_configuration_get_format : t -> int
  val surface_configuration_get_usage : t -> int
  val surface_configuration_get_width : t -> int
  val surface_configuration_get_height : t -> int
  val surface_configuration_get_view_formats : t -> nativeint
  val surface_configuration_get_alpha_mode : t -> int
  val surface_configuration_get_present_mode : t -> int
end

module Surface_Descriptor : sig
  type t = nativeint
  val surface_descriptor_create : unit -> t
  val surface_descriptor_free : t -> unit
  val surface_descriptor_set_label : t -> string -> unit
  val surface_descriptor_get_label : t -> string
end

module Surface_Source_Android_Native_Window : sig
  type t = nativeint
  val surface_source_android_native_window_create : unit -> t
  val surface_source_android_native_window_free : t -> unit
  val surface_source_android_native_window_set_window : t -> nativeint -> unit
  val surface_source_android_native_window_get_window : t -> nativeint
end

module Surface_Source_Metal_Layer : sig
  type t = nativeint
  val surface_source_metal_layer_create : unit -> t
  val surface_source_metal_layer_free : t -> unit
  val surface_source_metal_layer_set_layer : t -> nativeint -> unit
  val surface_source_metal_layer_get_layer : t -> nativeint
end

module Surface_Source_Wayland_Surface : sig
  type t = nativeint
  val surface_source_wayland_surface_create : unit -> t
  val surface_source_wayland_surface_free : t -> unit
  val surface_source_wayland_surface_set_display : t -> nativeint -> unit
  val surface_source_wayland_surface_set_surface : t -> nativeint -> unit
  val surface_source_wayland_surface_get_display : t -> nativeint
  val surface_source_wayland_surface_get_surface : t -> nativeint
end

module Surface_Source_Windows_HWND : sig
  type t = nativeint
  val surface_source_windows_HWND_create : unit -> t
  val surface_source_windows_HWND_free : t -> unit
  val surface_source_windows_HWND_set_hinstance : t -> nativeint -> unit
  val surface_source_windows_HWND_set_hwnd : t -> nativeint -> unit
  val surface_source_windows_HWND_get_hinstance : t -> nativeint
  val surface_source_windows_HWND_get_hwnd : t -> nativeint
end

module Surface_Source_XCB_Window : sig
  type t = nativeint
  val surface_source_XCB_window_create : unit -> t
  val surface_source_XCB_window_free : t -> unit
  val surface_source_XCB_window_set_connection : t -> nativeint -> unit
  val surface_source_XCB_window_set_window : t -> int -> unit
  val surface_source_XCB_window_get_connection : t -> nativeint
  val surface_source_XCB_window_get_window : t -> int
end

module Surface_Source_Xlib_Window : sig
  type t = nativeint
  val surface_source_xlib_window_create : unit -> t
  val surface_source_xlib_window_free : t -> unit
  val surface_source_xlib_window_set_display : t -> nativeint -> unit
  val surface_source_xlib_window_set_window : t -> int64 -> unit
  val surface_source_xlib_window_get_display : t -> nativeint
  val surface_source_xlib_window_get_window : t -> int64
end

module Surface_Texture : sig
  type t = nativeint
  val surface_texture_create : unit -> t
  val surface_texture_free : t -> unit
  val surface_texture_set_texture : t -> nativeint -> unit
  val surface_texture_set_status : t -> int -> unit
  val surface_texture_get_texture : t -> nativeint
  val surface_texture_get_status : t -> int
end

module Texel_Copy_Buffer_Info : sig
  type t = nativeint
  val texel_copy_buffer_info_create : unit -> t
  val texel_copy_buffer_info_free : t -> unit
  val texel_copy_buffer_info_set_layout : t -> nativeint -> unit
  val texel_copy_buffer_info_set_buffer : t -> nativeint -> unit
  val texel_copy_buffer_info_get_layout : t -> nativeint
  val texel_copy_buffer_info_get_buffer : t -> nativeint
end

module Texel_Copy_Buffer_Layout : sig
  type t = nativeint
  val texel_copy_buffer_layout_create : unit -> t
  val texel_copy_buffer_layout_free : t -> unit
  val texel_copy_buffer_layout_set_offset : t -> int64 -> unit
  val texel_copy_buffer_layout_set_bytes_per_row : t -> int -> unit
  val texel_copy_buffer_layout_set_rows_per_image : t -> int -> unit
  val texel_copy_buffer_layout_get_offset : t -> int64
  val texel_copy_buffer_layout_get_bytes_per_row : t -> int
  val texel_copy_buffer_layout_get_rows_per_image : t -> int
end

module Texel_Copy_Texture_Info : sig
  type t = nativeint
  val texel_copy_texture_info_create : unit -> t
  val texel_copy_texture_info_free : t -> unit
  val texel_copy_texture_info_set_texture : t -> nativeint -> unit
  val texel_copy_texture_info_set_mip_level : t -> int -> unit
  val texel_copy_texture_info_set_origin : t -> nativeint -> unit
  val texel_copy_texture_info_set_aspect : t -> int -> unit
  val texel_copy_texture_info_get_texture : t -> nativeint
  val texel_copy_texture_info_get_mip_level : t -> int
  val texel_copy_texture_info_get_origin : t -> nativeint
  val texel_copy_texture_info_get_aspect : t -> int
end

module Texture_Binding_Layout : sig
  type t = nativeint
  val texture_binding_layout_create : unit -> t
  val texture_binding_layout_free : t -> unit
  val texture_binding_layout_set_sample_type : t -> int -> unit
  val texture_binding_layout_set_view_dimension : t -> int -> unit
  val texture_binding_layout_set_multisampled : t -> bool -> unit
  val texture_binding_layout_get_sample_type : t -> int
  val texture_binding_layout_get_view_dimension : t -> int
  val texture_binding_layout_get_multisampled : t -> bool
end

module Texture_Descriptor : sig
  type t = nativeint
  val texture_descriptor_create : unit -> t
  val texture_descriptor_free : t -> unit
  val texture_descriptor_set_label : t -> string -> unit
  val texture_descriptor_set_usage : t -> int -> unit
  val texture_descriptor_set_dimension : t -> int -> unit
  val texture_descriptor_set_size : t -> nativeint -> unit
  val texture_descriptor_set_format : t -> int -> unit
  val texture_descriptor_set_mip_level_count : t -> int -> unit
  val texture_descriptor_set_sample_count : t -> int -> unit
  val texture_descriptor_set_view_formats : t -> int array -> unit
  val texture_descriptor_get_label : t -> string
  val texture_descriptor_get_usage : t -> int
  val texture_descriptor_get_dimension : t -> int
  val texture_descriptor_get_size : t -> nativeint
  val texture_descriptor_get_format : t -> int
  val texture_descriptor_get_mip_level_count : t -> int
  val texture_descriptor_get_sample_count : t -> int
  val texture_descriptor_get_view_formats : t -> nativeint
end

module Texture_View_Descriptor : sig
  type t = nativeint
  val texture_view_descriptor_create : unit -> t
  val texture_view_descriptor_free : t -> unit
  val texture_view_descriptor_set_label : t -> string -> unit
  val texture_view_descriptor_set_format : t -> int -> unit
  val texture_view_descriptor_set_dimension : t -> int -> unit
  val texture_view_descriptor_set_base_mip_level : t -> int -> unit
  val texture_view_descriptor_set_mip_level_count : t -> int -> unit
  val texture_view_descriptor_set_base_array_layer : t -> int -> unit
  val texture_view_descriptor_set_array_layer_count : t -> int -> unit
  val texture_view_descriptor_set_aspect : t -> int -> unit
  val texture_view_descriptor_set_usage : t -> int -> unit
  val texture_view_descriptor_get_label : t -> string
  val texture_view_descriptor_get_format : t -> int
  val texture_view_descriptor_get_dimension : t -> int
  val texture_view_descriptor_get_base_mip_level : t -> int
  val texture_view_descriptor_get_mip_level_count : t -> int
  val texture_view_descriptor_get_base_array_layer : t -> int
  val texture_view_descriptor_get_array_layer_count : t -> int
  val texture_view_descriptor_get_aspect : t -> int
  val texture_view_descriptor_get_usage : t -> int
end

module Vertex_Attribute : sig
  type t = nativeint
  val vertex_attribute_create : unit -> t
  val vertex_attribute_free : t -> unit
  val vertex_attribute_set_format : t -> int -> unit
  val vertex_attribute_set_offset : t -> int64 -> unit
  val vertex_attribute_set_shader_location : t -> int -> unit
  val vertex_attribute_get_format : t -> int
  val vertex_attribute_get_offset : t -> int64
  val vertex_attribute_get_shader_location : t -> int
end

module Vertex_Buffer_Layout : sig
  type t = nativeint
  val vertex_buffer_layout_create : unit -> t
  val vertex_buffer_layout_free : t -> unit
  val vertex_buffer_layout_set_step_mode : t -> int -> unit
  val vertex_buffer_layout_set_array_stride : t -> int64 -> unit
  val vertex_buffer_layout_set_attributes : t -> nativeint array -> unit
  val vertex_buffer_layout_get_step_mode : t -> int
  val vertex_buffer_layout_get_array_stride : t -> int64
  val vertex_buffer_layout_get_attributes : t -> nativeint
end

module Vertex_State : sig
  type t = nativeint
  val vertex_state_create : unit -> t
  val vertex_state_free : t -> unit
  val vertex_state_set_module : t -> nativeint -> unit
  val vertex_state_set_entry_point : t -> string -> unit
  val vertex_state_set_constants : t -> nativeint array -> unit
  val vertex_state_set_buffers : t -> nativeint array -> unit
  val vertex_state_get_module : t -> nativeint
  val vertex_state_get_entry_point : t -> string
  val vertex_state_get_constants : t -> nativeint
  val vertex_state_get_buffers : t -> nativeint
end
type adapter = nativeint
type bind_group = nativeint
type bind_group_layout = nativeint
type buffer = nativeint
type command_buffer = nativeint
type command_encoder = nativeint
type compute_pass_encoder = nativeint
type compute_pipeline = nativeint
type device = nativeint
type instance = nativeint
type pipeline_layout = nativeint
type query_set = nativeint
type queue = nativeint
type render_bundle = nativeint
type render_bundle_encoder = nativeint
type render_pass_encoder = nativeint
type render_pipeline = nativeint
type sampler = nativeint
type shader_module = nativeint
type surface = nativeint
type texture = nativeint
type texture_view = nativeint

val adapter_release : adapter -> unit
val adapter_get_limits : adapter -> nativeint -> int
val adapter_has_feature : adapter -> int -> bool
val adapter_get_features : adapter -> nativeint -> unit

val bind_group_release : bind_group -> unit
val bind_group_set_label : bind_group -> string -> unit

val bind_group_layout_release : bind_group_layout -> unit
val bind_group_layout_set_label : bind_group_layout -> string -> unit

val buffer_release : buffer -> unit
val buffer_get_mapped_range : buffer -> int64 -> int64 -> nativeint
val buffer_get_const_mapped_range : buffer -> int64 -> int64 -> nativeint
val buffer_set_label : buffer -> string -> unit
val buffer_get_usage : buffer -> int
val buffer_get_size : buffer -> int64
val buffer_get_map_state : buffer -> int
val buffer_unmap : buffer -> unit
val buffer_destroy : buffer -> unit

val command_buffer_release : command_buffer -> unit
val command_buffer_set_label : command_buffer -> string -> unit

val command_encoder_release : command_encoder -> unit
val command_encoder_finish : command_encoder -> nativeint -> command_buffer
val command_encoder_begin_compute_pass : command_encoder -> nativeint -> compute_pass_encoder
val command_encoder_begin_render_pass : command_encoder -> nativeint -> render_pass_encoder
val command_encoder_copy_buffer_to_buffer : command_encoder -> buffer -> int64 -> buffer -> int64 -> int64 -> unit
val command_encoder_copy_buffer_to_texture : command_encoder -> nativeint -> nativeint -> nativeint -> unit
val command_encoder_copy_texture_to_buffer : command_encoder -> nativeint -> nativeint -> nativeint -> unit
val command_encoder_copy_texture_to_texture : command_encoder -> nativeint -> nativeint -> nativeint -> unit
val command_encoder_clear_buffer : command_encoder -> buffer -> int64 -> int64 -> unit
val command_encoder_insert_debug_marker : command_encoder -> string -> unit
val command_encoder_pop_debug_group : command_encoder -> unit
val command_encoder_push_debug_group : command_encoder -> string -> unit
val command_encoder_resolve_query_set : command_encoder -> query_set -> int -> int -> buffer -> int64 -> unit
val command_encoder_write_timestamp : command_encoder -> query_set -> int -> unit
val command_encoder_set_label : command_encoder -> string -> unit

val compute_pass_encoder_release : compute_pass_encoder -> unit
val compute_pass_encoder_insert_debug_marker : compute_pass_encoder -> string -> unit
val compute_pass_encoder_pop_debug_group : compute_pass_encoder -> unit
val compute_pass_encoder_push_debug_group : compute_pass_encoder -> string -> unit
val compute_pass_encoder_set_pipeline : compute_pass_encoder -> compute_pipeline -> unit
val compute_pass_encoder_set_bind_group : compute_pass_encoder -> int -> bind_group -> int array -> unit
val compute_pass_encoder_dispatch_workgroups : compute_pass_encoder -> int -> int -> int -> unit
val compute_pass_encoder_dispatch_workgroups_indirect : compute_pass_encoder -> buffer -> int64 -> unit
val compute_pass_encoder_end : compute_pass_encoder -> unit
val compute_pass_encoder_set_label : compute_pass_encoder -> string -> unit

val compute_pipeline_release : compute_pipeline -> unit
val compute_pipeline_get_bind_group_layout : compute_pipeline -> int -> bind_group_layout
val compute_pipeline_set_label : compute_pipeline -> string -> unit

val device_release : device -> unit
val device_create_bind_group : device -> nativeint -> bind_group
val device_create_bind_group_layout : device -> nativeint -> bind_group_layout
val device_create_buffer : device -> nativeint -> buffer
val device_create_command_encoder : device -> nativeint -> command_encoder
val device_create_compute_pipeline : device -> nativeint -> compute_pipeline
val device_create_pipeline_layout : device -> nativeint -> pipeline_layout
val device_create_query_set : device -> nativeint -> query_set
val device_create_render_bundle_encoder : device -> nativeint -> render_bundle_encoder
val device_create_render_pipeline : device -> nativeint -> render_pipeline
val device_create_sampler : device -> nativeint -> sampler
val device_create_shader_module : device -> nativeint -> shader_module
val device_create_texture : device -> nativeint -> texture
val device_destroy : device -> unit
val device_get_lost_future : device -> nativeint
val device_get_limits : device -> nativeint -> int
val device_has_feature : device -> int -> bool
val device_get_features : device -> nativeint -> unit
val device_get_adapter_info : device -> nativeint
val device_push_error_scope : device -> int -> unit
val device_set_label : device -> string -> unit

val instance_release : instance -> unit
val instance_create_surface : instance -> nativeint -> surface
val instance_get_WGSL_language_features : instance -> nativeint -> int
val instance_has_WGSL_language_feature : instance -> int -> bool
val instance_process_events : instance -> unit
val instance_wait_any : instance -> int64 -> nativeint -> int64 -> int

val pipeline_layout_release : pipeline_layout -> unit
val pipeline_layout_set_label : pipeline_layout -> string -> unit

val query_set_release : query_set -> unit
val query_set_set_label : query_set -> string -> unit
val query_set_get_type : query_set -> int
val query_set_get_count : query_set -> int
val query_set_destroy : query_set -> unit

val queue_release : queue -> unit
val queue_submit : queue -> command_buffer array -> unit
val queue_write_buffer : queue -> buffer -> int64 -> nativeint -> int64 -> unit
val queue_write_texture : queue -> nativeint -> nativeint -> int64 -> nativeint -> nativeint -> unit
val queue_set_label : queue -> string -> unit

val render_bundle_release : render_bundle -> unit
val render_bundle_set_label : render_bundle -> string -> unit

val render_bundle_encoder_release : render_bundle_encoder -> unit
val render_bundle_encoder_set_pipeline : render_bundle_encoder -> render_pipeline -> unit
val render_bundle_encoder_set_bind_group : render_bundle_encoder -> int -> bind_group -> int array -> unit
val render_bundle_encoder_draw : render_bundle_encoder -> int -> int -> int -> int -> unit
val render_bundle_encoder_draw_indexed : render_bundle_encoder -> int -> int -> int -> int -> int -> unit
val render_bundle_encoder_draw_indirect : render_bundle_encoder -> buffer -> int64 -> unit
val render_bundle_encoder_draw_indexed_indirect : render_bundle_encoder -> buffer -> int64 -> unit
val render_bundle_encoder_insert_debug_marker : render_bundle_encoder -> string -> unit
val render_bundle_encoder_pop_debug_group : render_bundle_encoder -> unit
val render_bundle_encoder_push_debug_group : render_bundle_encoder -> string -> unit
val render_bundle_encoder_set_vertex_buffer : render_bundle_encoder -> int -> buffer -> int64 -> int64 -> unit
val render_bundle_encoder_set_index_buffer : render_bundle_encoder -> buffer -> int -> int64 -> int64 -> unit
val render_bundle_encoder_finish : render_bundle_encoder -> nativeint -> render_bundle
val render_bundle_encoder_set_label : render_bundle_encoder -> string -> unit

val render_pass_encoder_release : render_pass_encoder -> unit
val render_pass_encoder_set_pipeline : render_pass_encoder -> render_pipeline -> unit
val render_pass_encoder_set_bind_group : render_pass_encoder -> int -> bind_group -> int array -> unit
val render_pass_encoder_draw : render_pass_encoder -> int -> int -> int -> int -> unit
val render_pass_encoder_draw_indexed : render_pass_encoder -> int -> int -> int -> int -> int -> unit
val render_pass_encoder_draw_indirect : render_pass_encoder -> buffer -> int64 -> unit
val render_pass_encoder_draw_indexed_indirect : render_pass_encoder -> buffer -> int64 -> unit
val render_pass_encoder_execute_bundles : render_pass_encoder -> render_bundle array -> unit
val render_pass_encoder_insert_debug_marker : render_pass_encoder -> string -> unit
val render_pass_encoder_pop_debug_group : render_pass_encoder -> unit
val render_pass_encoder_push_debug_group : render_pass_encoder -> string -> unit
val render_pass_encoder_set_stencil_reference : render_pass_encoder -> int -> unit
val render_pass_encoder_set_blend_constant : render_pass_encoder -> nativeint -> unit
val render_pass_encoder_set_viewport : render_pass_encoder -> float -> float -> float -> float -> float -> float -> unit
val render_pass_encoder_set_scissor_rect : render_pass_encoder -> int -> int -> int -> int -> unit
val render_pass_encoder_set_vertex_buffer : render_pass_encoder -> int -> buffer -> int64 -> int64 -> unit
val render_pass_encoder_set_index_buffer : render_pass_encoder -> buffer -> int -> int64 -> int64 -> unit
val render_pass_encoder_begin_occlusion_query : render_pass_encoder -> int -> unit
val render_pass_encoder_end_occlusion_query : render_pass_encoder -> unit
val render_pass_encoder_end : render_pass_encoder -> unit
val render_pass_encoder_set_label : render_pass_encoder -> string -> unit

val render_pipeline_release : render_pipeline -> unit
val render_pipeline_get_bind_group_layout : render_pipeline -> int -> bind_group_layout
val render_pipeline_set_label : render_pipeline -> string -> unit

val sampler_release : sampler -> unit
val sampler_set_label : sampler -> string -> unit

val shader_module_release : shader_module -> unit
val shader_module_set_label : shader_module -> string -> unit

val surface_release : surface -> unit
val surface_configure : surface -> nativeint -> unit
val surface_get_capabilities : surface -> adapter -> nativeint -> int
val surface_get_current_texture : surface -> nativeint -> unit
val surface_present : surface -> int
val surface_unconfigure : surface -> unit
val surface_set_label : surface -> string -> unit

val texture_release : texture -> unit
val texture_create_view : texture -> nativeint -> texture_view
val texture_set_label : texture -> string -> unit
val texture_get_width : texture -> int
val texture_get_height : texture -> int
val texture_get_depth_or_array_layers : texture -> int
val texture_get_mip_level_count : texture -> int
val texture_get_sample_count : texture -> int
val texture_get_dimension : texture -> int
val texture_get_format : texture -> int
val texture_get_usage : texture -> int
val texture_destroy : texture -> unit

val texture_view_release : texture_view -> unit
val texture_view_set_label : texture_view -> string -> unit
val create_instance : unit -> instance

val instance_request_adapter_sync : instance -> adapter

val adapter_request_device_sync : adapter -> device

val device_get_queue : device -> queue

type adapter_info =
  { vendor : string
  ; architecture : string
  ; device : string
  ; description : string
  ; backend_type : int
  ; adapter_type : int
  }

val adapter_get_info : adapter -> adapter_info

val device_create_shader_module_wgsl : device -> string -> string -> shader_module

val device_create_command_encoder_simple : device -> string -> command_encoder

val command_encoder_begin_compute_pass_simple : command_encoder -> string -> compute_pass_encoder

val command_encoder_finish_simple : command_encoder -> string -> command_buffer

val queue_submit_single : queue -> command_buffer -> unit

val compute_pass_encoder_set_bind_group_simple : compute_pass_encoder -> int -> bind_group -> unit

val device_poll : device -> bool -> unit

val buffer_map_sync : buffer -> int -> int64 -> int64 -> int

val buffer_get_mapped_range_bigarray :
  buffer -> int64 -> int64 -> (int, Bigarray.int8_unsigned_elt, Bigarray.c_layout) Bigarray.Array1.t

val buffer_get_const_mapped_range_bigarray :
  buffer -> int64 -> int64 -> (int, Bigarray.int8_unsigned_elt, Bigarray.c_layout) Bigarray.Array1.t

val queue_write_buffer_bigarray :
  queue -> buffer -> int64 -> (_, _, Bigarray.c_layout) Bigarray.Array1.t -> unit

val device_create_bind_group_layout_storage :
  device -> string -> int -> bool -> bind_group_layout

val device_create_bind_group_buffer :
  device -> string -> bind_group_layout -> int -> buffer -> int64 -> int64 -> bind_group

val device_create_pipeline_layout_single :
  device -> string -> bind_group_layout -> pipeline_layout

val device_create_compute_pipeline_simple :
  device -> string -> pipeline_layout -> shader_module -> string -> compute_pipeline

val device_create_texture_2d :
  device -> string -> int -> int -> int -> int -> texture

val texture_create_view_simple : texture -> string -> texture_view

val command_encoder_begin_render_pass_simple :
  command_encoder -> string -> texture_view -> float -> float -> float -> float -> render_pass_encoder

val command_encoder_copy_texture_to_buffer_simple :
  command_encoder -> texture -> buffer -> int -> int -> int -> unit

val device_create_render_pipeline_simple :
  device -> string -> shader_module -> string -> string -> int -> render_pipeline
