/* Generated by gen_bindings - low-level C stubs */
#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/custom.h>
#include <caml/fail.h>

#include "webgpu.h"
#include "wgpu.h"

/* Minimal test stub: create a wgpu instance */
CAMLprim value caml_wgpu_create_instance(value unit) {
  CAMLparam1(unit);
  WGPUInstanceDescriptor desc = {
    .nextInChain = NULL,
  };
  WGPUInstance instance = wgpuCreateInstance(&desc);
  /* For now, just return the pointer as a nativeint */
  CAMLreturn(caml_copy_nativeint((intnat)instance));
}

/* Release an instance */
CAMLprim value caml_wgpu_instance_release(value instance_val) {
  CAMLparam1(instance_val);
  WGPUInstance instance = (WGPUInstance)Nativeint_val(instance_val);
  if (instance != NULL) {
    wgpuInstanceRelease(instance);
  }
  CAMLreturn(Val_unit);
}
