(* Generated by gen_bindings - low-level OCaml bindings *)

(** Raw instance handle *)
type instance = nativeint

(** Create a new wgpu instance with default settings *)
external create_instance : unit -> instance = "caml_wgpu_create_instance"

(** Release an instance *)
external instance_release : instance -> unit = "caml_wgpu_instance_release"
