(* Generated by gen_bindings - low-level OCaml interface *)

module Adapter_Type : sig
  type t =
  | Discrete_gpu
  | Integrated_gpu
  | Cpu
  | Unknown

  val to_int : t -> int
end

module Address_Mode : sig
  type t =
  | Undefined
  | Clamp_to_edge
  | Repeat
  | Mirror_repeat

  val to_int : t -> int
end

module Backend_Type : sig
  type t =
  | Undefined
  | Null
  | Webgpu
  | D3d11
  | D3d12
  | Metal
  | Vulkan
  | Opengl
  | Opengles

  val to_int : t -> int
end

module Blend_Factor : sig
  type t =
  | Undefined
  | Zero
  | One
  | Src
  | One_minus_src
  | Src_alpha
  | One_minus_src_alpha
  | Dst
  | One_minus_dst
  | Dst_alpha
  | One_minus_dst_alpha
  | Src_alpha_saturated
  | Constant
  | One_minus_constant
  | Src1
  | One_minus_src1
  | Src1_alpha
  | One_minus_src1_alpha

  val to_int : t -> int
end

module Blend_Operation : sig
  type t =
  | Undefined
  | Add
  | Subtract
  | Reverse_subtract
  | Min
  | Max

  val to_int : t -> int
end

module Buffer_Binding_Type : sig
  type t =
  | Binding_not_used
  | Undefined
  | Uniform
  | Storage
  | Read_only_storage

  val to_int : t -> int
end

module Buffer_Map_State : sig
  type t =
  | Unmapped
  | Pending
  | Mapped

  val to_int : t -> int
end

module Callback_Mode : sig
  type t =
  | Wait_any_only
  | Allow_process_events
  | Allow_spontaneous

  val to_int : t -> int
end

module Compare_Function : sig
  type t =
  | Undefined
  | Never
  | Less
  | Equal
  | Less_equal
  | Greater
  | Not_equal
  | Greater_equal
  | Always

  val to_int : t -> int
end

module Compilation_Info_Request_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

  val to_int : t -> int
end

module Compilation_Message_Type : sig
  type t =
  | Error
  | Warning
  | Info

  val to_int : t -> int
end

module Composite_Alpha_Mode : sig
  type t =
  | Auto
  | Opaque
  | Premultiplied
  | Unpremultiplied
  | Inherit

  val to_int : t -> int
end

module Create_Pipeline_Async_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Validation_error
  | Internal_error
  | Unknown

  val to_int : t -> int
end

module Cull_Mode : sig
  type t =
  | Undefined
  | None
  | Front
  | Back

  val to_int : t -> int
end

module Device_Lost_Reason : sig
  type t =
  | Unknown
  | Destroyed
  | Instance_dropped
  | Failed_creation

  val to_int : t -> int
end

module Error_Filter : sig
  type t =
  | Validation
  | Out_of_memory
  | Internal

  val to_int : t -> int
end

module Error_Type : sig
  type t =
  | No_error
  | Validation
  | Out_of_memory
  | Internal
  | Unknown

  val to_int : t -> int
end

module Feature_Level : sig
  type t =
  | Compatibility
  | Core

  val to_int : t -> int
end

module Feature_Name : sig
  type t =
  | Undefined
  | Depth_clip_control
  | Depth32_float_stencil8
  | Timestamp_query
  | Texture_compression_bc
  | Texture_compression_bc_sliced_3d
  | Texture_compression_etc2
  | Texture_compression_astc
  | Texture_compression_astc_sliced_3d
  | Indirect_first_instance
  | Shader_f16
  | Rg11b10_ufloat_renderable
  | Bgra8_unorm_storage
  | Float32_filterable
  | Float32_blendable
  | Clip_distances
  | Dual_source_blending

  val to_int : t -> int
end

module Filter_Mode : sig
  type t =
  | Undefined
  | Nearest
  | Linear

  val to_int : t -> int
end

module Front_Face : sig
  type t =
  | Undefined
  | Ccw
  | Cw

  val to_int : t -> int
end

module Index_Format : sig
  type t =
  | Undefined
  | Uint16
  | Uint32

  val to_int : t -> int
end

module Load_Op : sig
  type t =
  | Undefined
  | Load
  | Clear

  val to_int : t -> int
end

module Map_Async_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Aborted
  | Unknown

  val to_int : t -> int
end

module Mipmap_Filter_Mode : sig
  type t =
  | Undefined
  | Nearest
  | Linear

  val to_int : t -> int
end

module Optional_Bool : sig
  type t =
  | False
  | True
  | Undefined

  val to_int : t -> int
end

module Pop_Error_Scope_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Empty_stack

  val to_int : t -> int
end

module Power_Preference : sig
  type t =
  | Undefined
  | Low_power
  | High_performance

  val to_int : t -> int
end

module Present_Mode : sig
  type t =
  | Undefined
  | Fifo
  | Fifo_relaxed
  | Immediate
  | Mailbox

  val to_int : t -> int
end

module Primitive_Topology : sig
  type t =
  | Undefined
  | Point_list
  | Line_list
  | Line_strip
  | Triangle_list
  | Triangle_strip

  val to_int : t -> int
end

module Query_Type : sig
  type t =
  | Occlusion
  | Timestamp

  val to_int : t -> int
end

module Queue_Work_Done_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

  val to_int : t -> int
end

module Request_Adapter_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Unavailable
  | Error
  | Unknown

  val to_int : t -> int
end

module Request_Device_Status : sig
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

  val to_int : t -> int
end

module S_Type : sig
  type t =
  | Shader_source_spirv
  | Shader_source_wgsl
  | Render_pass_max_draw_count
  | Surface_source_metal_layer
  | Surface_source_windows_hwnd
  | Surface_source_xlib_window
  | Surface_source_wayland_surface
  | Surface_source_android_native_window
  | Surface_source_xcb_window

  val to_int : t -> int
end

module Sampler_Binding_Type : sig
  type t =
  | Binding_not_used
  | Undefined
  | Filtering
  | Non_filtering
  | Comparison

  val to_int : t -> int
end

module Status : sig
  type t =
  | Success
  | Error

  val to_int : t -> int
end

module Stencil_Operation : sig
  type t =
  | Undefined
  | Keep
  | Zero
  | Replace
  | Invert
  | Increment_clamp
  | Decrement_clamp
  | Increment_wrap
  | Decrement_wrap

  val to_int : t -> int
end

module Storage_Texture_Access : sig
  type t =
  | Binding_not_used
  | Undefined
  | Write_only
  | Read_only
  | Read_write

  val to_int : t -> int
end

module Store_Op : sig
  type t =
  | Undefined
  | Store
  | Discard

  val to_int : t -> int
end

module Surface_Get_Current_Texture_Status : sig
  type t =
  | Success_optimal
  | Success_suboptimal
  | Timeout
  | Outdated
  | Lost
  | Out_of_memory
  | Device_lost
  | Error

  val to_int : t -> int
end

module Texture_Aspect : sig
  type t =
  | Undefined
  | All
  | Stencil_only
  | Depth_only

  val to_int : t -> int
end

module Texture_Dimension : sig
  type t =
  | Undefined
  | N1d
  | N2d
  | N3d

  val to_int : t -> int
end

module Texture_Format : sig
  type t =
  | Undefined
  | R8_unorm
  | R8_snorm
  | R8_uint
  | R8_sint
  | R16_uint
  | R16_sint
  | R16_float
  | Rg8_unorm
  | Rg8_snorm
  | Rg8_uint
  | Rg8_sint
  | R32_float
  | R32_uint
  | R32_sint
  | Rg16_uint
  | Rg16_sint
  | Rg16_float
  | Rgba8_unorm
  | Rgba8_unorm_srgb
  | Rgba8_snorm
  | Rgba8_uint
  | Rgba8_sint
  | Bgra8_unorm
  | Bgra8_unorm_srgb
  | Rgb10_a2_uint
  | Rgb10_a2_unorm
  | Rg11_b10_ufloat
  | Rgb9_e5_ufloat
  | Rg32_float
  | Rg32_uint
  | Rg32_sint
  | Rgba16_uint
  | Rgba16_sint
  | Rgba16_float
  | Rgba32_float
  | Rgba32_uint
  | Rgba32_sint
  | Stencil8
  | Depth16_unorm
  | Depth24_plus
  | Depth24_plus_stencil8
  | Depth32_float
  | Depth32_float_stencil8
  | Bc1_rgba_unorm
  | Bc1_rgba_unorm_srgb
  | Bc2_rgba_unorm
  | Bc2_rgba_unorm_srgb
  | Bc3_rgba_unorm
  | Bc3_rgba_unorm_srgb
  | Bc4_r_unorm
  | Bc4_r_snorm
  | Bc5_rg_unorm
  | Bc5_rg_snorm
  | Bc6h_rgb_ufloat
  | Bc6h_rgb_float
  | Bc7_rgba_unorm
  | Bc7_rgba_unorm_srgb
  | Etc2_rgb8_unorm
  | Etc2_rgb8_unorm_srgb
  | Etc2_rgb8a1_unorm
  | Etc2_rgb8a1_unorm_srgb
  | Etc2_rgba8_unorm
  | Etc2_rgba8_unorm_srgb
  | Eac_r11_unorm
  | Eac_r11_snorm
  | Eac_rg11_unorm
  | Eac_rg11_snorm
  | Astc_4x4_unorm
  | Astc_4x4_unorm_srgb
  | Astc_5x4_unorm
  | Astc_5x4_unorm_srgb
  | Astc_5x5_unorm
  | Astc_5x5_unorm_srgb
  | Astc_6x5_unorm
  | Astc_6x5_unorm_srgb
  | Astc_6x6_unorm
  | Astc_6x6_unorm_srgb
  | Astc_8x5_unorm
  | Astc_8x5_unorm_srgb
  | Astc_8x6_unorm
  | Astc_8x6_unorm_srgb
  | Astc_8x8_unorm
  | Astc_8x8_unorm_srgb
  | Astc_10x5_unorm
  | Astc_10x5_unorm_srgb
  | Astc_10x6_unorm
  | Astc_10x6_unorm_srgb
  | Astc_10x8_unorm
  | Astc_10x8_unorm_srgb
  | Astc_10x10_unorm
  | Astc_10x10_unorm_srgb
  | Astc_12x10_unorm
  | Astc_12x10_unorm_srgb
  | Astc_12x12_unorm
  | Astc_12x12_unorm_srgb

  val to_int : t -> int
end

module Texture_Sample_Type : sig
  type t =
  | Binding_not_used
  | Undefined
  | Float
  | Unfilterable_float
  | Depth
  | Sint
  | Uint

  val to_int : t -> int
end

module Texture_View_Dimension : sig
  type t =
  | Undefined
  | N1d
  | N2d
  | N2d_array
  | Cube
  | Cube_array
  | N3d

  val to_int : t -> int
end

module Vertex_Format : sig
  type t =
  | Uint8
  | Uint8x2
  | Uint8x4
  | Sint8
  | Sint8x2
  | Sint8x4
  | Unorm8
  | Unorm8x2
  | Unorm8x4
  | Snorm8
  | Snorm8x2
  | Snorm8x4
  | Uint16
  | Uint16x2
  | Uint16x4
  | Sint16
  | Sint16x2
  | Sint16x4
  | Unorm16
  | Unorm16x2
  | Unorm16x4
  | Snorm16
  | Snorm16x2
  | Snorm16x4
  | Float16
  | Float16x2
  | Float16x4
  | Float32
  | Float32x2
  | Float32x3
  | Float32x4
  | Uint32
  | Uint32x2
  | Uint32x3
  | Uint32x4
  | Sint32
  | Sint32x2
  | Sint32x3
  | Sint32x4
  | Unorm10__10__10__2
  | Unorm8x4_b_g_r_a

  val to_int : t -> int
end

module Vertex_Step_Mode : sig
  type t =
  | Vertex_buffer_not_used
  | Undefined
  | Vertex
  | Instance

  val to_int : t -> int
end

module Wait_Status : sig
  type t =
  | Success
  | Timed_out
  | Unsupported_timeout
  | Unsupported_count
  | Unsupported_mixed_sources

  val to_int : t -> int
end

module WGSL_Language_Feature_Name : sig
  type t =
  | Readonly_and_readwrite_storage_textures
  | Packed4x8_integer_dot_product
  | Unrestricted_pointer_parameters
  | Pointer_composite_access

  val to_int : t -> int
end
module Buffer_Usage : sig
  type t =
  | None
  | Map_read
  | Map_write
  | Copy_src
  | Copy_dst
  | Index
  | Vertex
  | Uniform
  | Storage
  | Indirect
  | Query_resolve

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Color_Write_Mask : sig
  type t =
  | None
  | Red
  | Green
  | Blue
  | Alpha
  | All

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Map_Mode : sig
  type t =
  | None
  | Read
  | Write

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Shader_Stage : sig
  type t =
  | None
  | Vertex
  | Fragment
  | Compute

  val to_int : t -> int
  val list_to_int : t list -> int
end

module Texture_Usage : sig
  type t =
  | None
  | Copy_src
  | Copy_dst
  | Texture_binding
  | Storage_binding
  | Render_attachment

  val to_int : t -> int
  val list_to_int : t list -> int
end
type adapter = nativeint

val adapter_release : adapter -> unit

type bind_group = nativeint

val bind_group_release : bind_group -> unit

type bind_group_layout = nativeint

val bind_group_layout_release : bind_group_layout -> unit

type buffer = nativeint

val buffer_release : buffer -> unit

type command_buffer = nativeint

val command_buffer_release : command_buffer -> unit

type command_encoder = nativeint

val command_encoder_release : command_encoder -> unit

type compute_pass_encoder = nativeint

val compute_pass_encoder_release : compute_pass_encoder -> unit

type compute_pipeline = nativeint

val compute_pipeline_release : compute_pipeline -> unit

type device = nativeint

val device_release : device -> unit

type instance = nativeint

val instance_release : instance -> unit

type pipeline_layout = nativeint

val pipeline_layout_release : pipeline_layout -> unit

type query_set = nativeint

val query_set_release : query_set -> unit

type queue = nativeint

val queue_release : queue -> unit

type render_bundle = nativeint

val render_bundle_release : render_bundle -> unit

type render_bundle_encoder = nativeint

val render_bundle_encoder_release : render_bundle_encoder -> unit

type render_pass_encoder = nativeint

val render_pass_encoder_release : render_pass_encoder -> unit

type render_pipeline = nativeint

val render_pipeline_release : render_pipeline -> unit

type sampler = nativeint

val sampler_release : sampler -> unit

type shader_module = nativeint

val shader_module_release : shader_module -> unit

type surface = nativeint (** An object used to continuously present image data to the user, see @ref Surfaces for more details. *)

val surface_release : surface -> unit

type texture = nativeint

val texture_release : texture -> unit

type texture_view = nativeint

val texture_view_release : texture_view -> unit
val create_instance : unit -> instance
