(* Generated by gen_bindings - low-level OCaml interface *)

(** Raw instance handle *)
type instance = nativeint

(** Create a new wgpu instance with default settings *)
val create_instance : unit -> instance

(** Release an instance *)
val instance_release : instance -> unit
