(* Generated by gen_bindings - low-level OCaml bindings *)

module Adapter_Type = struct
  type t =
  | Discrete_gpu
  | Integrated_gpu
  | Cpu
  | Unknown

external adapter_type_discrete_gpu : unit -> int = "caml_wgpu_adapter_type_discrete_gpu"
external adapter_type_integrated_gpu : unit -> int = "caml_wgpu_adapter_type_integrated_gpu"
external adapter_type_cpu : unit -> int = "caml_wgpu_adapter_type_cpu"
external adapter_type_unknown : unit -> int = "caml_wgpu_adapter_type_unknown"

  let to_int = function
    | Discrete_gpu -> adapter_type_discrete_gpu ()
    | Integrated_gpu -> adapter_type_integrated_gpu ()
    | Cpu -> adapter_type_cpu ()
    | Unknown -> adapter_type_unknown ()
end

module Address_Mode = struct
  type t =
  | Undefined
  | Clamp_to_edge
  | Repeat
  | Mirror_repeat

external address_mode_undefined : unit -> int = "caml_wgpu_address_mode_undefined"
external address_mode_clamp_to_edge : unit -> int = "caml_wgpu_address_mode_clamp_to_edge"
external address_mode_repeat : unit -> int = "caml_wgpu_address_mode_repeat"
external address_mode_mirror_repeat : unit -> int = "caml_wgpu_address_mode_mirror_repeat"

  let to_int = function
    | Undefined -> address_mode_undefined ()
    | Clamp_to_edge -> address_mode_clamp_to_edge ()
    | Repeat -> address_mode_repeat ()
    | Mirror_repeat -> address_mode_mirror_repeat ()
end

module Backend_Type = struct
  type t =
  | Undefined
  | Null
  | Webgpu
  | D3d11
  | D3d12
  | Metal
  | Vulkan
  | Opengl
  | Opengles

external backend_type_undefined : unit -> int = "caml_wgpu_backend_type_undefined"
external backend_type_null : unit -> int = "caml_wgpu_backend_type_null"
external backend_type_webgpu : unit -> int = "caml_wgpu_backend_type_webgpu"
external backend_type_d3d11 : unit -> int = "caml_wgpu_backend_type_d3d11"
external backend_type_d3d12 : unit -> int = "caml_wgpu_backend_type_d3d12"
external backend_type_metal : unit -> int = "caml_wgpu_backend_type_metal"
external backend_type_vulkan : unit -> int = "caml_wgpu_backend_type_vulkan"
external backend_type_opengl : unit -> int = "caml_wgpu_backend_type_opengl"
external backend_type_opengles : unit -> int = "caml_wgpu_backend_type_opengles"

  let to_int = function
    | Undefined -> backend_type_undefined ()
    | Null -> backend_type_null ()
    | Webgpu -> backend_type_webgpu ()
    | D3d11 -> backend_type_d3d11 ()
    | D3d12 -> backend_type_d3d12 ()
    | Metal -> backend_type_metal ()
    | Vulkan -> backend_type_vulkan ()
    | Opengl -> backend_type_opengl ()
    | Opengles -> backend_type_opengles ()
end

module Blend_Factor = struct
  type t =
  | Undefined
  | Zero
  | One
  | Src
  | One_minus_src
  | Src_alpha
  | One_minus_src_alpha
  | Dst
  | One_minus_dst
  | Dst_alpha
  | One_minus_dst_alpha
  | Src_alpha_saturated
  | Constant
  | One_minus_constant
  | Src1
  | One_minus_src1
  | Src1_alpha
  | One_minus_src1_alpha

external blend_factor_undefined : unit -> int = "caml_wgpu_blend_factor_undefined"
external blend_factor_zero : unit -> int = "caml_wgpu_blend_factor_zero"
external blend_factor_one : unit -> int = "caml_wgpu_blend_factor_one"
external blend_factor_src : unit -> int = "caml_wgpu_blend_factor_src"
external blend_factor_one_minus_src : unit -> int = "caml_wgpu_blend_factor_one_minus_src"
external blend_factor_src_alpha : unit -> int = "caml_wgpu_blend_factor_src_alpha"
external blend_factor_one_minus_src_alpha : unit -> int = "caml_wgpu_blend_factor_one_minus_src_alpha"
external blend_factor_dst : unit -> int = "caml_wgpu_blend_factor_dst"
external blend_factor_one_minus_dst : unit -> int = "caml_wgpu_blend_factor_one_minus_dst"
external blend_factor_dst_alpha : unit -> int = "caml_wgpu_blend_factor_dst_alpha"
external blend_factor_one_minus_dst_alpha : unit -> int = "caml_wgpu_blend_factor_one_minus_dst_alpha"
external blend_factor_src_alpha_saturated : unit -> int = "caml_wgpu_blend_factor_src_alpha_saturated"
external blend_factor_constant : unit -> int = "caml_wgpu_blend_factor_constant"
external blend_factor_one_minus_constant : unit -> int = "caml_wgpu_blend_factor_one_minus_constant"
external blend_factor_src1 : unit -> int = "caml_wgpu_blend_factor_src1"
external blend_factor_one_minus_src1 : unit -> int = "caml_wgpu_blend_factor_one_minus_src1"
external blend_factor_src1_alpha : unit -> int = "caml_wgpu_blend_factor_src1_alpha"
external blend_factor_one_minus_src1_alpha : unit -> int = "caml_wgpu_blend_factor_one_minus_src1_alpha"

  let to_int = function
    | Undefined -> blend_factor_undefined ()
    | Zero -> blend_factor_zero ()
    | One -> blend_factor_one ()
    | Src -> blend_factor_src ()
    | One_minus_src -> blend_factor_one_minus_src ()
    | Src_alpha -> blend_factor_src_alpha ()
    | One_minus_src_alpha -> blend_factor_one_minus_src_alpha ()
    | Dst -> blend_factor_dst ()
    | One_minus_dst -> blend_factor_one_minus_dst ()
    | Dst_alpha -> blend_factor_dst_alpha ()
    | One_minus_dst_alpha -> blend_factor_one_minus_dst_alpha ()
    | Src_alpha_saturated -> blend_factor_src_alpha_saturated ()
    | Constant -> blend_factor_constant ()
    | One_minus_constant -> blend_factor_one_minus_constant ()
    | Src1 -> blend_factor_src1 ()
    | One_minus_src1 -> blend_factor_one_minus_src1 ()
    | Src1_alpha -> blend_factor_src1_alpha ()
    | One_minus_src1_alpha -> blend_factor_one_minus_src1_alpha ()
end

module Blend_Operation = struct
  type t =
  | Undefined
  | Add
  | Subtract
  | Reverse_subtract
  | Min
  | Max

external blend_operation_undefined : unit -> int = "caml_wgpu_blend_operation_undefined"
external blend_operation_add : unit -> int = "caml_wgpu_blend_operation_add"
external blend_operation_subtract : unit -> int = "caml_wgpu_blend_operation_subtract"
external blend_operation_reverse_subtract : unit -> int = "caml_wgpu_blend_operation_reverse_subtract"
external blend_operation_min : unit -> int = "caml_wgpu_blend_operation_min"
external blend_operation_max : unit -> int = "caml_wgpu_blend_operation_max"

  let to_int = function
    | Undefined -> blend_operation_undefined ()
    | Add -> blend_operation_add ()
    | Subtract -> blend_operation_subtract ()
    | Reverse_subtract -> blend_operation_reverse_subtract ()
    | Min -> blend_operation_min ()
    | Max -> blend_operation_max ()
end

module Buffer_Binding_Type = struct
  type t =
  | Binding_not_used
  | Undefined
  | Uniform
  | Storage
  | Read_only_storage

external buffer_binding_type_binding_not_used : unit -> int = "caml_wgpu_buffer_binding_type_binding_not_used"
external buffer_binding_type_undefined : unit -> int = "caml_wgpu_buffer_binding_type_undefined"
external buffer_binding_type_uniform : unit -> int = "caml_wgpu_buffer_binding_type_uniform"
external buffer_binding_type_storage : unit -> int = "caml_wgpu_buffer_binding_type_storage"
external buffer_binding_type_read_only_storage : unit -> int = "caml_wgpu_buffer_binding_type_read_only_storage"

  let to_int = function
    | Binding_not_used -> buffer_binding_type_binding_not_used ()
    | Undefined -> buffer_binding_type_undefined ()
    | Uniform -> buffer_binding_type_uniform ()
    | Storage -> buffer_binding_type_storage ()
    | Read_only_storage -> buffer_binding_type_read_only_storage ()
end

module Buffer_Map_State = struct
  type t =
  | Unmapped
  | Pending
  | Mapped

external buffer_map_state_unmapped : unit -> int = "caml_wgpu_buffer_map_state_unmapped"
external buffer_map_state_pending : unit -> int = "caml_wgpu_buffer_map_state_pending"
external buffer_map_state_mapped : unit -> int = "caml_wgpu_buffer_map_state_mapped"

  let to_int = function
    | Unmapped -> buffer_map_state_unmapped ()
    | Pending -> buffer_map_state_pending ()
    | Mapped -> buffer_map_state_mapped ()
end

module Callback_Mode = struct
  type t =
  | Wait_any_only
  | Allow_process_events
  | Allow_spontaneous

external callback_mode_wait_any_only : unit -> int = "caml_wgpu_callback_mode_wait_any_only"
external callback_mode_allow_process_events : unit -> int = "caml_wgpu_callback_mode_allow_process_events"
external callback_mode_allow_spontaneous : unit -> int = "caml_wgpu_callback_mode_allow_spontaneous"

  let to_int = function
    | Wait_any_only -> callback_mode_wait_any_only ()
    | Allow_process_events -> callback_mode_allow_process_events ()
    | Allow_spontaneous -> callback_mode_allow_spontaneous ()
end

module Compare_Function = struct
  type t =
  | Undefined
  | Never
  | Less
  | Equal
  | Less_equal
  | Greater
  | Not_equal
  | Greater_equal
  | Always

external compare_function_undefined : unit -> int = "caml_wgpu_compare_function_undefined"
external compare_function_never : unit -> int = "caml_wgpu_compare_function_never"
external compare_function_less : unit -> int = "caml_wgpu_compare_function_less"
external compare_function_equal : unit -> int = "caml_wgpu_compare_function_equal"
external compare_function_less_equal : unit -> int = "caml_wgpu_compare_function_less_equal"
external compare_function_greater : unit -> int = "caml_wgpu_compare_function_greater"
external compare_function_not_equal : unit -> int = "caml_wgpu_compare_function_not_equal"
external compare_function_greater_equal : unit -> int = "caml_wgpu_compare_function_greater_equal"
external compare_function_always : unit -> int = "caml_wgpu_compare_function_always"

  let to_int = function
    | Undefined -> compare_function_undefined ()
    | Never -> compare_function_never ()
    | Less -> compare_function_less ()
    | Equal -> compare_function_equal ()
    | Less_equal -> compare_function_less_equal ()
    | Greater -> compare_function_greater ()
    | Not_equal -> compare_function_not_equal ()
    | Greater_equal -> compare_function_greater_equal ()
    | Always -> compare_function_always ()
end

module Compilation_Info_Request_Status = struct
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

external compilation_info_request_status_success : unit -> int = "caml_wgpu_compilation_info_request_status_success"
external compilation_info_request_status_instance_dropped : unit -> int = "caml_wgpu_compilation_info_request_status_instance_dropped"
external compilation_info_request_status_error : unit -> int = "caml_wgpu_compilation_info_request_status_error"
external compilation_info_request_status_unknown : unit -> int = "caml_wgpu_compilation_info_request_status_unknown"

  let to_int = function
    | Success -> compilation_info_request_status_success ()
    | Instance_dropped -> compilation_info_request_status_instance_dropped ()
    | Error -> compilation_info_request_status_error ()
    | Unknown -> compilation_info_request_status_unknown ()
end

module Compilation_Message_Type = struct
  type t =
  | Error
  | Warning
  | Info

external compilation_message_type_error : unit -> int = "caml_wgpu_compilation_message_type_error"
external compilation_message_type_warning : unit -> int = "caml_wgpu_compilation_message_type_warning"
external compilation_message_type_info : unit -> int = "caml_wgpu_compilation_message_type_info"

  let to_int = function
    | Error -> compilation_message_type_error ()
    | Warning -> compilation_message_type_warning ()
    | Info -> compilation_message_type_info ()
end

module Composite_Alpha_Mode = struct
  type t =
  | Auto
  | Opaque
  | Premultiplied
  | Unpremultiplied
  | Inherit

external composite_alpha_mode_auto : unit -> int = "caml_wgpu_composite_alpha_mode_auto"
external composite_alpha_mode_opaque : unit -> int = "caml_wgpu_composite_alpha_mode_opaque"
external composite_alpha_mode_premultiplied : unit -> int = "caml_wgpu_composite_alpha_mode_premultiplied"
external composite_alpha_mode_unpremultiplied : unit -> int = "caml_wgpu_composite_alpha_mode_unpremultiplied"
external composite_alpha_mode_inherit : unit -> int = "caml_wgpu_composite_alpha_mode_inherit"

  let to_int = function
    | Auto -> composite_alpha_mode_auto ()
    | Opaque -> composite_alpha_mode_opaque ()
    | Premultiplied -> composite_alpha_mode_premultiplied ()
    | Unpremultiplied -> composite_alpha_mode_unpremultiplied ()
    | Inherit -> composite_alpha_mode_inherit ()
end

module Create_Pipeline_Async_Status = struct
  type t =
  | Success
  | Instance_dropped
  | Validation_error
  | Internal_error
  | Unknown

external create_pipeline_async_status_success : unit -> int = "caml_wgpu_create_pipeline_async_status_success"
external create_pipeline_async_status_instance_dropped : unit -> int = "caml_wgpu_create_pipeline_async_status_instance_dropped"
external create_pipeline_async_status_validation_error : unit -> int = "caml_wgpu_create_pipeline_async_status_validation_error"
external create_pipeline_async_status_internal_error : unit -> int = "caml_wgpu_create_pipeline_async_status_internal_error"
external create_pipeline_async_status_unknown : unit -> int = "caml_wgpu_create_pipeline_async_status_unknown"

  let to_int = function
    | Success -> create_pipeline_async_status_success ()
    | Instance_dropped -> create_pipeline_async_status_instance_dropped ()
    | Validation_error -> create_pipeline_async_status_validation_error ()
    | Internal_error -> create_pipeline_async_status_internal_error ()
    | Unknown -> create_pipeline_async_status_unknown ()
end

module Cull_Mode = struct
  type t =
  | Undefined
  | None
  | Front
  | Back

external cull_mode_undefined : unit -> int = "caml_wgpu_cull_mode_undefined"
external cull_mode_none : unit -> int = "caml_wgpu_cull_mode_none"
external cull_mode_front : unit -> int = "caml_wgpu_cull_mode_front"
external cull_mode_back : unit -> int = "caml_wgpu_cull_mode_back"

  let to_int = function
    | Undefined -> cull_mode_undefined ()
    | None -> cull_mode_none ()
    | Front -> cull_mode_front ()
    | Back -> cull_mode_back ()
end

module Device_Lost_Reason = struct
  type t =
  | Unknown
  | Destroyed
  | Instance_dropped
  | Failed_creation

external device_lost_reason_unknown : unit -> int = "caml_wgpu_device_lost_reason_unknown"
external device_lost_reason_destroyed : unit -> int = "caml_wgpu_device_lost_reason_destroyed"
external device_lost_reason_instance_dropped : unit -> int = "caml_wgpu_device_lost_reason_instance_dropped"
external device_lost_reason_failed_creation : unit -> int = "caml_wgpu_device_lost_reason_failed_creation"

  let to_int = function
    | Unknown -> device_lost_reason_unknown ()
    | Destroyed -> device_lost_reason_destroyed ()
    | Instance_dropped -> device_lost_reason_instance_dropped ()
    | Failed_creation -> device_lost_reason_failed_creation ()
end

module Error_Filter = struct
  type t =
  | Validation
  | Out_of_memory
  | Internal

external error_filter_validation : unit -> int = "caml_wgpu_error_filter_validation"
external error_filter_out_of_memory : unit -> int = "caml_wgpu_error_filter_out_of_memory"
external error_filter_internal : unit -> int = "caml_wgpu_error_filter_internal"

  let to_int = function
    | Validation -> error_filter_validation ()
    | Out_of_memory -> error_filter_out_of_memory ()
    | Internal -> error_filter_internal ()
end

module Error_Type = struct
  type t =
  | No_error
  | Validation
  | Out_of_memory
  | Internal
  | Unknown

external error_type_no_error : unit -> int = "caml_wgpu_error_type_no_error"
external error_type_validation : unit -> int = "caml_wgpu_error_type_validation"
external error_type_out_of_memory : unit -> int = "caml_wgpu_error_type_out_of_memory"
external error_type_internal : unit -> int = "caml_wgpu_error_type_internal"
external error_type_unknown : unit -> int = "caml_wgpu_error_type_unknown"

  let to_int = function
    | No_error -> error_type_no_error ()
    | Validation -> error_type_validation ()
    | Out_of_memory -> error_type_out_of_memory ()
    | Internal -> error_type_internal ()
    | Unknown -> error_type_unknown ()
end

module Feature_Level = struct
  type t =
  | Compatibility
  | Core

external feature_level_compatibility : unit -> int = "caml_wgpu_feature_level_compatibility"
external feature_level_core : unit -> int = "caml_wgpu_feature_level_core"

  let to_int = function
    | Compatibility -> feature_level_compatibility ()
    | Core -> feature_level_core ()
end

module Feature_Name = struct
  type t =
  | Undefined
  | Depth_clip_control
  | Depth32_float_stencil8
  | Timestamp_query
  | Texture_compression_bc
  | Texture_compression_bc_sliced_3d
  | Texture_compression_etc2
  | Texture_compression_astc
  | Texture_compression_astc_sliced_3d
  | Indirect_first_instance
  | Shader_f16
  | Rg11b10_ufloat_renderable
  | Bgra8_unorm_storage
  | Float32_filterable
  | Float32_blendable
  | Clip_distances
  | Dual_source_blending

external feature_name_undefined : unit -> int = "caml_wgpu_feature_name_undefined"
external feature_name_depth_clip_control : unit -> int = "caml_wgpu_feature_name_depth_clip_control"
external feature_name_depth32_float_stencil8 : unit -> int = "caml_wgpu_feature_name_depth32_float_stencil8"
external feature_name_timestamp_query : unit -> int = "caml_wgpu_feature_name_timestamp_query"
external feature_name_texture_compression_bc : unit -> int = "caml_wgpu_feature_name_texture_compression_bc"
external feature_name_texture_compression_bc_sliced_3d : unit -> int = "caml_wgpu_feature_name_texture_compression_bc_sliced_3d"
external feature_name_texture_compression_etc2 : unit -> int = "caml_wgpu_feature_name_texture_compression_etc2"
external feature_name_texture_compression_astc : unit -> int = "caml_wgpu_feature_name_texture_compression_astc"
external feature_name_texture_compression_astc_sliced_3d : unit -> int = "caml_wgpu_feature_name_texture_compression_astc_sliced_3d"
external feature_name_indirect_first_instance : unit -> int = "caml_wgpu_feature_name_indirect_first_instance"
external feature_name_shader_f16 : unit -> int = "caml_wgpu_feature_name_shader_f16"
external feature_name_rg11b10_ufloat_renderable : unit -> int = "caml_wgpu_feature_name_rg11b10_ufloat_renderable"
external feature_name_bgra8_unorm_storage : unit -> int = "caml_wgpu_feature_name_bgra8_unorm_storage"
external feature_name_float32_filterable : unit -> int = "caml_wgpu_feature_name_float32_filterable"
external feature_name_float32_blendable : unit -> int = "caml_wgpu_feature_name_float32_blendable"
external feature_name_clip_distances : unit -> int = "caml_wgpu_feature_name_clip_distances"
external feature_name_dual_source_blending : unit -> int = "caml_wgpu_feature_name_dual_source_blending"

  let to_int = function
    | Undefined -> feature_name_undefined ()
    | Depth_clip_control -> feature_name_depth_clip_control ()
    | Depth32_float_stencil8 -> feature_name_depth32_float_stencil8 ()
    | Timestamp_query -> feature_name_timestamp_query ()
    | Texture_compression_bc -> feature_name_texture_compression_bc ()
    | Texture_compression_bc_sliced_3d -> feature_name_texture_compression_bc_sliced_3d ()
    | Texture_compression_etc2 -> feature_name_texture_compression_etc2 ()
    | Texture_compression_astc -> feature_name_texture_compression_astc ()
    | Texture_compression_astc_sliced_3d -> feature_name_texture_compression_astc_sliced_3d ()
    | Indirect_first_instance -> feature_name_indirect_first_instance ()
    | Shader_f16 -> feature_name_shader_f16 ()
    | Rg11b10_ufloat_renderable -> feature_name_rg11b10_ufloat_renderable ()
    | Bgra8_unorm_storage -> feature_name_bgra8_unorm_storage ()
    | Float32_filterable -> feature_name_float32_filterable ()
    | Float32_blendable -> feature_name_float32_blendable ()
    | Clip_distances -> feature_name_clip_distances ()
    | Dual_source_blending -> feature_name_dual_source_blending ()
end

module Filter_Mode = struct
  type t =
  | Undefined
  | Nearest
  | Linear

external filter_mode_undefined : unit -> int = "caml_wgpu_filter_mode_undefined"
external filter_mode_nearest : unit -> int = "caml_wgpu_filter_mode_nearest"
external filter_mode_linear : unit -> int = "caml_wgpu_filter_mode_linear"

  let to_int = function
    | Undefined -> filter_mode_undefined ()
    | Nearest -> filter_mode_nearest ()
    | Linear -> filter_mode_linear ()
end

module Front_Face = struct
  type t =
  | Undefined
  | Ccw
  | Cw

external front_face_undefined : unit -> int = "caml_wgpu_front_face_undefined"
external front_face_ccw : unit -> int = "caml_wgpu_front_face_ccw"
external front_face_cw : unit -> int = "caml_wgpu_front_face_cw"

  let to_int = function
    | Undefined -> front_face_undefined ()
    | Ccw -> front_face_ccw ()
    | Cw -> front_face_cw ()
end

module Index_Format = struct
  type t =
  | Undefined
  | Uint16
  | Uint32

external index_format_undefined : unit -> int = "caml_wgpu_index_format_undefined"
external index_format_uint16 : unit -> int = "caml_wgpu_index_format_uint16"
external index_format_uint32 : unit -> int = "caml_wgpu_index_format_uint32"

  let to_int = function
    | Undefined -> index_format_undefined ()
    | Uint16 -> index_format_uint16 ()
    | Uint32 -> index_format_uint32 ()
end

module Load_Op = struct
  type t =
  | Undefined
  | Load
  | Clear

external load_op_undefined : unit -> int = "caml_wgpu_load_op_undefined"
external load_op_load : unit -> int = "caml_wgpu_load_op_load"
external load_op_clear : unit -> int = "caml_wgpu_load_op_clear"

  let to_int = function
    | Undefined -> load_op_undefined ()
    | Load -> load_op_load ()
    | Clear -> load_op_clear ()
end

module Map_Async_Status = struct
  type t =
  | Success
  | Instance_dropped
  | Error
  | Aborted
  | Unknown

external map_async_status_success : unit -> int = "caml_wgpu_map_async_status_success"
external map_async_status_instance_dropped : unit -> int = "caml_wgpu_map_async_status_instance_dropped"
external map_async_status_error : unit -> int = "caml_wgpu_map_async_status_error"
external map_async_status_aborted : unit -> int = "caml_wgpu_map_async_status_aborted"
external map_async_status_unknown : unit -> int = "caml_wgpu_map_async_status_unknown"

  let to_int = function
    | Success -> map_async_status_success ()
    | Instance_dropped -> map_async_status_instance_dropped ()
    | Error -> map_async_status_error ()
    | Aborted -> map_async_status_aborted ()
    | Unknown -> map_async_status_unknown ()
end

module Mipmap_Filter_Mode = struct
  type t =
  | Undefined
  | Nearest
  | Linear

external mipmap_filter_mode_undefined : unit -> int = "caml_wgpu_mipmap_filter_mode_undefined"
external mipmap_filter_mode_nearest : unit -> int = "caml_wgpu_mipmap_filter_mode_nearest"
external mipmap_filter_mode_linear : unit -> int = "caml_wgpu_mipmap_filter_mode_linear"

  let to_int = function
    | Undefined -> mipmap_filter_mode_undefined ()
    | Nearest -> mipmap_filter_mode_nearest ()
    | Linear -> mipmap_filter_mode_linear ()
end

module Optional_Bool = struct
  type t =
  | False
  | True
  | Undefined

external optional_bool_false : unit -> int = "caml_wgpu_optional_bool_false"
external optional_bool_true : unit -> int = "caml_wgpu_optional_bool_true"
external optional_bool_undefined : unit -> int = "caml_wgpu_optional_bool_undefined"

  let to_int = function
    | False -> optional_bool_false ()
    | True -> optional_bool_true ()
    | Undefined -> optional_bool_undefined ()
end

module Pop_Error_Scope_Status = struct
  type t =
  | Success
  | Instance_dropped
  | Empty_stack

external pop_error_scope_status_success : unit -> int = "caml_wgpu_pop_error_scope_status_success"
external pop_error_scope_status_instance_dropped : unit -> int = "caml_wgpu_pop_error_scope_status_instance_dropped"
external pop_error_scope_status_empty_stack : unit -> int = "caml_wgpu_pop_error_scope_status_empty_stack"

  let to_int = function
    | Success -> pop_error_scope_status_success ()
    | Instance_dropped -> pop_error_scope_status_instance_dropped ()
    | Empty_stack -> pop_error_scope_status_empty_stack ()
end

module Power_Preference = struct
  type t =
  | Undefined
  | Low_power
  | High_performance

external power_preference_undefined : unit -> int = "caml_wgpu_power_preference_undefined"
external power_preference_low_power : unit -> int = "caml_wgpu_power_preference_low_power"
external power_preference_high_performance : unit -> int = "caml_wgpu_power_preference_high_performance"

  let to_int = function
    | Undefined -> power_preference_undefined ()
    | Low_power -> power_preference_low_power ()
    | High_performance -> power_preference_high_performance ()
end

module Present_Mode = struct
  type t =
  | Undefined
  | Fifo
  | Fifo_relaxed
  | Immediate
  | Mailbox

external present_mode_undefined : unit -> int = "caml_wgpu_present_mode_undefined"
external present_mode_fifo : unit -> int = "caml_wgpu_present_mode_fifo"
external present_mode_fifo_relaxed : unit -> int = "caml_wgpu_present_mode_fifo_relaxed"
external present_mode_immediate : unit -> int = "caml_wgpu_present_mode_immediate"
external present_mode_mailbox : unit -> int = "caml_wgpu_present_mode_mailbox"

  let to_int = function
    | Undefined -> present_mode_undefined ()
    | Fifo -> present_mode_fifo ()
    | Fifo_relaxed -> present_mode_fifo_relaxed ()
    | Immediate -> present_mode_immediate ()
    | Mailbox -> present_mode_mailbox ()
end

module Primitive_Topology = struct
  type t =
  | Undefined
  | Point_list
  | Line_list
  | Line_strip
  | Triangle_list
  | Triangle_strip

external primitive_topology_undefined : unit -> int = "caml_wgpu_primitive_topology_undefined"
external primitive_topology_point_list : unit -> int = "caml_wgpu_primitive_topology_point_list"
external primitive_topology_line_list : unit -> int = "caml_wgpu_primitive_topology_line_list"
external primitive_topology_line_strip : unit -> int = "caml_wgpu_primitive_topology_line_strip"
external primitive_topology_triangle_list : unit -> int = "caml_wgpu_primitive_topology_triangle_list"
external primitive_topology_triangle_strip : unit -> int = "caml_wgpu_primitive_topology_triangle_strip"

  let to_int = function
    | Undefined -> primitive_topology_undefined ()
    | Point_list -> primitive_topology_point_list ()
    | Line_list -> primitive_topology_line_list ()
    | Line_strip -> primitive_topology_line_strip ()
    | Triangle_list -> primitive_topology_triangle_list ()
    | Triangle_strip -> primitive_topology_triangle_strip ()
end

module Query_Type = struct
  type t =
  | Occlusion
  | Timestamp

external query_type_occlusion : unit -> int = "caml_wgpu_query_type_occlusion"
external query_type_timestamp : unit -> int = "caml_wgpu_query_type_timestamp"

  let to_int = function
    | Occlusion -> query_type_occlusion ()
    | Timestamp -> query_type_timestamp ()
end

module Queue_Work_Done_Status = struct
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

external queue_work_done_status_success : unit -> int = "caml_wgpu_queue_work_done_status_success"
external queue_work_done_status_instance_dropped : unit -> int = "caml_wgpu_queue_work_done_status_instance_dropped"
external queue_work_done_status_error : unit -> int = "caml_wgpu_queue_work_done_status_error"
external queue_work_done_status_unknown : unit -> int = "caml_wgpu_queue_work_done_status_unknown"

  let to_int = function
    | Success -> queue_work_done_status_success ()
    | Instance_dropped -> queue_work_done_status_instance_dropped ()
    | Error -> queue_work_done_status_error ()
    | Unknown -> queue_work_done_status_unknown ()
end

module Request_Adapter_Status = struct
  type t =
  | Success
  | Instance_dropped
  | Unavailable
  | Error
  | Unknown

external request_adapter_status_success : unit -> int = "caml_wgpu_request_adapter_status_success"
external request_adapter_status_instance_dropped : unit -> int = "caml_wgpu_request_adapter_status_instance_dropped"
external request_adapter_status_unavailable : unit -> int = "caml_wgpu_request_adapter_status_unavailable"
external request_adapter_status_error : unit -> int = "caml_wgpu_request_adapter_status_error"
external request_adapter_status_unknown : unit -> int = "caml_wgpu_request_adapter_status_unknown"

  let to_int = function
    | Success -> request_adapter_status_success ()
    | Instance_dropped -> request_adapter_status_instance_dropped ()
    | Unavailable -> request_adapter_status_unavailable ()
    | Error -> request_adapter_status_error ()
    | Unknown -> request_adapter_status_unknown ()
end

module Request_Device_Status = struct
  type t =
  | Success
  | Instance_dropped
  | Error
  | Unknown

external request_device_status_success : unit -> int = "caml_wgpu_request_device_status_success"
external request_device_status_instance_dropped : unit -> int = "caml_wgpu_request_device_status_instance_dropped"
external request_device_status_error : unit -> int = "caml_wgpu_request_device_status_error"
external request_device_status_unknown : unit -> int = "caml_wgpu_request_device_status_unknown"

  let to_int = function
    | Success -> request_device_status_success ()
    | Instance_dropped -> request_device_status_instance_dropped ()
    | Error -> request_device_status_error ()
    | Unknown -> request_device_status_unknown ()
end

module S_Type = struct
  type t =
  | Shader_source_spirv
  | Shader_source_wgsl
  | Render_pass_max_draw_count
  | Surface_source_metal_layer
  | Surface_source_windows_hwnd
  | Surface_source_xlib_window
  | Surface_source_wayland_surface
  | Surface_source_android_native_window
  | Surface_source_xcb_window

external s_type_shader_source_spirv : unit -> int = "caml_wgpu_s_type_shader_source_spirv"
external s_type_shader_source_wgsl : unit -> int = "caml_wgpu_s_type_shader_source_wgsl"
external s_type_render_pass_max_draw_count : unit -> int = "caml_wgpu_s_type_render_pass_max_draw_count"
external s_type_surface_source_metal_layer : unit -> int = "caml_wgpu_s_type_surface_source_metal_layer"
external s_type_surface_source_windows_hwnd : unit -> int = "caml_wgpu_s_type_surface_source_windows_hwnd"
external s_type_surface_source_xlib_window : unit -> int = "caml_wgpu_s_type_surface_source_xlib_window"
external s_type_surface_source_wayland_surface : unit -> int = "caml_wgpu_s_type_surface_source_wayland_surface"
external s_type_surface_source_android_native_window : unit -> int = "caml_wgpu_s_type_surface_source_android_native_window"
external s_type_surface_source_xcb_window : unit -> int = "caml_wgpu_s_type_surface_source_xcb_window"

  let to_int = function
    | Shader_source_spirv -> s_type_shader_source_spirv ()
    | Shader_source_wgsl -> s_type_shader_source_wgsl ()
    | Render_pass_max_draw_count -> s_type_render_pass_max_draw_count ()
    | Surface_source_metal_layer -> s_type_surface_source_metal_layer ()
    | Surface_source_windows_hwnd -> s_type_surface_source_windows_hwnd ()
    | Surface_source_xlib_window -> s_type_surface_source_xlib_window ()
    | Surface_source_wayland_surface -> s_type_surface_source_wayland_surface ()
    | Surface_source_android_native_window -> s_type_surface_source_android_native_window ()
    | Surface_source_xcb_window -> s_type_surface_source_xcb_window ()
end

module Sampler_Binding_Type = struct
  type t =
  | Binding_not_used
  | Undefined
  | Filtering
  | Non_filtering
  | Comparison

external sampler_binding_type_binding_not_used : unit -> int = "caml_wgpu_sampler_binding_type_binding_not_used"
external sampler_binding_type_undefined : unit -> int = "caml_wgpu_sampler_binding_type_undefined"
external sampler_binding_type_filtering : unit -> int = "caml_wgpu_sampler_binding_type_filtering"
external sampler_binding_type_non_filtering : unit -> int = "caml_wgpu_sampler_binding_type_non_filtering"
external sampler_binding_type_comparison : unit -> int = "caml_wgpu_sampler_binding_type_comparison"

  let to_int = function
    | Binding_not_used -> sampler_binding_type_binding_not_used ()
    | Undefined -> sampler_binding_type_undefined ()
    | Filtering -> sampler_binding_type_filtering ()
    | Non_filtering -> sampler_binding_type_non_filtering ()
    | Comparison -> sampler_binding_type_comparison ()
end

module Status = struct
  type t =
  | Success
  | Error

external status_success : unit -> int = "caml_wgpu_status_success"
external status_error : unit -> int = "caml_wgpu_status_error"

  let to_int = function
    | Success -> status_success ()
    | Error -> status_error ()
end

module Stencil_Operation = struct
  type t =
  | Undefined
  | Keep
  | Zero
  | Replace
  | Invert
  | Increment_clamp
  | Decrement_clamp
  | Increment_wrap
  | Decrement_wrap

external stencil_operation_undefined : unit -> int = "caml_wgpu_stencil_operation_undefined"
external stencil_operation_keep : unit -> int = "caml_wgpu_stencil_operation_keep"
external stencil_operation_zero : unit -> int = "caml_wgpu_stencil_operation_zero"
external stencil_operation_replace : unit -> int = "caml_wgpu_stencil_operation_replace"
external stencil_operation_invert : unit -> int = "caml_wgpu_stencil_operation_invert"
external stencil_operation_increment_clamp : unit -> int = "caml_wgpu_stencil_operation_increment_clamp"
external stencil_operation_decrement_clamp : unit -> int = "caml_wgpu_stencil_operation_decrement_clamp"
external stencil_operation_increment_wrap : unit -> int = "caml_wgpu_stencil_operation_increment_wrap"
external stencil_operation_decrement_wrap : unit -> int = "caml_wgpu_stencil_operation_decrement_wrap"

  let to_int = function
    | Undefined -> stencil_operation_undefined ()
    | Keep -> stencil_operation_keep ()
    | Zero -> stencil_operation_zero ()
    | Replace -> stencil_operation_replace ()
    | Invert -> stencil_operation_invert ()
    | Increment_clamp -> stencil_operation_increment_clamp ()
    | Decrement_clamp -> stencil_operation_decrement_clamp ()
    | Increment_wrap -> stencil_operation_increment_wrap ()
    | Decrement_wrap -> stencil_operation_decrement_wrap ()
end

module Storage_Texture_Access = struct
  type t =
  | Binding_not_used
  | Undefined
  | Write_only
  | Read_only
  | Read_write

external storage_texture_access_binding_not_used : unit -> int = "caml_wgpu_storage_texture_access_binding_not_used"
external storage_texture_access_undefined : unit -> int = "caml_wgpu_storage_texture_access_undefined"
external storage_texture_access_write_only : unit -> int = "caml_wgpu_storage_texture_access_write_only"
external storage_texture_access_read_only : unit -> int = "caml_wgpu_storage_texture_access_read_only"
external storage_texture_access_read_write : unit -> int = "caml_wgpu_storage_texture_access_read_write"

  let to_int = function
    | Binding_not_used -> storage_texture_access_binding_not_used ()
    | Undefined -> storage_texture_access_undefined ()
    | Write_only -> storage_texture_access_write_only ()
    | Read_only -> storage_texture_access_read_only ()
    | Read_write -> storage_texture_access_read_write ()
end

module Store_Op = struct
  type t =
  | Undefined
  | Store
  | Discard

external store_op_undefined : unit -> int = "caml_wgpu_store_op_undefined"
external store_op_store : unit -> int = "caml_wgpu_store_op_store"
external store_op_discard : unit -> int = "caml_wgpu_store_op_discard"

  let to_int = function
    | Undefined -> store_op_undefined ()
    | Store -> store_op_store ()
    | Discard -> store_op_discard ()
end

module Surface_Get_Current_Texture_Status = struct
  type t =
  | Success_optimal
  | Success_suboptimal
  | Timeout
  | Outdated
  | Lost
  | Out_of_memory
  | Device_lost
  | Error

external surface_get_current_texture_status_success_optimal : unit -> int = "caml_wgpu_surface_get_current_texture_status_success_optimal"
external surface_get_current_texture_status_success_suboptimal : unit -> int = "caml_wgpu_surface_get_current_texture_status_success_suboptimal"
external surface_get_current_texture_status_timeout : unit -> int = "caml_wgpu_surface_get_current_texture_status_timeout"
external surface_get_current_texture_status_outdated : unit -> int = "caml_wgpu_surface_get_current_texture_status_outdated"
external surface_get_current_texture_status_lost : unit -> int = "caml_wgpu_surface_get_current_texture_status_lost"
external surface_get_current_texture_status_out_of_memory : unit -> int = "caml_wgpu_surface_get_current_texture_status_out_of_memory"
external surface_get_current_texture_status_device_lost : unit -> int = "caml_wgpu_surface_get_current_texture_status_device_lost"
external surface_get_current_texture_status_error : unit -> int = "caml_wgpu_surface_get_current_texture_status_error"

  let to_int = function
    | Success_optimal -> surface_get_current_texture_status_success_optimal ()
    | Success_suboptimal -> surface_get_current_texture_status_success_suboptimal ()
    | Timeout -> surface_get_current_texture_status_timeout ()
    | Outdated -> surface_get_current_texture_status_outdated ()
    | Lost -> surface_get_current_texture_status_lost ()
    | Out_of_memory -> surface_get_current_texture_status_out_of_memory ()
    | Device_lost -> surface_get_current_texture_status_device_lost ()
    | Error -> surface_get_current_texture_status_error ()
end

module Texture_Aspect = struct
  type t =
  | Undefined
  | All
  | Stencil_only
  | Depth_only

external texture_aspect_undefined : unit -> int = "caml_wgpu_texture_aspect_undefined"
external texture_aspect_all : unit -> int = "caml_wgpu_texture_aspect_all"
external texture_aspect_stencil_only : unit -> int = "caml_wgpu_texture_aspect_stencil_only"
external texture_aspect_depth_only : unit -> int = "caml_wgpu_texture_aspect_depth_only"

  let to_int = function
    | Undefined -> texture_aspect_undefined ()
    | All -> texture_aspect_all ()
    | Stencil_only -> texture_aspect_stencil_only ()
    | Depth_only -> texture_aspect_depth_only ()
end

module Texture_Dimension = struct
  type t =
  | Undefined
  | N1d
  | N2d
  | N3d

external texture_dimension_undefined : unit -> int = "caml_wgpu_texture_dimension_undefined"
external texture_dimension_1d : unit -> int = "caml_wgpu_texture_dimension_1d"
external texture_dimension_2d : unit -> int = "caml_wgpu_texture_dimension_2d"
external texture_dimension_3d : unit -> int = "caml_wgpu_texture_dimension_3d"

  let to_int = function
    | Undefined -> texture_dimension_undefined ()
    | N1d -> texture_dimension_1d ()
    | N2d -> texture_dimension_2d ()
    | N3d -> texture_dimension_3d ()
end

module Texture_Format = struct
  type t =
  | Undefined
  | R8_unorm
  | R8_snorm
  | R8_uint
  | R8_sint
  | R16_uint
  | R16_sint
  | R16_float
  | Rg8_unorm
  | Rg8_snorm
  | Rg8_uint
  | Rg8_sint
  | R32_float
  | R32_uint
  | R32_sint
  | Rg16_uint
  | Rg16_sint
  | Rg16_float
  | Rgba8_unorm
  | Rgba8_unorm_srgb
  | Rgba8_snorm
  | Rgba8_uint
  | Rgba8_sint
  | Bgra8_unorm
  | Bgra8_unorm_srgb
  | Rgb10_a2_uint
  | Rgb10_a2_unorm
  | Rg11_b10_ufloat
  | Rgb9_e5_ufloat
  | Rg32_float
  | Rg32_uint
  | Rg32_sint
  | Rgba16_uint
  | Rgba16_sint
  | Rgba16_float
  | Rgba32_float
  | Rgba32_uint
  | Rgba32_sint
  | Stencil8
  | Depth16_unorm
  | Depth24_plus
  | Depth24_plus_stencil8
  | Depth32_float
  | Depth32_float_stencil8
  | Bc1_rgba_unorm
  | Bc1_rgba_unorm_srgb
  | Bc2_rgba_unorm
  | Bc2_rgba_unorm_srgb
  | Bc3_rgba_unorm
  | Bc3_rgba_unorm_srgb
  | Bc4_r_unorm
  | Bc4_r_snorm
  | Bc5_rg_unorm
  | Bc5_rg_snorm
  | Bc6h_rgb_ufloat
  | Bc6h_rgb_float
  | Bc7_rgba_unorm
  | Bc7_rgba_unorm_srgb
  | Etc2_rgb8_unorm
  | Etc2_rgb8_unorm_srgb
  | Etc2_rgb8a1_unorm
  | Etc2_rgb8a1_unorm_srgb
  | Etc2_rgba8_unorm
  | Etc2_rgba8_unorm_srgb
  | Eac_r11_unorm
  | Eac_r11_snorm
  | Eac_rg11_unorm
  | Eac_rg11_snorm
  | Astc_4x4_unorm
  | Astc_4x4_unorm_srgb
  | Astc_5x4_unorm
  | Astc_5x4_unorm_srgb
  | Astc_5x5_unorm
  | Astc_5x5_unorm_srgb
  | Astc_6x5_unorm
  | Astc_6x5_unorm_srgb
  | Astc_6x6_unorm
  | Astc_6x6_unorm_srgb
  | Astc_8x5_unorm
  | Astc_8x5_unorm_srgb
  | Astc_8x6_unorm
  | Astc_8x6_unorm_srgb
  | Astc_8x8_unorm
  | Astc_8x8_unorm_srgb
  | Astc_10x5_unorm
  | Astc_10x5_unorm_srgb
  | Astc_10x6_unorm
  | Astc_10x6_unorm_srgb
  | Astc_10x8_unorm
  | Astc_10x8_unorm_srgb
  | Astc_10x10_unorm
  | Astc_10x10_unorm_srgb
  | Astc_12x10_unorm
  | Astc_12x10_unorm_srgb
  | Astc_12x12_unorm
  | Astc_12x12_unorm_srgb

external texture_format_undefined : unit -> int = "caml_wgpu_texture_format_undefined"
external texture_format_r8_unorm : unit -> int = "caml_wgpu_texture_format_r8_unorm"
external texture_format_r8_snorm : unit -> int = "caml_wgpu_texture_format_r8_snorm"
external texture_format_r8_uint : unit -> int = "caml_wgpu_texture_format_r8_uint"
external texture_format_r8_sint : unit -> int = "caml_wgpu_texture_format_r8_sint"
external texture_format_r16_uint : unit -> int = "caml_wgpu_texture_format_r16_uint"
external texture_format_r16_sint : unit -> int = "caml_wgpu_texture_format_r16_sint"
external texture_format_r16_float : unit -> int = "caml_wgpu_texture_format_r16_float"
external texture_format_rg8_unorm : unit -> int = "caml_wgpu_texture_format_rg8_unorm"
external texture_format_rg8_snorm : unit -> int = "caml_wgpu_texture_format_rg8_snorm"
external texture_format_rg8_uint : unit -> int = "caml_wgpu_texture_format_rg8_uint"
external texture_format_rg8_sint : unit -> int = "caml_wgpu_texture_format_rg8_sint"
external texture_format_r32_float : unit -> int = "caml_wgpu_texture_format_r32_float"
external texture_format_r32_uint : unit -> int = "caml_wgpu_texture_format_r32_uint"
external texture_format_r32_sint : unit -> int = "caml_wgpu_texture_format_r32_sint"
external texture_format_rg16_uint : unit -> int = "caml_wgpu_texture_format_rg16_uint"
external texture_format_rg16_sint : unit -> int = "caml_wgpu_texture_format_rg16_sint"
external texture_format_rg16_float : unit -> int = "caml_wgpu_texture_format_rg16_float"
external texture_format_rgba8_unorm : unit -> int = "caml_wgpu_texture_format_rgba8_unorm"
external texture_format_rgba8_unorm_srgb : unit -> int = "caml_wgpu_texture_format_rgba8_unorm_srgb"
external texture_format_rgba8_snorm : unit -> int = "caml_wgpu_texture_format_rgba8_snorm"
external texture_format_rgba8_uint : unit -> int = "caml_wgpu_texture_format_rgba8_uint"
external texture_format_rgba8_sint : unit -> int = "caml_wgpu_texture_format_rgba8_sint"
external texture_format_bgra8_unorm : unit -> int = "caml_wgpu_texture_format_bgra8_unorm"
external texture_format_bgra8_unorm_srgb : unit -> int = "caml_wgpu_texture_format_bgra8_unorm_srgb"
external texture_format_rgb10_a2_uint : unit -> int = "caml_wgpu_texture_format_rgb10_a2_uint"
external texture_format_rgb10_a2_unorm : unit -> int = "caml_wgpu_texture_format_rgb10_a2_unorm"
external texture_format_rg11_b10_ufloat : unit -> int = "caml_wgpu_texture_format_rg11_b10_ufloat"
external texture_format_rgb9_e5_ufloat : unit -> int = "caml_wgpu_texture_format_rgb9_e5_ufloat"
external texture_format_rg32_float : unit -> int = "caml_wgpu_texture_format_rg32_float"
external texture_format_rg32_uint : unit -> int = "caml_wgpu_texture_format_rg32_uint"
external texture_format_rg32_sint : unit -> int = "caml_wgpu_texture_format_rg32_sint"
external texture_format_rgba16_uint : unit -> int = "caml_wgpu_texture_format_rgba16_uint"
external texture_format_rgba16_sint : unit -> int = "caml_wgpu_texture_format_rgba16_sint"
external texture_format_rgba16_float : unit -> int = "caml_wgpu_texture_format_rgba16_float"
external texture_format_rgba32_float : unit -> int = "caml_wgpu_texture_format_rgba32_float"
external texture_format_rgba32_uint : unit -> int = "caml_wgpu_texture_format_rgba32_uint"
external texture_format_rgba32_sint : unit -> int = "caml_wgpu_texture_format_rgba32_sint"
external texture_format_stencil8 : unit -> int = "caml_wgpu_texture_format_stencil8"
external texture_format_depth16_unorm : unit -> int = "caml_wgpu_texture_format_depth16_unorm"
external texture_format_depth24_plus : unit -> int = "caml_wgpu_texture_format_depth24_plus"
external texture_format_depth24_plus_stencil8 : unit -> int = "caml_wgpu_texture_format_depth24_plus_stencil8"
external texture_format_depth32_float : unit -> int = "caml_wgpu_texture_format_depth32_float"
external texture_format_depth32_float_stencil8 : unit -> int = "caml_wgpu_texture_format_depth32_float_stencil8"
external texture_format_bc1_rgba_unorm : unit -> int = "caml_wgpu_texture_format_bc1_rgba_unorm"
external texture_format_bc1_rgba_unorm_srgb : unit -> int = "caml_wgpu_texture_format_bc1_rgba_unorm_srgb"
external texture_format_bc2_rgba_unorm : unit -> int = "caml_wgpu_texture_format_bc2_rgba_unorm"
external texture_format_bc2_rgba_unorm_srgb : unit -> int = "caml_wgpu_texture_format_bc2_rgba_unorm_srgb"
external texture_format_bc3_rgba_unorm : unit -> int = "caml_wgpu_texture_format_bc3_rgba_unorm"
external texture_format_bc3_rgba_unorm_srgb : unit -> int = "caml_wgpu_texture_format_bc3_rgba_unorm_srgb"
external texture_format_bc4_r_unorm : unit -> int = "caml_wgpu_texture_format_bc4_r_unorm"
external texture_format_bc4_r_snorm : unit -> int = "caml_wgpu_texture_format_bc4_r_snorm"
external texture_format_bc5_rg_unorm : unit -> int = "caml_wgpu_texture_format_bc5_rg_unorm"
external texture_format_bc5_rg_snorm : unit -> int = "caml_wgpu_texture_format_bc5_rg_snorm"
external texture_format_bc6h_rgb_ufloat : unit -> int = "caml_wgpu_texture_format_bc6h_rgb_ufloat"
external texture_format_bc6h_rgb_float : unit -> int = "caml_wgpu_texture_format_bc6h_rgb_float"
external texture_format_bc7_rgba_unorm : unit -> int = "caml_wgpu_texture_format_bc7_rgba_unorm"
external texture_format_bc7_rgba_unorm_srgb : unit -> int = "caml_wgpu_texture_format_bc7_rgba_unorm_srgb"
external texture_format_etc2_rgb8_unorm : unit -> int = "caml_wgpu_texture_format_etc2_rgb8_unorm"
external texture_format_etc2_rgb8_unorm_srgb : unit -> int = "caml_wgpu_texture_format_etc2_rgb8_unorm_srgb"
external texture_format_etc2_rgb8a1_unorm : unit -> int = "caml_wgpu_texture_format_etc2_rgb8a1_unorm"
external texture_format_etc2_rgb8a1_unorm_srgb : unit -> int = "caml_wgpu_texture_format_etc2_rgb8a1_unorm_srgb"
external texture_format_etc2_rgba8_unorm : unit -> int = "caml_wgpu_texture_format_etc2_rgba8_unorm"
external texture_format_etc2_rgba8_unorm_srgb : unit -> int = "caml_wgpu_texture_format_etc2_rgba8_unorm_srgb"
external texture_format_eac_r11_unorm : unit -> int = "caml_wgpu_texture_format_eac_r11_unorm"
external texture_format_eac_r11_snorm : unit -> int = "caml_wgpu_texture_format_eac_r11_snorm"
external texture_format_eac_rg11_unorm : unit -> int = "caml_wgpu_texture_format_eac_rg11_unorm"
external texture_format_eac_rg11_snorm : unit -> int = "caml_wgpu_texture_format_eac_rg11_snorm"
external texture_format_astc_4x4_unorm : unit -> int = "caml_wgpu_texture_format_astc_4x4_unorm"
external texture_format_astc_4x4_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_4x4_unorm_srgb"
external texture_format_astc_5x4_unorm : unit -> int = "caml_wgpu_texture_format_astc_5x4_unorm"
external texture_format_astc_5x4_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_5x4_unorm_srgb"
external texture_format_astc_5x5_unorm : unit -> int = "caml_wgpu_texture_format_astc_5x5_unorm"
external texture_format_astc_5x5_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_5x5_unorm_srgb"
external texture_format_astc_6x5_unorm : unit -> int = "caml_wgpu_texture_format_astc_6x5_unorm"
external texture_format_astc_6x5_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_6x5_unorm_srgb"
external texture_format_astc_6x6_unorm : unit -> int = "caml_wgpu_texture_format_astc_6x6_unorm"
external texture_format_astc_6x6_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_6x6_unorm_srgb"
external texture_format_astc_8x5_unorm : unit -> int = "caml_wgpu_texture_format_astc_8x5_unorm"
external texture_format_astc_8x5_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_8x5_unorm_srgb"
external texture_format_astc_8x6_unorm : unit -> int = "caml_wgpu_texture_format_astc_8x6_unorm"
external texture_format_astc_8x6_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_8x6_unorm_srgb"
external texture_format_astc_8x8_unorm : unit -> int = "caml_wgpu_texture_format_astc_8x8_unorm"
external texture_format_astc_8x8_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_8x8_unorm_srgb"
external texture_format_astc_10x5_unorm : unit -> int = "caml_wgpu_texture_format_astc_10x5_unorm"
external texture_format_astc_10x5_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_10x5_unorm_srgb"
external texture_format_astc_10x6_unorm : unit -> int = "caml_wgpu_texture_format_astc_10x6_unorm"
external texture_format_astc_10x6_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_10x6_unorm_srgb"
external texture_format_astc_10x8_unorm : unit -> int = "caml_wgpu_texture_format_astc_10x8_unorm"
external texture_format_astc_10x8_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_10x8_unorm_srgb"
external texture_format_astc_10x10_unorm : unit -> int = "caml_wgpu_texture_format_astc_10x10_unorm"
external texture_format_astc_10x10_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_10x10_unorm_srgb"
external texture_format_astc_12x10_unorm : unit -> int = "caml_wgpu_texture_format_astc_12x10_unorm"
external texture_format_astc_12x10_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_12x10_unorm_srgb"
external texture_format_astc_12x12_unorm : unit -> int = "caml_wgpu_texture_format_astc_12x12_unorm"
external texture_format_astc_12x12_unorm_srgb : unit -> int = "caml_wgpu_texture_format_astc_12x12_unorm_srgb"

  let to_int = function
    | Undefined -> texture_format_undefined ()
    | R8_unorm -> texture_format_r8_unorm ()
    | R8_snorm -> texture_format_r8_snorm ()
    | R8_uint -> texture_format_r8_uint ()
    | R8_sint -> texture_format_r8_sint ()
    | R16_uint -> texture_format_r16_uint ()
    | R16_sint -> texture_format_r16_sint ()
    | R16_float -> texture_format_r16_float ()
    | Rg8_unorm -> texture_format_rg8_unorm ()
    | Rg8_snorm -> texture_format_rg8_snorm ()
    | Rg8_uint -> texture_format_rg8_uint ()
    | Rg8_sint -> texture_format_rg8_sint ()
    | R32_float -> texture_format_r32_float ()
    | R32_uint -> texture_format_r32_uint ()
    | R32_sint -> texture_format_r32_sint ()
    | Rg16_uint -> texture_format_rg16_uint ()
    | Rg16_sint -> texture_format_rg16_sint ()
    | Rg16_float -> texture_format_rg16_float ()
    | Rgba8_unorm -> texture_format_rgba8_unorm ()
    | Rgba8_unorm_srgb -> texture_format_rgba8_unorm_srgb ()
    | Rgba8_snorm -> texture_format_rgba8_snorm ()
    | Rgba8_uint -> texture_format_rgba8_uint ()
    | Rgba8_sint -> texture_format_rgba8_sint ()
    | Bgra8_unorm -> texture_format_bgra8_unorm ()
    | Bgra8_unorm_srgb -> texture_format_bgra8_unorm_srgb ()
    | Rgb10_a2_uint -> texture_format_rgb10_a2_uint ()
    | Rgb10_a2_unorm -> texture_format_rgb10_a2_unorm ()
    | Rg11_b10_ufloat -> texture_format_rg11_b10_ufloat ()
    | Rgb9_e5_ufloat -> texture_format_rgb9_e5_ufloat ()
    | Rg32_float -> texture_format_rg32_float ()
    | Rg32_uint -> texture_format_rg32_uint ()
    | Rg32_sint -> texture_format_rg32_sint ()
    | Rgba16_uint -> texture_format_rgba16_uint ()
    | Rgba16_sint -> texture_format_rgba16_sint ()
    | Rgba16_float -> texture_format_rgba16_float ()
    | Rgba32_float -> texture_format_rgba32_float ()
    | Rgba32_uint -> texture_format_rgba32_uint ()
    | Rgba32_sint -> texture_format_rgba32_sint ()
    | Stencil8 -> texture_format_stencil8 ()
    | Depth16_unorm -> texture_format_depth16_unorm ()
    | Depth24_plus -> texture_format_depth24_plus ()
    | Depth24_plus_stencil8 -> texture_format_depth24_plus_stencil8 ()
    | Depth32_float -> texture_format_depth32_float ()
    | Depth32_float_stencil8 -> texture_format_depth32_float_stencil8 ()
    | Bc1_rgba_unorm -> texture_format_bc1_rgba_unorm ()
    | Bc1_rgba_unorm_srgb -> texture_format_bc1_rgba_unorm_srgb ()
    | Bc2_rgba_unorm -> texture_format_bc2_rgba_unorm ()
    | Bc2_rgba_unorm_srgb -> texture_format_bc2_rgba_unorm_srgb ()
    | Bc3_rgba_unorm -> texture_format_bc3_rgba_unorm ()
    | Bc3_rgba_unorm_srgb -> texture_format_bc3_rgba_unorm_srgb ()
    | Bc4_r_unorm -> texture_format_bc4_r_unorm ()
    | Bc4_r_snorm -> texture_format_bc4_r_snorm ()
    | Bc5_rg_unorm -> texture_format_bc5_rg_unorm ()
    | Bc5_rg_snorm -> texture_format_bc5_rg_snorm ()
    | Bc6h_rgb_ufloat -> texture_format_bc6h_rgb_ufloat ()
    | Bc6h_rgb_float -> texture_format_bc6h_rgb_float ()
    | Bc7_rgba_unorm -> texture_format_bc7_rgba_unorm ()
    | Bc7_rgba_unorm_srgb -> texture_format_bc7_rgba_unorm_srgb ()
    | Etc2_rgb8_unorm -> texture_format_etc2_rgb8_unorm ()
    | Etc2_rgb8_unorm_srgb -> texture_format_etc2_rgb8_unorm_srgb ()
    | Etc2_rgb8a1_unorm -> texture_format_etc2_rgb8a1_unorm ()
    | Etc2_rgb8a1_unorm_srgb -> texture_format_etc2_rgb8a1_unorm_srgb ()
    | Etc2_rgba8_unorm -> texture_format_etc2_rgba8_unorm ()
    | Etc2_rgba8_unorm_srgb -> texture_format_etc2_rgba8_unorm_srgb ()
    | Eac_r11_unorm -> texture_format_eac_r11_unorm ()
    | Eac_r11_snorm -> texture_format_eac_r11_snorm ()
    | Eac_rg11_unorm -> texture_format_eac_rg11_unorm ()
    | Eac_rg11_snorm -> texture_format_eac_rg11_snorm ()
    | Astc_4x4_unorm -> texture_format_astc_4x4_unorm ()
    | Astc_4x4_unorm_srgb -> texture_format_astc_4x4_unorm_srgb ()
    | Astc_5x4_unorm -> texture_format_astc_5x4_unorm ()
    | Astc_5x4_unorm_srgb -> texture_format_astc_5x4_unorm_srgb ()
    | Astc_5x5_unorm -> texture_format_astc_5x5_unorm ()
    | Astc_5x5_unorm_srgb -> texture_format_astc_5x5_unorm_srgb ()
    | Astc_6x5_unorm -> texture_format_astc_6x5_unorm ()
    | Astc_6x5_unorm_srgb -> texture_format_astc_6x5_unorm_srgb ()
    | Astc_6x6_unorm -> texture_format_astc_6x6_unorm ()
    | Astc_6x6_unorm_srgb -> texture_format_astc_6x6_unorm_srgb ()
    | Astc_8x5_unorm -> texture_format_astc_8x5_unorm ()
    | Astc_8x5_unorm_srgb -> texture_format_astc_8x5_unorm_srgb ()
    | Astc_8x6_unorm -> texture_format_astc_8x6_unorm ()
    | Astc_8x6_unorm_srgb -> texture_format_astc_8x6_unorm_srgb ()
    | Astc_8x8_unorm -> texture_format_astc_8x8_unorm ()
    | Astc_8x8_unorm_srgb -> texture_format_astc_8x8_unorm_srgb ()
    | Astc_10x5_unorm -> texture_format_astc_10x5_unorm ()
    | Astc_10x5_unorm_srgb -> texture_format_astc_10x5_unorm_srgb ()
    | Astc_10x6_unorm -> texture_format_astc_10x6_unorm ()
    | Astc_10x6_unorm_srgb -> texture_format_astc_10x6_unorm_srgb ()
    | Astc_10x8_unorm -> texture_format_astc_10x8_unorm ()
    | Astc_10x8_unorm_srgb -> texture_format_astc_10x8_unorm_srgb ()
    | Astc_10x10_unorm -> texture_format_astc_10x10_unorm ()
    | Astc_10x10_unorm_srgb -> texture_format_astc_10x10_unorm_srgb ()
    | Astc_12x10_unorm -> texture_format_astc_12x10_unorm ()
    | Astc_12x10_unorm_srgb -> texture_format_astc_12x10_unorm_srgb ()
    | Astc_12x12_unorm -> texture_format_astc_12x12_unorm ()
    | Astc_12x12_unorm_srgb -> texture_format_astc_12x12_unorm_srgb ()
end

module Texture_Sample_Type = struct
  type t =
  | Binding_not_used
  | Undefined
  | Float
  | Unfilterable_float
  | Depth
  | Sint
  | Uint

external texture_sample_type_binding_not_used : unit -> int = "caml_wgpu_texture_sample_type_binding_not_used"
external texture_sample_type_undefined : unit -> int = "caml_wgpu_texture_sample_type_undefined"
external texture_sample_type_float : unit -> int = "caml_wgpu_texture_sample_type_float"
external texture_sample_type_unfilterable_float : unit -> int = "caml_wgpu_texture_sample_type_unfilterable_float"
external texture_sample_type_depth : unit -> int = "caml_wgpu_texture_sample_type_depth"
external texture_sample_type_sint : unit -> int = "caml_wgpu_texture_sample_type_sint"
external texture_sample_type_uint : unit -> int = "caml_wgpu_texture_sample_type_uint"

  let to_int = function
    | Binding_not_used -> texture_sample_type_binding_not_used ()
    | Undefined -> texture_sample_type_undefined ()
    | Float -> texture_sample_type_float ()
    | Unfilterable_float -> texture_sample_type_unfilterable_float ()
    | Depth -> texture_sample_type_depth ()
    | Sint -> texture_sample_type_sint ()
    | Uint -> texture_sample_type_uint ()
end

module Texture_View_Dimension = struct
  type t =
  | Undefined
  | N1d
  | N2d
  | N2d_array
  | Cube
  | Cube_array
  | N3d

external texture_view_dimension_undefined : unit -> int = "caml_wgpu_texture_view_dimension_undefined"
external texture_view_dimension_1d : unit -> int = "caml_wgpu_texture_view_dimension_1d"
external texture_view_dimension_2d : unit -> int = "caml_wgpu_texture_view_dimension_2d"
external texture_view_dimension_2d_array : unit -> int = "caml_wgpu_texture_view_dimension_2d_array"
external texture_view_dimension_cube : unit -> int = "caml_wgpu_texture_view_dimension_cube"
external texture_view_dimension_cube_array : unit -> int = "caml_wgpu_texture_view_dimension_cube_array"
external texture_view_dimension_3d : unit -> int = "caml_wgpu_texture_view_dimension_3d"

  let to_int = function
    | Undefined -> texture_view_dimension_undefined ()
    | N1d -> texture_view_dimension_1d ()
    | N2d -> texture_view_dimension_2d ()
    | N2d_array -> texture_view_dimension_2d_array ()
    | Cube -> texture_view_dimension_cube ()
    | Cube_array -> texture_view_dimension_cube_array ()
    | N3d -> texture_view_dimension_3d ()
end

module Vertex_Format = struct
  type t =
  | Uint8
  | Uint8x2
  | Uint8x4
  | Sint8
  | Sint8x2
  | Sint8x4
  | Unorm8
  | Unorm8x2
  | Unorm8x4
  | Snorm8
  | Snorm8x2
  | Snorm8x4
  | Uint16
  | Uint16x2
  | Uint16x4
  | Sint16
  | Sint16x2
  | Sint16x4
  | Unorm16
  | Unorm16x2
  | Unorm16x4
  | Snorm16
  | Snorm16x2
  | Snorm16x4
  | Float16
  | Float16x2
  | Float16x4
  | Float32
  | Float32x2
  | Float32x3
  | Float32x4
  | Uint32
  | Uint32x2
  | Uint32x3
  | Uint32x4
  | Sint32
  | Sint32x2
  | Sint32x3
  | Sint32x4
  | Unorm10__10__10__2
  | Unorm8x4_b_g_r_a

external vertex_format_uint8 : unit -> int = "caml_wgpu_vertex_format_uint8"
external vertex_format_uint8x2 : unit -> int = "caml_wgpu_vertex_format_uint8x2"
external vertex_format_uint8x4 : unit -> int = "caml_wgpu_vertex_format_uint8x4"
external vertex_format_sint8 : unit -> int = "caml_wgpu_vertex_format_sint8"
external vertex_format_sint8x2 : unit -> int = "caml_wgpu_vertex_format_sint8x2"
external vertex_format_sint8x4 : unit -> int = "caml_wgpu_vertex_format_sint8x4"
external vertex_format_unorm8 : unit -> int = "caml_wgpu_vertex_format_unorm8"
external vertex_format_unorm8x2 : unit -> int = "caml_wgpu_vertex_format_unorm8x2"
external vertex_format_unorm8x4 : unit -> int = "caml_wgpu_vertex_format_unorm8x4"
external vertex_format_snorm8 : unit -> int = "caml_wgpu_vertex_format_snorm8"
external vertex_format_snorm8x2 : unit -> int = "caml_wgpu_vertex_format_snorm8x2"
external vertex_format_snorm8x4 : unit -> int = "caml_wgpu_vertex_format_snorm8x4"
external vertex_format_uint16 : unit -> int = "caml_wgpu_vertex_format_uint16"
external vertex_format_uint16x2 : unit -> int = "caml_wgpu_vertex_format_uint16x2"
external vertex_format_uint16x4 : unit -> int = "caml_wgpu_vertex_format_uint16x4"
external vertex_format_sint16 : unit -> int = "caml_wgpu_vertex_format_sint16"
external vertex_format_sint16x2 : unit -> int = "caml_wgpu_vertex_format_sint16x2"
external vertex_format_sint16x4 : unit -> int = "caml_wgpu_vertex_format_sint16x4"
external vertex_format_unorm16 : unit -> int = "caml_wgpu_vertex_format_unorm16"
external vertex_format_unorm16x2 : unit -> int = "caml_wgpu_vertex_format_unorm16x2"
external vertex_format_unorm16x4 : unit -> int = "caml_wgpu_vertex_format_unorm16x4"
external vertex_format_snorm16 : unit -> int = "caml_wgpu_vertex_format_snorm16"
external vertex_format_snorm16x2 : unit -> int = "caml_wgpu_vertex_format_snorm16x2"
external vertex_format_snorm16x4 : unit -> int = "caml_wgpu_vertex_format_snorm16x4"
external vertex_format_float16 : unit -> int = "caml_wgpu_vertex_format_float16"
external vertex_format_float16x2 : unit -> int = "caml_wgpu_vertex_format_float16x2"
external vertex_format_float16x4 : unit -> int = "caml_wgpu_vertex_format_float16x4"
external vertex_format_float32 : unit -> int = "caml_wgpu_vertex_format_float32"
external vertex_format_float32x2 : unit -> int = "caml_wgpu_vertex_format_float32x2"
external vertex_format_float32x3 : unit -> int = "caml_wgpu_vertex_format_float32x3"
external vertex_format_float32x4 : unit -> int = "caml_wgpu_vertex_format_float32x4"
external vertex_format_uint32 : unit -> int = "caml_wgpu_vertex_format_uint32"
external vertex_format_uint32x2 : unit -> int = "caml_wgpu_vertex_format_uint32x2"
external vertex_format_uint32x3 : unit -> int = "caml_wgpu_vertex_format_uint32x3"
external vertex_format_uint32x4 : unit -> int = "caml_wgpu_vertex_format_uint32x4"
external vertex_format_sint32 : unit -> int = "caml_wgpu_vertex_format_sint32"
external vertex_format_sint32x2 : unit -> int = "caml_wgpu_vertex_format_sint32x2"
external vertex_format_sint32x3 : unit -> int = "caml_wgpu_vertex_format_sint32x3"
external vertex_format_sint32x4 : unit -> int = "caml_wgpu_vertex_format_sint32x4"
external vertex_format_unorm10__10__10__2 : unit -> int = "caml_wgpu_vertex_format_unorm10__10__10__2"
external vertex_format_unorm8x4_b_g_r_a : unit -> int = "caml_wgpu_vertex_format_unorm8x4_b_g_r_a"

  let to_int = function
    | Uint8 -> vertex_format_uint8 ()
    | Uint8x2 -> vertex_format_uint8x2 ()
    | Uint8x4 -> vertex_format_uint8x4 ()
    | Sint8 -> vertex_format_sint8 ()
    | Sint8x2 -> vertex_format_sint8x2 ()
    | Sint8x4 -> vertex_format_sint8x4 ()
    | Unorm8 -> vertex_format_unorm8 ()
    | Unorm8x2 -> vertex_format_unorm8x2 ()
    | Unorm8x4 -> vertex_format_unorm8x4 ()
    | Snorm8 -> vertex_format_snorm8 ()
    | Snorm8x2 -> vertex_format_snorm8x2 ()
    | Snorm8x4 -> vertex_format_snorm8x4 ()
    | Uint16 -> vertex_format_uint16 ()
    | Uint16x2 -> vertex_format_uint16x2 ()
    | Uint16x4 -> vertex_format_uint16x4 ()
    | Sint16 -> vertex_format_sint16 ()
    | Sint16x2 -> vertex_format_sint16x2 ()
    | Sint16x4 -> vertex_format_sint16x4 ()
    | Unorm16 -> vertex_format_unorm16 ()
    | Unorm16x2 -> vertex_format_unorm16x2 ()
    | Unorm16x4 -> vertex_format_unorm16x4 ()
    | Snorm16 -> vertex_format_snorm16 ()
    | Snorm16x2 -> vertex_format_snorm16x2 ()
    | Snorm16x4 -> vertex_format_snorm16x4 ()
    | Float16 -> vertex_format_float16 ()
    | Float16x2 -> vertex_format_float16x2 ()
    | Float16x4 -> vertex_format_float16x4 ()
    | Float32 -> vertex_format_float32 ()
    | Float32x2 -> vertex_format_float32x2 ()
    | Float32x3 -> vertex_format_float32x3 ()
    | Float32x4 -> vertex_format_float32x4 ()
    | Uint32 -> vertex_format_uint32 ()
    | Uint32x2 -> vertex_format_uint32x2 ()
    | Uint32x3 -> vertex_format_uint32x3 ()
    | Uint32x4 -> vertex_format_uint32x4 ()
    | Sint32 -> vertex_format_sint32 ()
    | Sint32x2 -> vertex_format_sint32x2 ()
    | Sint32x3 -> vertex_format_sint32x3 ()
    | Sint32x4 -> vertex_format_sint32x4 ()
    | Unorm10__10__10__2 -> vertex_format_unorm10__10__10__2 ()
    | Unorm8x4_b_g_r_a -> vertex_format_unorm8x4_b_g_r_a ()
end

module Vertex_Step_Mode = struct
  type t =
  | Vertex_buffer_not_used
  | Undefined
  | Vertex
  | Instance

external vertex_step_mode_vertex_buffer_not_used : unit -> int = "caml_wgpu_vertex_step_mode_vertex_buffer_not_used"
external vertex_step_mode_undefined : unit -> int = "caml_wgpu_vertex_step_mode_undefined"
external vertex_step_mode_vertex : unit -> int = "caml_wgpu_vertex_step_mode_vertex"
external vertex_step_mode_instance : unit -> int = "caml_wgpu_vertex_step_mode_instance"

  let to_int = function
    | Vertex_buffer_not_used -> vertex_step_mode_vertex_buffer_not_used ()
    | Undefined -> vertex_step_mode_undefined ()
    | Vertex -> vertex_step_mode_vertex ()
    | Instance -> vertex_step_mode_instance ()
end

module Wait_Status = struct
  type t =
  | Success
  | Timed_out
  | Unsupported_timeout
  | Unsupported_count
  | Unsupported_mixed_sources

external wait_status_success : unit -> int = "caml_wgpu_wait_status_success"
external wait_status_timed_out : unit -> int = "caml_wgpu_wait_status_timed_out"
external wait_status_unsupported_timeout : unit -> int = "caml_wgpu_wait_status_unsupported_timeout"
external wait_status_unsupported_count : unit -> int = "caml_wgpu_wait_status_unsupported_count"
external wait_status_unsupported_mixed_sources : unit -> int = "caml_wgpu_wait_status_unsupported_mixed_sources"

  let to_int = function
    | Success -> wait_status_success ()
    | Timed_out -> wait_status_timed_out ()
    | Unsupported_timeout -> wait_status_unsupported_timeout ()
    | Unsupported_count -> wait_status_unsupported_count ()
    | Unsupported_mixed_sources -> wait_status_unsupported_mixed_sources ()
end

module WGSL_Language_Feature_Name = struct
  type t =
  | Readonly_and_readwrite_storage_textures
  | Packed4x8_integer_dot_product
  | Unrestricted_pointer_parameters
  | Pointer_composite_access

external wgsl_language_feature_name_readonly_and_readwrite_storage_textures : unit -> int = "caml_wgpu_wgsl_language_feature_name_readonly_and_readwrite_storage_textures"
external wgsl_language_feature_name_packed4x8_integer_dot_product : unit -> int = "caml_wgpu_wgsl_language_feature_name_packed4x8_integer_dot_product"
external wgsl_language_feature_name_unrestricted_pointer_parameters : unit -> int = "caml_wgpu_wgsl_language_feature_name_unrestricted_pointer_parameters"
external wgsl_language_feature_name_pointer_composite_access : unit -> int = "caml_wgpu_wgsl_language_feature_name_pointer_composite_access"

  let to_int = function
    | Readonly_and_readwrite_storage_textures -> wgsl_language_feature_name_readonly_and_readwrite_storage_textures ()
    | Packed4x8_integer_dot_product -> wgsl_language_feature_name_packed4x8_integer_dot_product ()
    | Unrestricted_pointer_parameters -> wgsl_language_feature_name_unrestricted_pointer_parameters ()
    | Pointer_composite_access -> wgsl_language_feature_name_pointer_composite_access ()
end
module Buffer_Usage = struct
  type t =
  | None
  | Map_read
  | Map_write
  | Copy_src
  | Copy_dst
  | Index
  | Vertex
  | Uniform
  | Storage
  | Indirect
  | Query_resolve

external buffer_usage_none : unit -> int = "caml_wgpu_buffer_usage_none"
external buffer_usage_map_read : unit -> int = "caml_wgpu_buffer_usage_map_read"
external buffer_usage_map_write : unit -> int = "caml_wgpu_buffer_usage_map_write"
external buffer_usage_copy_src : unit -> int = "caml_wgpu_buffer_usage_copy_src"
external buffer_usage_copy_dst : unit -> int = "caml_wgpu_buffer_usage_copy_dst"
external buffer_usage_index : unit -> int = "caml_wgpu_buffer_usage_index"
external buffer_usage_vertex : unit -> int = "caml_wgpu_buffer_usage_vertex"
external buffer_usage_uniform : unit -> int = "caml_wgpu_buffer_usage_uniform"
external buffer_usage_storage : unit -> int = "caml_wgpu_buffer_usage_storage"
external buffer_usage_indirect : unit -> int = "caml_wgpu_buffer_usage_indirect"
external buffer_usage_query_resolve : unit -> int = "caml_wgpu_buffer_usage_query_resolve"

  let to_int = function
    | None -> buffer_usage_none ()
    | Map_read -> buffer_usage_map_read ()
    | Map_write -> buffer_usage_map_write ()
    | Copy_src -> buffer_usage_copy_src ()
    | Copy_dst -> buffer_usage_copy_dst ()
    | Index -> buffer_usage_index ()
    | Vertex -> buffer_usage_vertex ()
    | Uniform -> buffer_usage_uniform ()
    | Storage -> buffer_usage_storage ()
    | Indirect -> buffer_usage_indirect ()
    | Query_resolve -> buffer_usage_query_resolve ()

  let list_to_int flags =
    List.fold_left (fun acc f -> acc lor to_int f) 0 flags
end

module Color_Write_Mask = struct
  type t =
  | None
  | Red
  | Green
  | Blue
  | Alpha
  | All

external color_write_mask_none : unit -> int = "caml_wgpu_color_write_mask_none"
external color_write_mask_red : unit -> int = "caml_wgpu_color_write_mask_red"
external color_write_mask_green : unit -> int = "caml_wgpu_color_write_mask_green"
external color_write_mask_blue : unit -> int = "caml_wgpu_color_write_mask_blue"
external color_write_mask_alpha : unit -> int = "caml_wgpu_color_write_mask_alpha"
external color_write_mask_all : unit -> int = "caml_wgpu_color_write_mask_all"

  let to_int = function
    | None -> color_write_mask_none ()
    | Red -> color_write_mask_red ()
    | Green -> color_write_mask_green ()
    | Blue -> color_write_mask_blue ()
    | Alpha -> color_write_mask_alpha ()
    | All -> color_write_mask_all ()

  let list_to_int flags =
    List.fold_left (fun acc f -> acc lor to_int f) 0 flags
end

module Map_Mode = struct
  type t =
  | None
  | Read
  | Write

external map_mode_none : unit -> int = "caml_wgpu_map_mode_none"
external map_mode_read : unit -> int = "caml_wgpu_map_mode_read"
external map_mode_write : unit -> int = "caml_wgpu_map_mode_write"

  let to_int = function
    | None -> map_mode_none ()
    | Read -> map_mode_read ()
    | Write -> map_mode_write ()

  let list_to_int flags =
    List.fold_left (fun acc f -> acc lor to_int f) 0 flags
end

module Shader_Stage = struct
  type t =
  | None
  | Vertex
  | Fragment
  | Compute

external shader_stage_none : unit -> int = "caml_wgpu_shader_stage_none"
external shader_stage_vertex : unit -> int = "caml_wgpu_shader_stage_vertex"
external shader_stage_fragment : unit -> int = "caml_wgpu_shader_stage_fragment"
external shader_stage_compute : unit -> int = "caml_wgpu_shader_stage_compute"

  let to_int = function
    | None -> shader_stage_none ()
    | Vertex -> shader_stage_vertex ()
    | Fragment -> shader_stage_fragment ()
    | Compute -> shader_stage_compute ()

  let list_to_int flags =
    List.fold_left (fun acc f -> acc lor to_int f) 0 flags
end

module Texture_Usage = struct
  type t =
  | None
  | Copy_src
  | Copy_dst
  | Texture_binding
  | Storage_binding
  | Render_attachment

external texture_usage_none : unit -> int = "caml_wgpu_texture_usage_none"
external texture_usage_copy_src : unit -> int = "caml_wgpu_texture_usage_copy_src"
external texture_usage_copy_dst : unit -> int = "caml_wgpu_texture_usage_copy_dst"
external texture_usage_texture_binding : unit -> int = "caml_wgpu_texture_usage_texture_binding"
external texture_usage_storage_binding : unit -> int = "caml_wgpu_texture_usage_storage_binding"
external texture_usage_render_attachment : unit -> int = "caml_wgpu_texture_usage_render_attachment"

  let to_int = function
    | None -> texture_usage_none ()
    | Copy_src -> texture_usage_copy_src ()
    | Copy_dst -> texture_usage_copy_dst ()
    | Texture_binding -> texture_usage_texture_binding ()
    | Storage_binding -> texture_usage_storage_binding ()
    | Render_attachment -> texture_usage_render_attachment ()

  let list_to_int flags =
    List.fold_left (fun acc f -> acc lor to_int f) 0 flags
end
type adapter = nativeint

external adapter_release : adapter -> unit = "caml_wgpu_adapter_release"

type bind_group = nativeint

external bind_group_release : bind_group -> unit = "caml_wgpu_bind_group_release"

type bind_group_layout = nativeint

external bind_group_layout_release : bind_group_layout -> unit = "caml_wgpu_bind_group_layout_release"

type buffer = nativeint

external buffer_release : buffer -> unit = "caml_wgpu_buffer_release"

type command_buffer = nativeint

external command_buffer_release : command_buffer -> unit = "caml_wgpu_command_buffer_release"

type command_encoder = nativeint

external command_encoder_release : command_encoder -> unit = "caml_wgpu_command_encoder_release"

type compute_pass_encoder = nativeint

external compute_pass_encoder_release : compute_pass_encoder -> unit = "caml_wgpu_compute_pass_encoder_release"

type compute_pipeline = nativeint

external compute_pipeline_release : compute_pipeline -> unit = "caml_wgpu_compute_pipeline_release"

type device = nativeint

external device_release : device -> unit = "caml_wgpu_device_release"

type instance = nativeint

external instance_release : instance -> unit = "caml_wgpu_instance_release"

type pipeline_layout = nativeint

external pipeline_layout_release : pipeline_layout -> unit = "caml_wgpu_pipeline_layout_release"

type query_set = nativeint

external query_set_release : query_set -> unit = "caml_wgpu_query_set_release"

type queue = nativeint

external queue_release : queue -> unit = "caml_wgpu_queue_release"

type render_bundle = nativeint

external render_bundle_release : render_bundle -> unit = "caml_wgpu_render_bundle_release"

type render_bundle_encoder = nativeint

external render_bundle_encoder_release : render_bundle_encoder -> unit = "caml_wgpu_render_bundle_encoder_release"

type render_pass_encoder = nativeint

external render_pass_encoder_release : render_pass_encoder -> unit = "caml_wgpu_render_pass_encoder_release"

type render_pipeline = nativeint

external render_pipeline_release : render_pipeline -> unit = "caml_wgpu_render_pipeline_release"

type sampler = nativeint

external sampler_release : sampler -> unit = "caml_wgpu_sampler_release"

type shader_module = nativeint

external shader_module_release : shader_module -> unit = "caml_wgpu_shader_module_release"

type surface = nativeint

external surface_release : surface -> unit = "caml_wgpu_surface_release"

type texture = nativeint

external texture_release : texture -> unit = "caml_wgpu_texture_release"

type texture_view = nativeint

external texture_view_release : texture_view -> unit = "caml_wgpu_texture_view_release"
external create_instance : unit -> instance = "caml_wgpu_create_instance"

external instance_request_adapter_sync : instance -> adapter
  = "caml_wgpu_instance_request_adapter_sync"

external adapter_request_device_sync : adapter -> device
  = "caml_wgpu_adapter_request_device_sync"

external device_get_queue : device -> queue = "caml_wgpu_device_get_queue"

type adapter_info =
  { vendor : string
  ; architecture : string
  ; device : string
  ; description : string
  ; backend_type : int
  ; adapter_type : int
  }

external adapter_get_info_raw :
  adapter -> string * string * string * string * int * int
  = "caml_wgpu_adapter_get_info"

let adapter_get_info adapter =
  let vendor, architecture, device, description, backend_type, adapter_type =
    adapter_get_info_raw adapter
  in
  { vendor; architecture; device; description; backend_type; adapter_type }
