(* Generated by gen_bindings - high-level OCaml interface *)

include module type of Enums
include module type of Bitsets

module Bind_group : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Bind_group_layout : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Buffer : sig
  type t

  val release : t -> unit
  val get_mapped_range : t -> offset:int64 -> size:int64 -> nativeint
  val get_const_mapped_range : t -> offset:int64 -> size:int64 -> nativeint
  val set_label : t -> label:string -> unit
  val get_usage : t -> int
  val get_size : t -> int64
  val get_map_state : t -> Buffer_map_state.t
  val unmap : t -> unit
  val destroy : t -> unit
end

module Command_buffer : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Pipeline_layout : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Query_set : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
  val get_type : t -> Query_type.t
  val get_count : t -> int
  val destroy : t -> unit
end

module Render_bundle : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Sampler : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Shader_module : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Texture_view : sig
  type t

  val release : t -> unit
  val set_label : t -> label:string -> unit
end

module Compute_pipeline : sig
  type t

  val release : t -> unit
  val get_bind_group_layout : t -> group_index:int -> Bind_group_layout.t
  val set_label : t -> label:string -> unit
end

module Render_pipeline : sig
  type t

  val release : t -> unit
  val get_bind_group_layout : t -> group_index:int -> Bind_group_layout.t
  val set_label : t -> label:string -> unit
end

module Texture : sig
  type t

  val release : t -> unit

  val create_view
    :  t
    -> ?label:string
    -> format:Texture_format.t
    -> dimension:Texture_view_dimension.t
    -> base_mip_level:int
    -> mip_level_count:int
    -> base_array_layer:int
    -> array_layer_count:int
    -> aspect:Texture_aspect.t
    -> usage:Texture_usage.Item.t list
    -> unit
    -> Texture_view.t

  val set_label : t -> label:string -> unit
  val get_width : t -> int
  val get_height : t -> int
  val get_depth_or_array_layers : t -> int
  val get_mip_level_count : t -> int
  val get_sample_count : t -> int
  val get_dimension : t -> Texture_dimension.t
  val get_format : t -> Texture_format.t
  val get_usage : t -> int
  val destroy : t -> unit
end

module Compute_pass_encoder : sig
  type t

  val release : t -> unit
  val insert_debug_marker : t -> marker_label:string -> unit
  val pop_debug_group : t -> unit
  val push_debug_group : t -> group_label:string -> unit
  val set_pipeline : t -> pipeline:Compute_pipeline.t -> unit

  val set_bind_group
    :  t
    -> group_index:int
    -> group:Bind_group.t
    -> dynamic_offsets:int list
    -> unit

  val dispatch_workgroups
    :  t
    -> workgroupCountX:int
    -> workgroupCountY:int
    -> workgroupCountZ:int
    -> unit

  val dispatch_workgroups_indirect
    :  t
    -> indirect_buffer:Buffer.t
    -> indirect_offset:int64
    -> unit

  val end_ : t -> unit
  val set_label : t -> label:string -> unit
end

module Render_bundle_encoder : sig
  type t

  val release : t -> unit
  val set_pipeline : t -> pipeline:Render_pipeline.t -> unit

  val set_bind_group
    :  t
    -> group_index:int
    -> group:Bind_group.t
    -> dynamic_offsets:int list
    -> unit

  val draw
    :  t
    -> vertex_count:int
    -> instance_count:int
    -> first_vertex:int
    -> first_instance:int
    -> unit

  val draw_indexed
    :  t
    -> index_count:int
    -> instance_count:int
    -> first_index:int
    -> base_vertex:int
    -> first_instance:int
    -> unit

  val draw_indirect : t -> indirect_buffer:Buffer.t -> indirect_offset:int64 -> unit

  val draw_indexed_indirect
    :  t
    -> indirect_buffer:Buffer.t
    -> indirect_offset:int64
    -> unit

  val insert_debug_marker : t -> marker_label:string -> unit
  val pop_debug_group : t -> unit
  val push_debug_group : t -> group_label:string -> unit

  val set_vertex_buffer
    :  t
    -> slot:int
    -> buffer:Buffer.t
    -> offset:int64
    -> size:int64
    -> unit

  val set_index_buffer
    :  t
    -> buffer:Buffer.t
    -> format:Index_format.t
    -> offset:int64
    -> size:int64
    -> unit

  val finish : t -> ?label:string -> unit -> Render_bundle.t
  val set_label : t -> label:string -> unit
end

module Render_pass_encoder : sig
  type t

  val release : t -> unit
  val set_pipeline : t -> pipeline:Render_pipeline.t -> unit

  val set_bind_group
    :  t
    -> group_index:int
    -> group:Bind_group.t
    -> dynamic_offsets:int list
    -> unit

  val draw
    :  t
    -> vertex_count:int
    -> instance_count:int
    -> first_vertex:int
    -> first_instance:int
    -> unit

  val draw_indexed
    :  t
    -> index_count:int
    -> instance_count:int
    -> first_index:int
    -> base_vertex:int
    -> first_instance:int
    -> unit

  val draw_indirect : t -> indirect_buffer:Buffer.t -> indirect_offset:int64 -> unit

  val draw_indexed_indirect
    :  t
    -> indirect_buffer:Buffer.t
    -> indirect_offset:int64
    -> unit

  val execute_bundles : t -> bundles:Render_bundle.t list -> unit
  val insert_debug_marker : t -> marker_label:string -> unit
  val pop_debug_group : t -> unit
  val push_debug_group : t -> group_label:string -> unit
  val set_stencil_reference : t -> reference:int -> unit
  val set_blend_constant : t -> r:float -> g:float -> b:float -> a:float -> unit -> unit

  val set_viewport
    :  t
    -> x:float
    -> y:float
    -> width:float
    -> height:float
    -> min_depth:float
    -> max_depth:float
    -> unit

  val set_scissor_rect : t -> x:int -> y:int -> width:int -> height:int -> unit

  val set_vertex_buffer
    :  t
    -> slot:int
    -> buffer:Buffer.t
    -> offset:int64
    -> size:int64
    -> unit

  val set_index_buffer
    :  t
    -> buffer:Buffer.t
    -> format:Index_format.t
    -> offset:int64
    -> size:int64
    -> unit

  val begin_occlusion_query : t -> query_index:int -> unit
  val end_occlusion_query : t -> unit
  val end_ : t -> unit
  val set_label : t -> label:string -> unit
end

module Bind_group_entry : sig
  type t = private
    { binding : int
    ; buffer : Buffer.t option
    ; offset : int64
    ; size : int64
    ; sampler : Sampler.t option
    ; texture_view : Texture_view.t option
    }

  val create
    :  binding:int
    -> ?buffer:Buffer.t
    -> offset:int64
    -> size:int64
    -> ?sampler:Sampler.t
    -> ?texture_view:Texture_view.t
    -> unit
    -> t
end

module Bind_group_layout_entry : sig
  module Buffer_binding_layout : sig
    type t = private
      { type_ : Buffer_binding_type.t
      ; has_dynamic_offset : bool
      ; min_binding_size : int64
      }

    val create
      :  type_:Buffer_binding_type.t
      -> has_dynamic_offset:bool
      -> min_binding_size:int64
      -> unit
      -> t
  end

  module Sampler_binding_layout : sig
    type t = private { type_ : Sampler_binding_type.t }

    val create : type_:Sampler_binding_type.t -> unit -> t
  end

  module Storage_texture_binding_layout : sig
    type t = private
      { access : Storage_texture_access.t
      ; format : Texture_format.t
      ; view_dimension : Texture_view_dimension.t
      }

    val create
      :  access:Storage_texture_access.t
      -> format:Texture_format.t
      -> view_dimension:Texture_view_dimension.t
      -> unit
      -> t
  end

  module Texture_binding_layout : sig
    type t = private
      { sample_type : Texture_sample_type.t
      ; view_dimension : Texture_view_dimension.t
      ; multisampled : bool
      }

    val create
      :  sample_type:Texture_sample_type.t
      -> view_dimension:Texture_view_dimension.t
      -> multisampled:bool
      -> unit
      -> t
  end

  type t = private
    { binding : int
    ; visibility : Shader_stage.Item.t list
    ; buffer : Buffer_binding_layout.t option
    ; sampler : Sampler_binding_layout.t option
    ; texture : Texture_binding_layout.t option
    ; storage_texture : Storage_texture_binding_layout.t option
    }

  val create
    :  binding:int
    -> visibility:Shader_stage.Item.t list
    -> ?buffer:Buffer_binding_layout.t
    -> ?sampler:Sampler_binding_layout.t
    -> ?texture:Texture_binding_layout.t
    -> ?storage_texture:Storage_texture_binding_layout.t
    -> unit
    -> t
end

module Color_target_state : sig
  module Blend_state : sig
    module Blend_component : sig
      type t = private
        { operation : Blend_operation.t
        ; src_factor : Blend_factor.t
        ; dst_factor : Blend_factor.t
        }

      val create
        :  operation:Blend_operation.t
        -> src_factor:Blend_factor.t
        -> dst_factor:Blend_factor.t
        -> unit
        -> t
    end

    type t = private
      { color : Blend_component.t
      ; alpha : Blend_component.t
      }

    val create : color:Blend_component.t -> alpha:Blend_component.t -> unit -> t
  end

  type t = private
    { format : Texture_format.t
    ; blend : Blend_state.t option
    ; write_mask : Color_write_mask.Item.t list
    }

  val create
    :  format:Texture_format.t
    -> ?blend:Blend_state.t
    -> write_mask:Color_write_mask.Item.t list
    -> unit
    -> t
end

module Compilation_message : sig
  type t = private
    { message : string
    ; type_ : Compilation_message_type.t
    ; line_num : int64
    ; line_pos : int64
    ; offset : int64
    ; length : int64
    }

  val create
    :  message:string
    -> type_:Compilation_message_type.t
    -> line_num:int64
    -> line_pos:int64
    -> offset:int64
    -> length:int64
    -> unit
    -> t
end

module Constant_entry : sig
  type t = private
    { key : string
    ; value : float
    }

  val create : ?key:string -> value:float -> unit -> t
end

module Render_pass_color_attachment : sig
  module Color : sig
    type t = private
      { r : float
      ; g : float
      ; b : float
      ; a : float
      }

    val create : r:float -> g:float -> b:float -> a:float -> unit -> t
  end

  type t = private
    { view : Texture_view.t option
    ; depth_slice : int
    ; resolve_target : Texture_view.t option
    ; load_op : Load_op.t
    ; store_op : Store_op.t
    ; clear_value : Color.t option
    }

  val create
    :  ?view:Texture_view.t
    -> ?depth_slice:int
    -> ?resolve_target:Texture_view.t
    -> load_op:Load_op.t
    -> store_op:Store_op.t
    -> ?clear_value:Color.t
    -> unit
    -> t
end

module Vertex_attribute : sig
  type t = private
    { format : Vertex_format.t
    ; offset : int64
    ; shader_location : int
    }

  val create : format:Vertex_format.t -> offset:int64 -> shader_location:int -> unit -> t
end

module Vertex_buffer_layout : sig
  type t = private
    { step_mode : Vertex_step_mode.t
    ; array_stride : int64
    ; attributes : Vertex_attribute.t list
    }

  val create
    :  step_mode:Vertex_step_mode.t
    -> array_stride:int64
    -> ?attributes:Vertex_attribute.t list
    -> unit
    -> t
end

module Blend_state : sig
  module Blend_component : sig
    type t = private
      { operation : Blend_operation.t
      ; src_factor : Blend_factor.t
      ; dst_factor : Blend_factor.t
      }

    val create
      :  operation:Blend_operation.t
      -> src_factor:Blend_factor.t
      -> dst_factor:Blend_factor.t
      -> unit
      -> t
  end

  type t = private
    { color : Blend_component.t
    ; alpha : Blend_component.t
    }

  val create : color:Blend_component.t -> alpha:Blend_component.t -> unit -> t
end

module Compute_pass_timestamp_writes : sig
  type t = private
    { query_set : Query_set.t
    ; beginning_of_pass_write_index : int
    ; end_of_pass_write_index : int
    }

  val create
    :  query_set:Query_set.t
    -> beginning_of_pass_write_index:int
    -> end_of_pass_write_index:int
    -> unit
    -> t
end

module Depth_stencil_state : sig
  module Stencil_face_state : sig
    type t = private
      { compare : Compare_function.t
      ; fail_op : Stencil_operation.t
      ; depth_fail_op : Stencil_operation.t
      ; pass_op : Stencil_operation.t
      }

    val create
      :  compare:Compare_function.t
      -> fail_op:Stencil_operation.t
      -> depth_fail_op:Stencil_operation.t
      -> pass_op:Stencil_operation.t
      -> unit
      -> t
  end

  type t = private
    { format : Texture_format.t
    ; depth_write_enabled : Optional_bool.t
    ; depth_compare : Compare_function.t
    ; stencil_front : Stencil_face_state.t
    ; stencil_back : Stencil_face_state.t
    ; stencil_read_mask : int
    ; stencil_write_mask : int
    ; depth_bias : int
    ; depth_bias_slope_scale : float
    ; depth_bias_clamp : float
    }

  val create
    :  format:Texture_format.t
    -> depth_write_enabled:Optional_bool.t
    -> depth_compare:Compare_function.t
    -> stencil_front:Stencil_face_state.t
    -> stencil_back:Stencil_face_state.t
    -> stencil_read_mask:int
    -> stencil_write_mask:int
    -> depth_bias:int
    -> depth_bias_slope_scale:float
    -> depth_bias_clamp:float
    -> unit
    -> t
end

module Fragment_state : sig
  type t = private
    { module_ : Shader_module.t
    ; entry_point : string
    ; constants : Constant_entry.t list
    ; targets : Color_target_state.t list
    }

  val create
    :  module_:Shader_module.t
    -> entry_point:string
    -> ?constants:Constant_entry.t list
    -> ?targets:Color_target_state.t list
    -> unit
    -> t
end

module Limits : sig
  type t = private
    { max_texture_dimension_1D : int
    ; max_texture_dimension_2D : int
    ; max_texture_dimension_3D : int
    ; max_texture_array_layers : int
    ; max_bind_groups : int
    ; max_bind_groups_plus_vertex_buffers : int
    ; max_bindings_per_bind_group : int
    ; max_dynamic_uniform_buffers_per_pipeline_layout : int
    ; max_dynamic_storage_buffers_per_pipeline_layout : int
    ; max_sampled_textures_per_shader_stage : int
    ; max_samplers_per_shader_stage : int
    ; max_storage_buffers_per_shader_stage : int
    ; max_storage_textures_per_shader_stage : int
    ; max_uniform_buffers_per_shader_stage : int
    ; max_uniform_buffer_binding_size : int64
    ; max_storage_buffer_binding_size : int64
    ; min_uniform_buffer_offset_alignment : int
    ; min_storage_buffer_offset_alignment : int
    ; max_vertex_buffers : int
    ; max_buffer_size : int64
    ; max_vertex_attributes : int
    ; max_vertex_buffer_array_stride : int
    ; max_inter_stage_shader_variables : int
    ; max_color_attachments : int
    ; max_color_attachment_bytes_per_sample : int
    ; max_compute_workgroup_storage_size : int
    ; max_compute_invocations_per_workgroup : int
    ; max_compute_workgroup_size_x : int
    ; max_compute_workgroup_size_y : int
    ; max_compute_workgroup_size_z : int
    ; max_compute_workgroups_per_dimension : int
    }

  val create
    :  max_texture_dimension_1D:int
    -> max_texture_dimension_2D:int
    -> max_texture_dimension_3D:int
    -> max_texture_array_layers:int
    -> max_bind_groups:int
    -> max_bind_groups_plus_vertex_buffers:int
    -> max_bindings_per_bind_group:int
    -> max_dynamic_uniform_buffers_per_pipeline_layout:int
    -> max_dynamic_storage_buffers_per_pipeline_layout:int
    -> max_sampled_textures_per_shader_stage:int
    -> max_samplers_per_shader_stage:int
    -> max_storage_buffers_per_shader_stage:int
    -> max_storage_textures_per_shader_stage:int
    -> max_uniform_buffers_per_shader_stage:int
    -> max_uniform_buffer_binding_size:int64
    -> max_storage_buffer_binding_size:int64
    -> min_uniform_buffer_offset_alignment:int
    -> min_storage_buffer_offset_alignment:int
    -> max_vertex_buffers:int
    -> max_buffer_size:int64
    -> max_vertex_attributes:int
    -> max_vertex_buffer_array_stride:int
    -> max_inter_stage_shader_variables:int
    -> max_color_attachments:int
    -> max_color_attachment_bytes_per_sample:int
    -> max_compute_workgroup_storage_size:int
    -> max_compute_invocations_per_workgroup:int
    -> max_compute_workgroup_size_x:int
    -> max_compute_workgroup_size_y:int
    -> max_compute_workgroup_size_z:int
    -> max_compute_workgroups_per_dimension:int
    -> unit
    -> t
end

module Render_pass_depth_stencil_attachment : sig
  type t = private
    { view : Texture_view.t
    ; depth_load_op : Load_op.t
    ; depth_store_op : Store_op.t
    ; depth_clear_value : float
    ; depth_read_only : bool
    ; stencil_load_op : Load_op.t
    ; stencil_store_op : Store_op.t
    ; stencil_clear_value : int
    ; stencil_read_only : bool
    }

  val create
    :  view:Texture_view.t
    -> depth_load_op:Load_op.t
    -> depth_store_op:Store_op.t
    -> depth_clear_value:float
    -> depth_read_only:bool
    -> stencil_load_op:Load_op.t
    -> stencil_store_op:Store_op.t
    -> stencil_clear_value:int
    -> stencil_read_only:bool
    -> unit
    -> t
end

module Render_pass_timestamp_writes : sig
  type t = private
    { query_set : Query_set.t
    ; beginning_of_pass_write_index : int
    ; end_of_pass_write_index : int
    }

  val create
    :  query_set:Query_set.t
    -> beginning_of_pass_write_index:int
    -> end_of_pass_write_index:int
    -> unit
    -> t
end

module Adapter_info : sig
  type t =
    { vendor : string
    ; architecture : string
    ; device : string
    ; description : string
    ; backend_type : Backend_type.t
    ; adapter_type : Adapter_type.t
    }
end

module Command_encoder : sig
  type t

  val release : t -> unit
  val finish : t -> ?label:string -> unit -> Command_buffer.t

  val begin_compute_pass
    :  t
    -> ?label:string
    -> ?timestamp_writes:Compute_pass_timestamp_writes.t
    -> unit
    -> Compute_pass_encoder.t

  val begin_render_pass
    :  t
    -> ?label:string
    -> ?color_attachments:Render_pass_color_attachment.t list
    -> ?depth_stencil_attachment:Render_pass_depth_stencil_attachment.t
    -> ?occlusion_query_set:Query_set.t
    -> ?timestamp_writes:Render_pass_timestamp_writes.t
    -> unit
    -> Render_pass_encoder.t

  val copy_buffer_to_buffer
    :  t
    -> source:Buffer.t
    -> source_offset:int64
    -> destination:Buffer.t
    -> destination_offset:int64
    -> size:int64
    -> unit

  val copy_buffer_to_texture
    :  t
    -> source_layout_offset:int64
    -> source_layout_bytes_per_row:int
    -> source_layout_rows_per_image:int
    -> source_buffer:Buffer.t
    -> destination_texture:Texture.t
    -> destination_mip_level:int
    -> destination_origin_x:int
    -> destination_origin_y:int
    -> destination_origin_z:int
    -> destination_aspect:Texture_aspect.t
    -> copy_size_width:int
    -> copy_size_height:int
    -> copy_size_depth_or_array_layers:int
    -> unit
    -> unit

  val copy_texture_to_buffer
    :  t
    -> source_texture:Texture.t
    -> source_mip_level:int
    -> source_origin_x:int
    -> source_origin_y:int
    -> source_origin_z:int
    -> source_aspect:Texture_aspect.t
    -> destination_layout_offset:int64
    -> destination_layout_bytes_per_row:int
    -> destination_layout_rows_per_image:int
    -> destination_buffer:Buffer.t
    -> copy_size_width:int
    -> copy_size_height:int
    -> copy_size_depth_or_array_layers:int
    -> unit
    -> unit

  val copy_texture_to_texture
    :  t
    -> source_texture:Texture.t
    -> source_mip_level:int
    -> source_origin_x:int
    -> source_origin_y:int
    -> source_origin_z:int
    -> source_aspect:Texture_aspect.t
    -> destination_texture:Texture.t
    -> destination_mip_level:int
    -> destination_origin_x:int
    -> destination_origin_y:int
    -> destination_origin_z:int
    -> destination_aspect:Texture_aspect.t
    -> copy_size_width:int
    -> copy_size_height:int
    -> copy_size_depth_or_array_layers:int
    -> unit
    -> unit

  val clear_buffer : t -> buffer:Buffer.t -> offset:int64 -> size:int64 -> unit
  val insert_debug_marker : t -> marker_label:string -> unit
  val pop_debug_group : t -> unit
  val push_debug_group : t -> group_label:string -> unit

  val resolve_query_set
    :  t
    -> query_set:Query_set.t
    -> first_query:int
    -> query_count:int
    -> destination:Buffer.t
    -> destination_offset:int64
    -> unit

  val write_timestamp : t -> query_set:Query_set.t -> query_index:int -> unit
  val set_label : t -> label:string -> unit
end

module Queue : sig
  type t

  val write_buffer
    :  t
    -> buffer:Buffer.t
    -> offset:int64
    -> data:(_, _, Bigarray.c_layout) Bigarray.Array1.t
    -> unit

  val write_texture
    :  t
    -> destination_texture:Texture.t
    -> destination_mip_level:int
    -> destination_origin_x:int
    -> destination_origin_y:int
    -> destination_origin_z:int
    -> destination_aspect:Texture_aspect.t
    -> data_layout_offset:int64
    -> data_layout_bytes_per_row:int
    -> data_layout_rows_per_image:int
    -> write_size_width:int
    -> write_size_height:int
    -> write_size_depth_or_array_layers:int
    -> data:(_, _, Bigarray.c_layout) Bigarray.Array1.t
    -> unit
    -> unit

  val release : t -> unit
  val submit : t -> commands:Command_buffer.t list -> unit
  val set_label : t -> label:string -> unit
end

module Device : sig
  type t

  (** Create a shader module from WGSL source code *)
  val create_shader_module : t -> ?label:string -> wgsl:string -> unit -> Shader_module.t

  (* create_compute_pipeline and create_render_pipeline are now auto-generated *)

  (** Create a bind group layout for a single storage buffer *)
  val create_bind_group_layout_for_storage_buffer
    :  t
    -> ?label:string
    -> binding:int
    -> ?read_only:bool
    -> unit
    -> Bind_group_layout.t

  (** Create a bind group layout for a single uniform buffer *)
  val create_bind_group_layout_for_uniform_buffer
    :  t
    -> ?label:string
    -> binding:int
    -> visibility:Shader_stage.Item.t list
    -> unit
    -> Bind_group_layout.t

  (* AUTO-GENERATED DEVICE METHOD SIGNATURES INJECTED HERE *)
  type limits =
    { max_texture_dimension_1D : int
    ; max_texture_dimension_2D : int
    ; max_texture_dimension_3D : int
    ; max_texture_array_layers : int
    ; max_bind_groups : int
    ; max_bind_groups_plus_vertex_buffers : int
    ; max_bindings_per_bind_group : int
    ; max_dynamic_uniform_buffers_per_pipeline_layout : int
    ; max_dynamic_storage_buffers_per_pipeline_layout : int
    ; max_sampled_textures_per_shader_stage : int
    ; max_samplers_per_shader_stage : int
    ; max_storage_buffers_per_shader_stage : int
    ; max_storage_textures_per_shader_stage : int
    ; max_uniform_buffers_per_shader_stage : int
    ; max_uniform_buffer_binding_size : int64
    ; max_storage_buffer_binding_size : int64
    ; min_uniform_buffer_offset_alignment : int
    ; min_storage_buffer_offset_alignment : int
    ; max_vertex_buffers : int
    ; max_buffer_size : int64
    ; max_vertex_attributes : int
    ; max_vertex_buffer_array_stride : int
    ; max_inter_stage_shader_variables : int
    ; max_color_attachments : int
    ; max_color_attachment_bytes_per_sample : int
    ; max_compute_workgroup_storage_size : int
    ; max_compute_invocations_per_workgroup : int
    ; max_compute_workgroup_size_x : int
    ; max_compute_workgroup_size_y : int
    ; max_compute_workgroup_size_z : int
    ; max_compute_workgroups_per_dimension : int
    }

  val release : t -> unit

  val create_bind_group
    :  t
    -> ?label:string
    -> layout:Bind_group_layout.t
    -> ?entries:Bind_group_entry.t list
    -> unit
    -> Bind_group.t

  val create_bind_group_layout
    :  t
    -> ?label:string
    -> ?entries:Bind_group_layout_entry.t list
    -> unit
    -> Bind_group_layout.t

  val create_buffer
    :  t
    -> ?label:string
    -> usage:Buffer_usage.Item.t list
    -> size:int64
    -> mapped_at_creation:bool
    -> unit
    -> Buffer.t

  val create_command_encoder : t -> ?label:string -> unit -> Command_encoder.t

  val create_compute_pipeline
    :  t
    -> ?label:string
    -> ?layout:Pipeline_layout.t
    -> compute_module:Shader_module.t
    -> compute_entry_point:string
    -> ?compute_constants:Constant_entry.t list
    -> unit
    -> Compute_pipeline.t

  val create_pipeline_layout
    :  t
    -> ?label:string
    -> ?bind_group_layouts:Bind_group_layout.t list
    -> unit
    -> Pipeline_layout.t

  val create_query_set
    :  t
    -> ?label:string
    -> type_:Query_type.t
    -> count:int
    -> unit
    -> Query_set.t

  val create_render_bundle_encoder
    :  t
    -> ?label:string
    -> ?color_formats:Texture_format.t list
    -> depth_stencil_format:Texture_format.t
    -> sample_count:int
    -> depth_read_only:bool
    -> stencil_read_only:bool
    -> unit
    -> Render_bundle_encoder.t

  val create_render_pipeline
    :  t
    -> ?label:string
    -> ?layout:Pipeline_layout.t
    -> vertex_module:Shader_module.t
    -> vertex_entry_point:string
    -> ?vertex_constants:Constant_entry.t list
    -> ?vertex_buffers:Vertex_buffer_layout.t list
    -> primitive_topology:Primitive_topology.t
    -> primitive_strip_index_format:Index_format.t
    -> primitive_front_face:Front_face.t
    -> primitive_cull_mode:Cull_mode.t
    -> primitive_unclipped_depth:bool
    -> ?depth_stencil:Depth_stencil_state.t
    -> multisample_count:int
    -> multisample_mask:int
    -> multisample_alpha_to_coverage_enabled:bool
    -> ?fragment:Fragment_state.t
    -> unit
    -> Render_pipeline.t

  val create_sampler
    :  t
    -> ?label:string
    -> address_mode_u:Address_mode.t
    -> address_mode_v:Address_mode.t
    -> address_mode_w:Address_mode.t
    -> mag_filter:Filter_mode.t
    -> min_filter:Filter_mode.t
    -> mipmap_filter:Mipmap_filter_mode.t
    -> lod_min_clamp:float
    -> lod_max_clamp:float
    -> compare:Compare_function.t
    -> max_anisotropy:int
    -> unit
    -> Sampler.t

  val create_texture
    :  t
    -> ?label:string
    -> usage:Texture_usage.Item.t list
    -> dimension:Texture_dimension.t
    -> size_width:int
    -> size_height:int
    -> size_depth_or_array_layers:int
    -> format:Texture_format.t
    -> mip_level_count:int
    -> sample_count:int
    -> ?view_formats:Texture_format.t list
    -> unit
    -> Texture.t

  val destroy : t -> unit
  val get_limits : t -> limits
  val has_feature : t -> feature:Feature_name.t -> bool
  val get_queue : t -> Queue.t
  val push_error_scope : t -> filter:Error_filter.t -> unit
  val set_label : t -> label:string -> unit

  (** Poll the device for completed work *)
  val poll : t -> ?wait:bool -> unit -> unit
end

module Adapter : sig
  type t

  val get_info : t -> Adapter_info.t
  val request_device : t -> Device.t

  type limits =
    { max_texture_dimension_1D : int
    ; max_texture_dimension_2D : int
    ; max_texture_dimension_3D : int
    ; max_texture_array_layers : int
    ; max_bind_groups : int
    ; max_bind_groups_plus_vertex_buffers : int
    ; max_bindings_per_bind_group : int
    ; max_dynamic_uniform_buffers_per_pipeline_layout : int
    ; max_dynamic_storage_buffers_per_pipeline_layout : int
    ; max_sampled_textures_per_shader_stage : int
    ; max_samplers_per_shader_stage : int
    ; max_storage_buffers_per_shader_stage : int
    ; max_storage_textures_per_shader_stage : int
    ; max_uniform_buffers_per_shader_stage : int
    ; max_uniform_buffer_binding_size : int64
    ; max_storage_buffer_binding_size : int64
    ; min_uniform_buffer_offset_alignment : int
    ; min_storage_buffer_offset_alignment : int
    ; max_vertex_buffers : int
    ; max_buffer_size : int64
    ; max_vertex_attributes : int
    ; max_vertex_buffer_array_stride : int
    ; max_inter_stage_shader_variables : int
    ; max_color_attachments : int
    ; max_color_attachment_bytes_per_sample : int
    ; max_compute_workgroup_storage_size : int
    ; max_compute_invocations_per_workgroup : int
    ; max_compute_workgroup_size_x : int
    ; max_compute_workgroup_size_y : int
    ; max_compute_workgroup_size_z : int
    ; max_compute_workgroups_per_dimension : int
    }

  val release : t -> unit
  val get_limits : t -> limits
  val has_feature : t -> feature:Feature_name.t -> bool
end

module Surface : sig
  (** An object used to continuously present image data to the user, see @ref Surfaces for
      more details. *)

  type t

  (** Create a Surface from a low-level surface handle (for platform-specific surface
      creation) *)
  val of_low_level : Wgpu_low.surface -> t

  type surface_capabilities =
    { usages : Texture_usage.Item.t list
    ; formats : Texture_format.t list
    ; present_modes : Present_mode.t list
    ; alpha_modes : Composite_alpha_mode.t list
    }

  type surface_texture =
    { texture : Texture.t
    ; status : Surface_get_current_texture_status.t
    }

  val get_current_texture : t -> surface_texture

  (* get_capabilities not yet implemented - low-level array getters are stubs *)

  (* present, unconfigure, set_label, configure are auto-generated *)

  val release : t -> unit

  val configure
    :  t
    -> device:Device.t
    -> format:Texture_format.t
    -> usage:Texture_usage.Item.t list
    -> width:int
    -> height:int
    -> ?view_formats:Texture_format.t list
    -> alpha_mode:Composite_alpha_mode.t
    -> present_mode:Present_mode.t
    -> unit
    -> unit

  val present : t -> Status.t
  val unconfigure : t -> unit
  val set_label : t -> label:string -> unit
end

module Instance : sig
  type t

  val create : unit -> t

  (** Get the low-level instance handle for use with platform-specific surface creation *)
  val to_low_level : t -> Wgpu_low.instance

  val request_adapter
    :  t
    -> ?power_preference:Power_preference.t
    -> ?backend_type:Backend_type.t
    -> unit
    -> Adapter.t

  val release : t -> unit
  val has_WGSL_language_feature : t -> feature:Wgsl_language_feature_name.t -> bool
  val process_events : t -> unit
end

(** Finish recording commands and get a command buffer *)
val finish : Command_encoder.t -> ?label:string -> unit -> Command_buffer.t

(** Set a bind group on a compute pass encoder *)
val set_bind_group
  :  Compute_pass_encoder.t
  -> index:int
  -> bind_group:Bind_group.t
  -> unit

(** Set a bind group on a render pass encoder *)
val set_bind_group_render
  :  Render_pass_encoder.t
  -> index:int
  -> bind_group:Bind_group.t
  -> unit

(** Copy texture to buffer (for readback) *)
val copy_texture_to_buffer
  :  Command_encoder.t
  -> texture:Texture.t
  -> buffer:Buffer.t
  -> size:int * int
  -> bytes_per_row:int
  -> unit
  -> unit

(** Map a buffer for CPU access (synchronous) *)
val map_buffer
  :  Buffer.t
  -> mode:Map_mode.Item.t list
  -> offset:int64
  -> size:int64
  -> unit

(** Get mapped buffer data as a bigarray *)
val get_mapped_range
  :  Buffer.t
  -> offset:int64
  -> size:int64
  -> kind:('a, 'b) Bigarray.kind
  -> ('a, 'b, Bigarray.c_layout) Bigarray.Array1.t

(** Get const mapped buffer data as a bigarray (for read-only access) *)
val get_const_mapped_range
  :  Buffer.t
  -> offset:int64
  -> size:int64
  -> kind:('a, 'b) Bigarray.kind
  -> ('a, 'b, Bigarray.c_layout) Bigarray.Array1.t

(** Create a texture view from a texture *)
val create_texture_view
  :  Texture.t
  -> ?label:string
  -> ?format:Texture_format.t
  -> ?dimension:Texture_view_dimension.t
  -> ?aspect:Texture_aspect.t
  -> ?base_mip_level:int
  -> ?mip_level_count:int
  -> ?base_array_layer:int
  -> ?array_layer_count:int
  -> unit
  -> Texture_view.t
