/* Generated by gen_bindings - low-level C stubs */
#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/custom.h>
#include <caml/fail.h>
#include <caml/bigarray.h>
#include <string.h>
#include <stdlib.h>

#include "webgpu.h"
#include "wgpu.h"

