(* Generated by gen_bindings - high-level bitset signatures *)

module type S = sig
  module Item : sig
    type t

    val to_int : t -> int
    val all : t list
  end

  type t = int

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool
  val empty : t
  val all : t
  val union : t -> t -> t
  val inter : t -> t -> t
  val diff : t -> t -> t
  val to_int : t -> int
  val to_list : t -> Item.t list
  val list_to_int : Item.t list -> t
end

module Buffer_usage : sig
  module Item : sig
    type t = Wgpu_low.Buffer_usage.t =
      | None
      | Map_read
      | Map_write
      | Copy_src
      | Copy_dst
      | Index
      | Vertex
      | Uniform
      | Storage
      | Indirect
      | Query_resolve

    val to_int : t -> int
    val all : t list
  end

  include S with module Item := Item
end

module Color_write_mask : sig
  module Item : sig
    type t = Wgpu_low.Color_write_mask.t =
      | None
      | Red
      | Green
      | Blue
      | Alpha
      | All

    val to_int : t -> int
    val all : t list
  end

  include S with module Item := Item
end

module Map_mode : sig
  module Item : sig
    type t = Wgpu_low.Map_mode.t =
      | None
      | Read
      | Write

    val to_int : t -> int
    val all : t list
  end

  include S with module Item := Item
end

module Shader_stage : sig
  module Item : sig
    type t = Wgpu_low.Shader_stage.t =
      | None
      | Vertex
      | Fragment
      | Compute

    val to_int : t -> int
    val all : t list
  end

  include S with module Item := Item
end

module Texture_usage : sig
  module Item : sig
    type t = Wgpu_low.Texture_usage.t =
      | None
      | Copy_src
      | Copy_dst
      | Texture_binding
      | Storage_binding
      | Render_attachment

    val to_int : t -> int
    val all : t list
  end

  include S with module Item := Item
end
