(* Generated by gen_bindings - high-level bitset signatures *)

module type S = sig
  module Item : sig
    type t
  end

  type t

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool
end

module Buffer_usage : sig
  module Item : sig
    type t =
      | None
      | Map_read
      | Map_write
      | Copy_src
      | Copy_dst
      | Index
      | Vertex
      | Uniform
      | Storage
      | Indirect
      | Query_resolve
  end

  type t = int

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool

  (* Backwards compatibility alias *)
  val list_to_int : Item.t list -> t
end

module Color_write_mask : sig
  module Item : sig
    type t =
      | None
      | Red
      | Green
      | Blue
      | Alpha
      | All
  end

  type t = int

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool

  (* Backwards compatibility alias *)
  val list_to_int : Item.t list -> t
end

module Map_mode : sig
  module Item : sig
    type t =
      | None
      | Read
      | Write
  end

  type t = int

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool

  (* Backwards compatibility alias *)
  val list_to_int : Item.t list -> t
end

module Shader_stage : sig
  module Item : sig
    type t =
      | None
      | Vertex
      | Fragment
      | Compute
  end

  type t = int

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool

  (* Backwards compatibility alias *)
  val list_to_int : Item.t list -> t
end

module Texture_usage : sig
  module Item : sig
    type t =
      | None
      | Copy_src
      | Copy_dst
      | Texture_binding
      | Storage_binding
      | Render_attachment
  end

  type t = int

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool

  (* Backwards compatibility alias *)
  val list_to_int : Item.t list -> t
end
