(* Generated by gen_bindings - high-level bitset definitions *)

module type S = sig
  module Item : sig
    type t

    val to_int : t -> int
    val all : t list
  end

  type t = int

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool
  val empty : t
  val all : t
  val union : t -> t -> t
  val inter : t -> t -> t
  val diff : t -> t -> t
  val to_int : t -> int
  val to_list : t -> Item.t list
  val list_to_int : Item.t list -> t
end

module Buffer_usage_item = struct
  type t = Wgpu_low.Buffer_usage.t =
    | None
    | Map_read
    | Map_write
    | Copy_src
    | Copy_dst
    | Index
    | Vertex
    | Uniform
    | Storage
    | Indirect
    | Query_resolve

  let to_int = Wgpu_low.Buffer_usage.to_int

  let all =
    [ None
    ; Map_read
    ; Map_write
    ; Copy_src
    ; Copy_dst
    ; Index
    ; Vertex
    ; Uniform
    ; Storage
    ; Indirect
    ; Query_resolve
    ]
  ;;
end

module Buffer_usage = struct
  include Bitset_functor.Make (Buffer_usage_item)
  module Item = Buffer_usage_item
end

module Color_write_mask_item = struct
  type t = Wgpu_low.Color_write_mask.t =
    | None
    | Red
    | Green
    | Blue
    | Alpha
    | All

  let to_int = Wgpu_low.Color_write_mask.to_int
  let all = [ None; Red; Green; Blue; Alpha; All ]
end

module Color_write_mask = struct
  include Bitset_functor.Make (Color_write_mask_item)
  module Item = Color_write_mask_item
end

module Map_mode_item = struct
  type t = Wgpu_low.Map_mode.t =
    | None
    | Read
    | Write

  let to_int = Wgpu_low.Map_mode.to_int
  let all = [ None; Read; Write ]
end

module Map_mode = struct
  include Bitset_functor.Make (Map_mode_item)
  module Item = Map_mode_item
end

module Shader_stage_item = struct
  type t = Wgpu_low.Shader_stage.t =
    | None
    | Vertex
    | Fragment
    | Compute

  let to_int = Wgpu_low.Shader_stage.to_int
  let all = [ None; Vertex; Fragment; Compute ]
end

module Shader_stage = struct
  include Bitset_functor.Make (Shader_stage_item)
  module Item = Shader_stage_item
end

module Texture_usage_item = struct
  type t = Wgpu_low.Texture_usage.t =
    | None
    | Copy_src
    | Copy_dst
    | Texture_binding
    | Storage_binding
    | Render_attachment

  let to_int = Wgpu_low.Texture_usage.to_int

  let all =
    [ None; Copy_src; Copy_dst; Texture_binding; Storage_binding; Render_attachment ]
  ;;
end

module Texture_usage = struct
  include Bitset_functor.Make (Texture_usage_item)
  module Item = Texture_usage_item
end
