(* Generated by gen_bindings - high-level bitset definitions *)

module type S = sig
  module Item : sig
    type t
  end

  type t

  val singleton : Item.t -> t
  val of_list : Item.t list -> t
  val is_member : t -> Item.t -> bool
end

module Buffer_usage = struct
  module Item = struct
    type t = Wgpu_low.Buffer_usage.t =
      | None
      | Map_read
      | Map_write
      | Copy_src
      | Copy_dst
      | Index
      | Vertex
      | Uniform
      | Storage
      | Indirect
      | Query_resolve

    let to_int = Wgpu_low.Buffer_usage.to_int
  end

  type t = int

  let singleton item = Item.to_int item
  let of_list items = List.fold_left (fun acc item -> acc lor Item.to_int item) 0 items
  let is_member t item = t land Item.to_int item <> 0

  (* Backwards compatibility alias *)
  let list_to_int = of_list
end

module Color_write_mask = struct
  module Item = struct
    type t = Wgpu_low.Color_write_mask.t =
      | None
      | Red
      | Green
      | Blue
      | Alpha
      | All

    let to_int = Wgpu_low.Color_write_mask.to_int
  end

  type t = int

  let singleton item = Item.to_int item
  let of_list items = List.fold_left (fun acc item -> acc lor Item.to_int item) 0 items
  let is_member t item = t land Item.to_int item <> 0

  (* Backwards compatibility alias *)
  let list_to_int = of_list
end

module Map_mode = struct
  module Item = struct
    type t = Wgpu_low.Map_mode.t =
      | None
      | Read
      | Write

    let to_int = Wgpu_low.Map_mode.to_int
  end

  type t = int

  let singleton item = Item.to_int item
  let of_list items = List.fold_left (fun acc item -> acc lor Item.to_int item) 0 items
  let is_member t item = t land Item.to_int item <> 0

  (* Backwards compatibility alias *)
  let list_to_int = of_list
end

module Shader_stage = struct
  module Item = struct
    type t = Wgpu_low.Shader_stage.t =
      | None
      | Vertex
      | Fragment
      | Compute

    let to_int = Wgpu_low.Shader_stage.to_int
  end

  type t = int

  let singleton item = Item.to_int item
  let of_list items = List.fold_left (fun acc item -> acc lor Item.to_int item) 0 items
  let is_member t item = t land Item.to_int item <> 0

  (* Backwards compatibility alias *)
  let list_to_int = of_list
end

module Texture_usage = struct
  module Item = struct
    type t = Wgpu_low.Texture_usage.t =
      | None
      | Copy_src
      | Copy_dst
      | Texture_binding
      | Storage_binding
      | Render_attachment

    let to_int = Wgpu_low.Texture_usage.to_int
  end

  type t = int

  let singleton item = Item.to_int item
  let of_list items = List.fold_left (fun acc item -> acc lor Item.to_int item) 0 items
  let is_member t item = t land Item.to_int item <> 0

  (* Backwards compatibility alias *)
  let list_to_int = of_list
end
