(* Generated by gen_bindings - high-level enum signatures *)

module type S = sig
  type t

  val to_int : t -> int
  val of_int : int -> t
  val to_string : t -> string
end

module Adapter_type : sig
  include module type of Wgpu_low.Adapter_type

  val to_string : t -> string
end

module Address_mode : sig
  include module type of Wgpu_low.Address_mode

  val to_string : t -> string
end

module Backend_type : sig
  include module type of Wgpu_low.Backend_type

  val to_string : t -> string
end

module Blend_factor : sig
  include module type of Wgpu_low.Blend_factor

  val to_string : t -> string
end

module Blend_operation : sig
  include module type of Wgpu_low.Blend_operation

  val to_string : t -> string
end

module Buffer_binding_type : sig
  include module type of Wgpu_low.Buffer_binding_type

  val to_string : t -> string
end

module Buffer_map_state : sig
  include module type of Wgpu_low.Buffer_map_state

  val to_string : t -> string
end

module Callback_mode : sig
  (** The callback mode controls how a callback for an asynchronous operation may be
      fired. See \@ref Asynchronous-Operations for how these are used. *)
  include module type of Wgpu_low.Callback_mode

  val to_string : t -> string
end

module Compare_function : sig
  include module type of Wgpu_low.Compare_function

  val to_string : t -> string
end

module Compilation_info_request_status : sig
  include module type of Wgpu_low.Compilation_info_request_status

  val to_string : t -> string
end

module Compilation_message_type : sig
  include module type of Wgpu_low.Compilation_message_type

  val to_string : t -> string
end

module Composite_alpha_mode : sig
  (** Describes how frames are composited with other contents on the screen when
      `::wgpuSurfacePresent` is called. *)
  include module type of Wgpu_low.Composite_alpha_mode

  val to_string : t -> string
end

module Create_pipeline_async_status : sig
  include module type of Wgpu_low.Create_pipeline_async_status

  val to_string : t -> string
end

module Cull_mode : sig
  include module type of Wgpu_low.Cull_mode

  val to_string : t -> string
end

module Device_lost_reason : sig
  include module type of Wgpu_low.Device_lost_reason

  val to_string : t -> string
end

module Error_filter : sig
  include module type of Wgpu_low.Error_filter

  val to_string : t -> string
end

module Error_type : sig
  include module type of Wgpu_low.Error_type

  val to_string : t -> string
end

module Feature_level : sig
  (** See \@ref WGPURequestAdapterOptions::featureLevel. *)
  include module type of Wgpu_low.Feature_level

  val to_string : t -> string
end

module Feature_name : sig
  include module type of Wgpu_low.Feature_name

  val to_string : t -> string
end

module Filter_mode : sig
  include module type of Wgpu_low.Filter_mode

  val to_string : t -> string
end

module Front_face : sig
  include module type of Wgpu_low.Front_face

  val to_string : t -> string
end

module Index_format : sig
  include module type of Wgpu_low.Index_format

  val to_string : t -> string
end

module Load_op : sig
  include module type of Wgpu_low.Load_op

  val to_string : t -> string
end

module Map_async_status : sig
  include module type of Wgpu_low.Map_async_status

  val to_string : t -> string
end

module Mipmap_filter_mode : sig
  include module type of Wgpu_low.Mipmap_filter_mode

  val to_string : t -> string
end

module Optional_bool : sig
  include module type of Wgpu_low.Optional_bool

  val to_string : t -> string
end

module Pop_error_scope_status : sig
  include module type of Wgpu_low.Pop_error_scope_status

  val to_string : t -> string
end

module Power_preference : sig
  include module type of Wgpu_low.Power_preference

  val to_string : t -> string
end

module Present_mode : sig
  (** Describes when and in which order frames are presented on the screen when
      `::wgpuSurfacePresent` is called. *)
  include module type of Wgpu_low.Present_mode

  val to_string : t -> string
end

module Primitive_topology : sig
  include module type of Wgpu_low.Primitive_topology

  val to_string : t -> string
end

module Query_type : sig
  include module type of Wgpu_low.Query_type

  val to_string : t -> string
end

module Queue_work_done_status : sig
  include module type of Wgpu_low.Queue_work_done_status

  val to_string : t -> string
end

module Request_adapter_status : sig
  include module type of Wgpu_low.Request_adapter_status

  val to_string : t -> string
end

module Request_device_status : sig
  include module type of Wgpu_low.Request_device_status

  val to_string : t -> string
end

module S_type : sig
  include module type of Wgpu_low.S_type

  val to_string : t -> string
end

module Sampler_binding_type : sig
  include module type of Wgpu_low.Sampler_binding_type

  val to_string : t -> string
end

module Status : sig
  (** Status code returned (synchronously) from many operations. Generally indicates an
      invalid input like an unknown enum value or \@ref OutStructChainError. Read the
      function's documentation for specific error conditions. *)
  include module type of Wgpu_low.Status

  val to_string : t -> string
end

module Stencil_operation : sig
  include module type of Wgpu_low.Stencil_operation

  val to_string : t -> string
end

module Storage_texture_access : sig
  include module type of Wgpu_low.Storage_texture_access

  val to_string : t -> string
end

module Store_op : sig
  include module type of Wgpu_low.Store_op

  val to_string : t -> string
end

module Surface_get_current_texture_status : sig
  (** The status enum for `::wgpuSurfaceGetCurrentTexture`. *)
  include module type of Wgpu_low.Surface_get_current_texture_status

  val to_string : t -> string
end

module Texture_aspect : sig
  include module type of Wgpu_low.Texture_aspect

  val to_string : t -> string
end

module Texture_dimension : sig
  include module type of Wgpu_low.Texture_dimension

  val to_string : t -> string
end

module Texture_format : sig
  include module type of Wgpu_low.Texture_format

  val to_string : t -> string
end

module Texture_sample_type : sig
  include module type of Wgpu_low.Texture_sample_type

  val to_string : t -> string
end

module Texture_view_dimension : sig
  include module type of Wgpu_low.Texture_view_dimension

  val to_string : t -> string
end

module Vertex_format : sig
  include module type of Wgpu_low.Vertex_format

  val to_string : t -> string
end

module Vertex_step_mode : sig
  include module type of Wgpu_low.Vertex_step_mode

  val to_string : t -> string
end

module Wait_status : sig
  (** Status returned from a call to ::wgpuInstanceWaitAny. *)
  include module type of Wgpu_low.Wait_status

  val to_string : t -> string
end

module Wgsl_language_feature_name : sig
  include module type of Wgpu_low.Wgsl_language_feature_name

  val to_string : t -> string
end
