(* Generated by gen_bindings - high-level enum signatures *)

module type S = sig
  type t

  val to_int : t -> int
  val of_int : int -> t
  val to_string : t -> string
end

module Adapter_type : sig
  type t =
    | Discrete_gpu
    | Integrated_gpu
    | Cpu
    | Unknown

  include S with type t := t
end

module Address_mode : sig
  type t =
    | Undefined
    | Clamp_to_edge
    | Repeat
    | Mirror_repeat

  include S with type t := t
end

module Backend_type : sig
  type t =
    | Undefined
    | Null
    | Webgpu
    | D3d11
    | D3d12
    | Metal
    | Vulkan
    | Opengl
    | Opengles

  include S with type t := t
end

module Blend_factor : sig
  type t =
    | Undefined
    | Zero
    | One
    | Src
    | One_minus_src
    | Src_alpha
    | One_minus_src_alpha
    | Dst
    | One_minus_dst
    | Dst_alpha
    | One_minus_dst_alpha
    | Src_alpha_saturated
    | Constant
    | One_minus_constant
    | Src1
    | One_minus_src1
    | Src1_alpha
    | One_minus_src1_alpha

  include S with type t := t
end

module Blend_operation : sig
  type t =
    | Undefined
    | Add
    | Subtract
    | Reverse_subtract
    | Min
    | Max

  include S with type t := t
end

module Buffer_binding_type : sig
  type t =
    | Binding_not_used
    | Undefined
    | Uniform
    | Storage
    | Read_only_storage

  include S with type t := t
end

module Buffer_map_state : sig
  type t =
    | Unmapped
    | Pending
    | Mapped

  include S with type t := t
end

module Callback_mode : sig
  (** The callback mode controls how a callback for an asynchronous operation may be
      fired. See \@ref Asynchronous-Operations for how these are used. *)
  type t =
    | Wait_any_only
    | Allow_process_events
    | Allow_spontaneous

  include S with type t := t
end

module Compare_function : sig
  type t =
    | Undefined
    | Never
    | Less
    | Equal
    | Less_equal
    | Greater
    | Not_equal
    | Greater_equal
    | Always

  include S with type t := t
end

module Compilation_info_request_status : sig
  type t =
    | Success
    | Instance_dropped
    | Error
    | Unknown

  include S with type t := t
end

module Compilation_message_type : sig
  type t =
    | Error
    | Warning
    | Info

  include S with type t := t
end

module Composite_alpha_mode : sig
  (** Describes how frames are composited with other contents on the screen when
      `::wgpuSurfacePresent` is called. *)
  type t =
    | Auto
    | Opaque
    | Premultiplied
    | Unpremultiplied
    | Inherit

  include S with type t := t
end

module Create_pipeline_async_status : sig
  type t =
    | Success
    | Instance_dropped
    | Validation_error
    | Internal_error
    | Unknown

  include S with type t := t
end

module Cull_mode : sig
  type t =
    | Undefined
    | None
    | Front
    | Back

  include S with type t := t
end

module Device_lost_reason : sig
  type t =
    | Unknown
    | Destroyed
    | Instance_dropped
    | Failed_creation

  include S with type t := t
end

module Error_filter : sig
  type t =
    | Validation
    | Out_of_memory
    | Internal

  include S with type t := t
end

module Error_type : sig
  type t =
    | No_error
    | Validation
    | Out_of_memory
    | Internal
    | Unknown

  include S with type t := t
end

module Feature_level : sig
  (** See \@ref WGPURequestAdapterOptions::featureLevel. *)
  type t =
    | Compatibility
    | Core

  include S with type t := t
end

module Feature_name : sig
  type t =
    | Undefined
    | Depth_clip_control
    | Depth32_float_stencil8
    | Timestamp_query
    | Texture_compression_bc
    | Texture_compression_bc_sliced_3d
    | Texture_compression_etc2
    | Texture_compression_astc
    | Texture_compression_astc_sliced_3d
    | Indirect_first_instance
    | Shader_f16
    | Rg11b10_ufloat_renderable
    | Bgra8_unorm_storage
    | Float32_filterable
    | Float32_blendable
    | Clip_distances
    | Dual_source_blending

  include S with type t := t
end

module Filter_mode : sig
  type t =
    | Undefined
    | Nearest
    | Linear

  include S with type t := t
end

module Front_face : sig
  type t =
    | Undefined
    | Ccw
    | Cw

  include S with type t := t
end

module Index_format : sig
  type t =
    | Undefined
    | Uint16
    | Uint32

  include S with type t := t
end

module Load_op : sig
  type t =
    | Undefined
    | Load
    | Clear

  include S with type t := t
end

module Map_async_status : sig
  type t =
    | Success
    | Instance_dropped
    | Error
    | Aborted
    | Unknown

  include S with type t := t
end

module Mipmap_filter_mode : sig
  type t =
    | Undefined
    | Nearest
    | Linear

  include S with type t := t
end

module Optional_bool : sig
  type t =
    | False
    | True
    | Undefined

  include S with type t := t
end

module Pop_error_scope_status : sig
  type t =
    | Success
    | Instance_dropped
    | Empty_stack

  include S with type t := t
end

module Power_preference : sig
  type t =
    | Undefined
    | Low_power
    | High_performance

  include S with type t := t
end

module Present_mode : sig
  (** Describes when and in which order frames are presented on the screen when
      `::wgpuSurfacePresent` is called. *)
  type t =
    | Undefined
    | Fifo
    | Fifo_relaxed
    | Immediate
    | Mailbox

  include S with type t := t
end

module Primitive_topology : sig
  type t =
    | Undefined
    | Point_list
    | Line_list
    | Line_strip
    | Triangle_list
    | Triangle_strip

  include S with type t := t
end

module Query_type : sig
  type t =
    | Occlusion
    | Timestamp

  include S with type t := t
end

module Queue_work_done_status : sig
  type t =
    | Success
    | Instance_dropped
    | Error
    | Unknown

  include S with type t := t
end

module Request_adapter_status : sig
  type t =
    | Success
    | Instance_dropped
    | Unavailable
    | Error
    | Unknown

  include S with type t := t
end

module Request_device_status : sig
  type t =
    | Success
    | Instance_dropped
    | Error
    | Unknown

  include S with type t := t
end

module S_type : sig
  type t =
    | Shader_source_spirv
    | Shader_source_wgsl
    | Render_pass_max_draw_count
    | Surface_source_metal_layer
    | Surface_source_windows_hwnd
    | Surface_source_xlib_window
    | Surface_source_wayland_surface
    | Surface_source_android_native_window
    | Surface_source_xcb_window

  include S with type t := t
end

module Sampler_binding_type : sig
  type t =
    | Binding_not_used
    | Undefined
    | Filtering
    | Non_filtering
    | Comparison

  include S with type t := t
end

module Status : sig
  (** Status code returned (synchronously) from many operations. Generally indicates an
      invalid input like an unknown enum value or \@ref OutStructChainError. Read the
      function's documentation for specific error conditions. *)
  type t =
    | Success
    | Error

  include S with type t := t
end

module Stencil_operation : sig
  type t =
    | Undefined
    | Keep
    | Zero
    | Replace
    | Invert
    | Increment_clamp
    | Decrement_clamp
    | Increment_wrap
    | Decrement_wrap

  include S with type t := t
end

module Storage_texture_access : sig
  type t =
    | Binding_not_used
    | Undefined
    | Write_only
    | Read_only
    | Read_write

  include S with type t := t
end

module Store_op : sig
  type t =
    | Undefined
    | Store
    | Discard

  include S with type t := t
end

module Surface_get_current_texture_status : sig
  (** The status enum for `::wgpuSurfaceGetCurrentTexture`. *)
  type t =
    | Success_optimal
    | Success_suboptimal
    | Timeout
    | Outdated
    | Lost
    | Out_of_memory
    | Device_lost
    | Error

  include S with type t := t
end

module Texture_aspect : sig
  type t =
    | Undefined
    | All
    | Stencil_only
    | Depth_only

  include S with type t := t
end

module Texture_dimension : sig
  type t =
    | Undefined
    | N1d
    | N2d
    | N3d

  include S with type t := t
end

module Texture_format : sig
  type t =
    | Undefined
    | R8_unorm
    | R8_snorm
    | R8_uint
    | R8_sint
    | R16_uint
    | R16_sint
    | R16_float
    | Rg8_unorm
    | Rg8_snorm
    | Rg8_uint
    | Rg8_sint
    | R32_float
    | R32_uint
    | R32_sint
    | Rg16_uint
    | Rg16_sint
    | Rg16_float
    | Rgba8_unorm
    | Rgba8_unorm_srgb
    | Rgba8_snorm
    | Rgba8_uint
    | Rgba8_sint
    | Bgra8_unorm
    | Bgra8_unorm_srgb
    | Rgb10_a2_uint
    | Rgb10_a2_unorm
    | Rg11_b10_ufloat
    | Rgb9_e5_ufloat
    | Rg32_float
    | Rg32_uint
    | Rg32_sint
    | Rgba16_uint
    | Rgba16_sint
    | Rgba16_float
    | Rgba32_float
    | Rgba32_uint
    | Rgba32_sint
    | Stencil8
    | Depth16_unorm
    | Depth24_plus
    | Depth24_plus_stencil8
    | Depth32_float
    | Depth32_float_stencil8
    | Bc1_rgba_unorm
    | Bc1_rgba_unorm_srgb
    | Bc2_rgba_unorm
    | Bc2_rgba_unorm_srgb
    | Bc3_rgba_unorm
    | Bc3_rgba_unorm_srgb
    | Bc4_r_unorm
    | Bc4_r_snorm
    | Bc5_rg_unorm
    | Bc5_rg_snorm
    | Bc6h_rgb_ufloat
    | Bc6h_rgb_float
    | Bc7_rgba_unorm
    | Bc7_rgba_unorm_srgb
    | Etc2_rgb8_unorm
    | Etc2_rgb8_unorm_srgb
    | Etc2_rgb8a1_unorm
    | Etc2_rgb8a1_unorm_srgb
    | Etc2_rgba8_unorm
    | Etc2_rgba8_unorm_srgb
    | Eac_r11_unorm
    | Eac_r11_snorm
    | Eac_rg11_unorm
    | Eac_rg11_snorm
    | Astc_4x4_unorm
    | Astc_4x4_unorm_srgb
    | Astc_5x4_unorm
    | Astc_5x4_unorm_srgb
    | Astc_5x5_unorm
    | Astc_5x5_unorm_srgb
    | Astc_6x5_unorm
    | Astc_6x5_unorm_srgb
    | Astc_6x6_unorm
    | Astc_6x6_unorm_srgb
    | Astc_8x5_unorm
    | Astc_8x5_unorm_srgb
    | Astc_8x6_unorm
    | Astc_8x6_unorm_srgb
    | Astc_8x8_unorm
    | Astc_8x8_unorm_srgb
    | Astc_10x5_unorm
    | Astc_10x5_unorm_srgb
    | Astc_10x6_unorm
    | Astc_10x6_unorm_srgb
    | Astc_10x8_unorm
    | Astc_10x8_unorm_srgb
    | Astc_10x10_unorm
    | Astc_10x10_unorm_srgb
    | Astc_12x10_unorm
    | Astc_12x10_unorm_srgb
    | Astc_12x12_unorm
    | Astc_12x12_unorm_srgb

  include S with type t := t
end

module Texture_sample_type : sig
  type t =
    | Binding_not_used
    | Undefined
    | Float
    | Unfilterable_float
    | Depth
    | Sint
    | Uint

  include S with type t := t
end

module Texture_view_dimension : sig
  type t =
    | Undefined
    | N1d
    | N2d
    | N2d_array
    | Cube
    | Cube_array
    | N3d

  include S with type t := t
end

module Vertex_format : sig
  type t =
    | Uint8
    | Uint8x2
    | Uint8x4
    | Sint8
    | Sint8x2
    | Sint8x4
    | Unorm8
    | Unorm8x2
    | Unorm8x4
    | Snorm8
    | Snorm8x2
    | Snorm8x4
    | Uint16
    | Uint16x2
    | Uint16x4
    | Sint16
    | Sint16x2
    | Sint16x4
    | Unorm16
    | Unorm16x2
    | Unorm16x4
    | Snorm16
    | Snorm16x2
    | Snorm16x4
    | Float16
    | Float16x2
    | Float16x4
    | Float32
    | Float32x2
    | Float32x3
    | Float32x4
    | Uint32
    | Uint32x2
    | Uint32x3
    | Uint32x4
    | Sint32
    | Sint32x2
    | Sint32x3
    | Sint32x4
    | Unorm10__10__10__2
    | Unorm8x4_b_g_r_a

  include S with type t := t
end

module Vertex_step_mode : sig
  type t =
    | Vertex_buffer_not_used
    | Undefined
    | Vertex
    | Instance

  include S with type t := t
end

module Wait_status : sig
  (** Status returned from a call to ::wgpuInstanceWaitAny. *)
  type t =
    | Success
    | Timed_out
    | Unsupported_timeout
    | Unsupported_count
    | Unsupported_mixed_sources

  include S with type t := t
end

module Wgsl_language_feature_name : sig
  type t =
    | Readonly_and_readwrite_storage_textures
    | Packed4x8_integer_dot_product
    | Unrestricted_pointer_parameters
    | Pointer_composite_access

  include S with type t := t
end
