(* Generated by gen_bindings - high-level enum definitions *)

module type S = sig
  type t

  val to_int : t -> int
  val of_int : int -> t
  val to_string : t -> string
end

module Adapter_type = struct
  include Wgpu_low.Adapter_type

  let to_string = function
    | Discrete_gpu -> "Discrete_gpu"
    | Integrated_gpu -> "Integrated_gpu"
    | Cpu -> "Cpu"
    | Unknown -> "Unknown"
  ;;
end

module Address_mode = struct
  include Wgpu_low.Address_mode

  let to_string = function
    | Undefined -> "Undefined"
    | Clamp_to_edge -> "Clamp_to_edge"
    | Repeat -> "Repeat"
    | Mirror_repeat -> "Mirror_repeat"
  ;;
end

module Backend_type = struct
  include Wgpu_low.Backend_type

  let to_string = function
    | Undefined -> "Undefined"
    | Null -> "Null"
    | Webgpu -> "Webgpu"
    | D3d11 -> "D3d11"
    | D3d12 -> "D3d12"
    | Metal -> "Metal"
    | Vulkan -> "Vulkan"
    | Opengl -> "Opengl"
    | Opengles -> "Opengles"
  ;;
end

module Blend_factor = struct
  include Wgpu_low.Blend_factor

  let to_string = function
    | Undefined -> "Undefined"
    | Zero -> "Zero"
    | One -> "One"
    | Src -> "Src"
    | One_minus_src -> "One_minus_src"
    | Src_alpha -> "Src_alpha"
    | One_minus_src_alpha -> "One_minus_src_alpha"
    | Dst -> "Dst"
    | One_minus_dst -> "One_minus_dst"
    | Dst_alpha -> "Dst_alpha"
    | One_minus_dst_alpha -> "One_minus_dst_alpha"
    | Src_alpha_saturated -> "Src_alpha_saturated"
    | Constant -> "Constant"
    | One_minus_constant -> "One_minus_constant"
    | Src1 -> "Src1"
    | One_minus_src1 -> "One_minus_src1"
    | Src1_alpha -> "Src1_alpha"
    | One_minus_src1_alpha -> "One_minus_src1_alpha"
  ;;
end

module Blend_operation = struct
  include Wgpu_low.Blend_operation

  let to_string = function
    | Undefined -> "Undefined"
    | Add -> "Add"
    | Subtract -> "Subtract"
    | Reverse_subtract -> "Reverse_subtract"
    | Min -> "Min"
    | Max -> "Max"
  ;;
end

module Buffer_binding_type = struct
  include Wgpu_low.Buffer_binding_type

  let to_string = function
    | Binding_not_used -> "Binding_not_used"
    | Undefined -> "Undefined"
    | Uniform -> "Uniform"
    | Storage -> "Storage"
    | Read_only_storage -> "Read_only_storage"
  ;;
end

module Buffer_map_state = struct
  include Wgpu_low.Buffer_map_state

  let to_string = function
    | Unmapped -> "Unmapped"
    | Pending -> "Pending"
    | Mapped -> "Mapped"
  ;;
end

module Callback_mode = struct
  include Wgpu_low.Callback_mode

  let to_string = function
    | Wait_any_only -> "Wait_any_only"
    | Allow_process_events -> "Allow_process_events"
    | Allow_spontaneous -> "Allow_spontaneous"
  ;;
end

module Compare_function = struct
  include Wgpu_low.Compare_function

  let to_string = function
    | Undefined -> "Undefined"
    | Never -> "Never"
    | Less -> "Less"
    | Equal -> "Equal"
    | Less_equal -> "Less_equal"
    | Greater -> "Greater"
    | Not_equal -> "Not_equal"
    | Greater_equal -> "Greater_equal"
    | Always -> "Always"
  ;;
end

module Compilation_info_request_status = struct
  include Wgpu_low.Compilation_info_request_status

  let to_string = function
    | Success -> "Success"
    | Instance_dropped -> "Instance_dropped"
    | Error -> "Error"
    | Unknown -> "Unknown"
  ;;
end

module Compilation_message_type = struct
  include Wgpu_low.Compilation_message_type

  let to_string = function
    | Error -> "Error"
    | Warning -> "Warning"
    | Info -> "Info"
  ;;
end

module Composite_alpha_mode = struct
  include Wgpu_low.Composite_alpha_mode

  let to_string = function
    | Auto -> "Auto"
    | Opaque -> "Opaque"
    | Premultiplied -> "Premultiplied"
    | Unpremultiplied -> "Unpremultiplied"
    | Inherit -> "Inherit"
  ;;
end

module Create_pipeline_async_status = struct
  include Wgpu_low.Create_pipeline_async_status

  let to_string = function
    | Success -> "Success"
    | Instance_dropped -> "Instance_dropped"
    | Validation_error -> "Validation_error"
    | Internal_error -> "Internal_error"
    | Unknown -> "Unknown"
  ;;
end

module Cull_mode = struct
  include Wgpu_low.Cull_mode

  let to_string = function
    | Undefined -> "Undefined"
    | None -> "None"
    | Front -> "Front"
    | Back -> "Back"
  ;;
end

module Device_lost_reason = struct
  include Wgpu_low.Device_lost_reason

  let to_string = function
    | Unknown -> "Unknown"
    | Destroyed -> "Destroyed"
    | Instance_dropped -> "Instance_dropped"
    | Failed_creation -> "Failed_creation"
  ;;
end

module Error_filter = struct
  include Wgpu_low.Error_filter

  let to_string = function
    | Validation -> "Validation"
    | Out_of_memory -> "Out_of_memory"
    | Internal -> "Internal"
  ;;
end

module Error_type = struct
  include Wgpu_low.Error_type

  let to_string = function
    | No_error -> "No_error"
    | Validation -> "Validation"
    | Out_of_memory -> "Out_of_memory"
    | Internal -> "Internal"
    | Unknown -> "Unknown"
  ;;
end

module Feature_level = struct
  include Wgpu_low.Feature_level

  let to_string = function
    | Compatibility -> "Compatibility"
    | Core -> "Core"
  ;;
end

module Feature_name = struct
  include Wgpu_low.Feature_name

  let to_string = function
    | Undefined -> "Undefined"
    | Depth_clip_control -> "Depth_clip_control"
    | Depth32_float_stencil8 -> "Depth32_float_stencil8"
    | Timestamp_query -> "Timestamp_query"
    | Texture_compression_bc -> "Texture_compression_bc"
    | Texture_compression_bc_sliced_3d -> "Texture_compression_bc_sliced_3d"
    | Texture_compression_etc2 -> "Texture_compression_etc2"
    | Texture_compression_astc -> "Texture_compression_astc"
    | Texture_compression_astc_sliced_3d -> "Texture_compression_astc_sliced_3d"
    | Indirect_first_instance -> "Indirect_first_instance"
    | Shader_f16 -> "Shader_f16"
    | Rg11b10_ufloat_renderable -> "Rg11b10_ufloat_renderable"
    | Bgra8_unorm_storage -> "Bgra8_unorm_storage"
    | Float32_filterable -> "Float32_filterable"
    | Float32_blendable -> "Float32_blendable"
    | Clip_distances -> "Clip_distances"
    | Dual_source_blending -> "Dual_source_blending"
  ;;
end

module Filter_mode = struct
  include Wgpu_low.Filter_mode

  let to_string = function
    | Undefined -> "Undefined"
    | Nearest -> "Nearest"
    | Linear -> "Linear"
  ;;
end

module Front_face = struct
  include Wgpu_low.Front_face

  let to_string = function
    | Undefined -> "Undefined"
    | Ccw -> "Ccw"
    | Cw -> "Cw"
  ;;
end

module Index_format = struct
  include Wgpu_low.Index_format

  let to_string = function
    | Undefined -> "Undefined"
    | Uint16 -> "Uint16"
    | Uint32 -> "Uint32"
  ;;
end

module Load_op = struct
  include Wgpu_low.Load_op

  let to_string = function
    | Undefined -> "Undefined"
    | Load -> "Load"
    | Clear -> "Clear"
  ;;
end

module Map_async_status = struct
  include Wgpu_low.Map_async_status

  let to_string = function
    | Success -> "Success"
    | Instance_dropped -> "Instance_dropped"
    | Error -> "Error"
    | Aborted -> "Aborted"
    | Unknown -> "Unknown"
  ;;
end

module Mipmap_filter_mode = struct
  include Wgpu_low.Mipmap_filter_mode

  let to_string = function
    | Undefined -> "Undefined"
    | Nearest -> "Nearest"
    | Linear -> "Linear"
  ;;
end

module Optional_bool = struct
  include Wgpu_low.Optional_bool

  let to_string = function
    | False -> "False"
    | True -> "True"
    | Undefined -> "Undefined"
  ;;
end

module Pop_error_scope_status = struct
  include Wgpu_low.Pop_error_scope_status

  let to_string = function
    | Success -> "Success"
    | Instance_dropped -> "Instance_dropped"
    | Empty_stack -> "Empty_stack"
  ;;
end

module Power_preference = struct
  include Wgpu_low.Power_preference

  let to_string = function
    | Undefined -> "Undefined"
    | Low_power -> "Low_power"
    | High_performance -> "High_performance"
  ;;
end

module Present_mode = struct
  include Wgpu_low.Present_mode

  let to_string = function
    | Undefined -> "Undefined"
    | Fifo -> "Fifo"
    | Fifo_relaxed -> "Fifo_relaxed"
    | Immediate -> "Immediate"
    | Mailbox -> "Mailbox"
  ;;
end

module Primitive_topology = struct
  include Wgpu_low.Primitive_topology

  let to_string = function
    | Undefined -> "Undefined"
    | Point_list -> "Point_list"
    | Line_list -> "Line_list"
    | Line_strip -> "Line_strip"
    | Triangle_list -> "Triangle_list"
    | Triangle_strip -> "Triangle_strip"
  ;;
end

module Query_type = struct
  include Wgpu_low.Query_type

  let to_string = function
    | Occlusion -> "Occlusion"
    | Timestamp -> "Timestamp"
  ;;
end

module Queue_work_done_status = struct
  include Wgpu_low.Queue_work_done_status

  let to_string = function
    | Success -> "Success"
    | Instance_dropped -> "Instance_dropped"
    | Error -> "Error"
    | Unknown -> "Unknown"
  ;;
end

module Request_adapter_status = struct
  include Wgpu_low.Request_adapter_status

  let to_string = function
    | Success -> "Success"
    | Instance_dropped -> "Instance_dropped"
    | Unavailable -> "Unavailable"
    | Error -> "Error"
    | Unknown -> "Unknown"
  ;;
end

module Request_device_status = struct
  include Wgpu_low.Request_device_status

  let to_string = function
    | Success -> "Success"
    | Instance_dropped -> "Instance_dropped"
    | Error -> "Error"
    | Unknown -> "Unknown"
  ;;
end

module S_type = struct
  include Wgpu_low.S_type

  let to_string = function
    | Shader_source_spirv -> "Shader_source_spirv"
    | Shader_source_wgsl -> "Shader_source_wgsl"
    | Render_pass_max_draw_count -> "Render_pass_max_draw_count"
    | Surface_source_metal_layer -> "Surface_source_metal_layer"
    | Surface_source_windows_hwnd -> "Surface_source_windows_hwnd"
    | Surface_source_xlib_window -> "Surface_source_xlib_window"
    | Surface_source_wayland_surface -> "Surface_source_wayland_surface"
    | Surface_source_android_native_window -> "Surface_source_android_native_window"
    | Surface_source_xcb_window -> "Surface_source_xcb_window"
  ;;
end

module Sampler_binding_type = struct
  include Wgpu_low.Sampler_binding_type

  let to_string = function
    | Binding_not_used -> "Binding_not_used"
    | Undefined -> "Undefined"
    | Filtering -> "Filtering"
    | Non_filtering -> "Non_filtering"
    | Comparison -> "Comparison"
  ;;
end

module Status = struct
  include Wgpu_low.Status

  let to_string = function
    | Success -> "Success"
    | Error -> "Error"
  ;;
end

module Stencil_operation = struct
  include Wgpu_low.Stencil_operation

  let to_string = function
    | Undefined -> "Undefined"
    | Keep -> "Keep"
    | Zero -> "Zero"
    | Replace -> "Replace"
    | Invert -> "Invert"
    | Increment_clamp -> "Increment_clamp"
    | Decrement_clamp -> "Decrement_clamp"
    | Increment_wrap -> "Increment_wrap"
    | Decrement_wrap -> "Decrement_wrap"
  ;;
end

module Storage_texture_access = struct
  include Wgpu_low.Storage_texture_access

  let to_string = function
    | Binding_not_used -> "Binding_not_used"
    | Undefined -> "Undefined"
    | Write_only -> "Write_only"
    | Read_only -> "Read_only"
    | Read_write -> "Read_write"
  ;;
end

module Store_op = struct
  include Wgpu_low.Store_op

  let to_string = function
    | Undefined -> "Undefined"
    | Store -> "Store"
    | Discard -> "Discard"
  ;;
end

module Surface_get_current_texture_status = struct
  include Wgpu_low.Surface_get_current_texture_status

  let to_string = function
    | Success_optimal -> "Success_optimal"
    | Success_suboptimal -> "Success_suboptimal"
    | Timeout -> "Timeout"
    | Outdated -> "Outdated"
    | Lost -> "Lost"
    | Out_of_memory -> "Out_of_memory"
    | Device_lost -> "Device_lost"
    | Error -> "Error"
  ;;
end

module Texture_aspect = struct
  include Wgpu_low.Texture_aspect

  let to_string = function
    | Undefined -> "Undefined"
    | All -> "All"
    | Stencil_only -> "Stencil_only"
    | Depth_only -> "Depth_only"
  ;;
end

module Texture_dimension = struct
  include Wgpu_low.Texture_dimension

  let to_string = function
    | Undefined -> "Undefined"
    | N1d -> "N1d"
    | N2d -> "N2d"
    | N3d -> "N3d"
  ;;
end

module Texture_format = struct
  include Wgpu_low.Texture_format

  let to_string = function
    | Undefined -> "Undefined"
    | R8_unorm -> "R8_unorm"
    | R8_snorm -> "R8_snorm"
    | R8_uint -> "R8_uint"
    | R8_sint -> "R8_sint"
    | R16_uint -> "R16_uint"
    | R16_sint -> "R16_sint"
    | R16_float -> "R16_float"
    | Rg8_unorm -> "Rg8_unorm"
    | Rg8_snorm -> "Rg8_snorm"
    | Rg8_uint -> "Rg8_uint"
    | Rg8_sint -> "Rg8_sint"
    | R32_float -> "R32_float"
    | R32_uint -> "R32_uint"
    | R32_sint -> "R32_sint"
    | Rg16_uint -> "Rg16_uint"
    | Rg16_sint -> "Rg16_sint"
    | Rg16_float -> "Rg16_float"
    | Rgba8_unorm -> "Rgba8_unorm"
    | Rgba8_unorm_srgb -> "Rgba8_unorm_srgb"
    | Rgba8_snorm -> "Rgba8_snorm"
    | Rgba8_uint -> "Rgba8_uint"
    | Rgba8_sint -> "Rgba8_sint"
    | Bgra8_unorm -> "Bgra8_unorm"
    | Bgra8_unorm_srgb -> "Bgra8_unorm_srgb"
    | Rgb10_a2_uint -> "Rgb10_a2_uint"
    | Rgb10_a2_unorm -> "Rgb10_a2_unorm"
    | Rg11_b10_ufloat -> "Rg11_b10_ufloat"
    | Rgb9_e5_ufloat -> "Rgb9_e5_ufloat"
    | Rg32_float -> "Rg32_float"
    | Rg32_uint -> "Rg32_uint"
    | Rg32_sint -> "Rg32_sint"
    | Rgba16_uint -> "Rgba16_uint"
    | Rgba16_sint -> "Rgba16_sint"
    | Rgba16_float -> "Rgba16_float"
    | Rgba32_float -> "Rgba32_float"
    | Rgba32_uint -> "Rgba32_uint"
    | Rgba32_sint -> "Rgba32_sint"
    | Stencil8 -> "Stencil8"
    | Depth16_unorm -> "Depth16_unorm"
    | Depth24_plus -> "Depth24_plus"
    | Depth24_plus_stencil8 -> "Depth24_plus_stencil8"
    | Depth32_float -> "Depth32_float"
    | Depth32_float_stencil8 -> "Depth32_float_stencil8"
    | Bc1_rgba_unorm -> "Bc1_rgba_unorm"
    | Bc1_rgba_unorm_srgb -> "Bc1_rgba_unorm_srgb"
    | Bc2_rgba_unorm -> "Bc2_rgba_unorm"
    | Bc2_rgba_unorm_srgb -> "Bc2_rgba_unorm_srgb"
    | Bc3_rgba_unorm -> "Bc3_rgba_unorm"
    | Bc3_rgba_unorm_srgb -> "Bc3_rgba_unorm_srgb"
    | Bc4_r_unorm -> "Bc4_r_unorm"
    | Bc4_r_snorm -> "Bc4_r_snorm"
    | Bc5_rg_unorm -> "Bc5_rg_unorm"
    | Bc5_rg_snorm -> "Bc5_rg_snorm"
    | Bc6h_rgb_ufloat -> "Bc6h_rgb_ufloat"
    | Bc6h_rgb_float -> "Bc6h_rgb_float"
    | Bc7_rgba_unorm -> "Bc7_rgba_unorm"
    | Bc7_rgba_unorm_srgb -> "Bc7_rgba_unorm_srgb"
    | Etc2_rgb8_unorm -> "Etc2_rgb8_unorm"
    | Etc2_rgb8_unorm_srgb -> "Etc2_rgb8_unorm_srgb"
    | Etc2_rgb8a1_unorm -> "Etc2_rgb8a1_unorm"
    | Etc2_rgb8a1_unorm_srgb -> "Etc2_rgb8a1_unorm_srgb"
    | Etc2_rgba8_unorm -> "Etc2_rgba8_unorm"
    | Etc2_rgba8_unorm_srgb -> "Etc2_rgba8_unorm_srgb"
    | Eac_r11_unorm -> "Eac_r11_unorm"
    | Eac_r11_snorm -> "Eac_r11_snorm"
    | Eac_rg11_unorm -> "Eac_rg11_unorm"
    | Eac_rg11_snorm -> "Eac_rg11_snorm"
    | Astc_4x4_unorm -> "Astc_4x4_unorm"
    | Astc_4x4_unorm_srgb -> "Astc_4x4_unorm_srgb"
    | Astc_5x4_unorm -> "Astc_5x4_unorm"
    | Astc_5x4_unorm_srgb -> "Astc_5x4_unorm_srgb"
    | Astc_5x5_unorm -> "Astc_5x5_unorm"
    | Astc_5x5_unorm_srgb -> "Astc_5x5_unorm_srgb"
    | Astc_6x5_unorm -> "Astc_6x5_unorm"
    | Astc_6x5_unorm_srgb -> "Astc_6x5_unorm_srgb"
    | Astc_6x6_unorm -> "Astc_6x6_unorm"
    | Astc_6x6_unorm_srgb -> "Astc_6x6_unorm_srgb"
    | Astc_8x5_unorm -> "Astc_8x5_unorm"
    | Astc_8x5_unorm_srgb -> "Astc_8x5_unorm_srgb"
    | Astc_8x6_unorm -> "Astc_8x6_unorm"
    | Astc_8x6_unorm_srgb -> "Astc_8x6_unorm_srgb"
    | Astc_8x8_unorm -> "Astc_8x8_unorm"
    | Astc_8x8_unorm_srgb -> "Astc_8x8_unorm_srgb"
    | Astc_10x5_unorm -> "Astc_10x5_unorm"
    | Astc_10x5_unorm_srgb -> "Astc_10x5_unorm_srgb"
    | Astc_10x6_unorm -> "Astc_10x6_unorm"
    | Astc_10x6_unorm_srgb -> "Astc_10x6_unorm_srgb"
    | Astc_10x8_unorm -> "Astc_10x8_unorm"
    | Astc_10x8_unorm_srgb -> "Astc_10x8_unorm_srgb"
    | Astc_10x10_unorm -> "Astc_10x10_unorm"
    | Astc_10x10_unorm_srgb -> "Astc_10x10_unorm_srgb"
    | Astc_12x10_unorm -> "Astc_12x10_unorm"
    | Astc_12x10_unorm_srgb -> "Astc_12x10_unorm_srgb"
    | Astc_12x12_unorm -> "Astc_12x12_unorm"
    | Astc_12x12_unorm_srgb -> "Astc_12x12_unorm_srgb"
  ;;
end

module Texture_sample_type = struct
  include Wgpu_low.Texture_sample_type

  let to_string = function
    | Binding_not_used -> "Binding_not_used"
    | Undefined -> "Undefined"
    | Float -> "Float"
    | Unfilterable_float -> "Unfilterable_float"
    | Depth -> "Depth"
    | Sint -> "Sint"
    | Uint -> "Uint"
  ;;
end

module Texture_view_dimension = struct
  include Wgpu_low.Texture_view_dimension

  let to_string = function
    | Undefined -> "Undefined"
    | N1d -> "N1d"
    | N2d -> "N2d"
    | N2d_array -> "N2d_array"
    | Cube -> "Cube"
    | Cube_array -> "Cube_array"
    | N3d -> "N3d"
  ;;
end

module Vertex_format = struct
  include Wgpu_low.Vertex_format

  let to_string = function
    | Uint8 -> "Uint8"
    | Uint8x2 -> "Uint8x2"
    | Uint8x4 -> "Uint8x4"
    | Sint8 -> "Sint8"
    | Sint8x2 -> "Sint8x2"
    | Sint8x4 -> "Sint8x4"
    | Unorm8 -> "Unorm8"
    | Unorm8x2 -> "Unorm8x2"
    | Unorm8x4 -> "Unorm8x4"
    | Snorm8 -> "Snorm8"
    | Snorm8x2 -> "Snorm8x2"
    | Snorm8x4 -> "Snorm8x4"
    | Uint16 -> "Uint16"
    | Uint16x2 -> "Uint16x2"
    | Uint16x4 -> "Uint16x4"
    | Sint16 -> "Sint16"
    | Sint16x2 -> "Sint16x2"
    | Sint16x4 -> "Sint16x4"
    | Unorm16 -> "Unorm16"
    | Unorm16x2 -> "Unorm16x2"
    | Unorm16x4 -> "Unorm16x4"
    | Snorm16 -> "Snorm16"
    | Snorm16x2 -> "Snorm16x2"
    | Snorm16x4 -> "Snorm16x4"
    | Float16 -> "Float16"
    | Float16x2 -> "Float16x2"
    | Float16x4 -> "Float16x4"
    | Float32 -> "Float32"
    | Float32x2 -> "Float32x2"
    | Float32x3 -> "Float32x3"
    | Float32x4 -> "Float32x4"
    | Uint32 -> "Uint32"
    | Uint32x2 -> "Uint32x2"
    | Uint32x3 -> "Uint32x3"
    | Uint32x4 -> "Uint32x4"
    | Sint32 -> "Sint32"
    | Sint32x2 -> "Sint32x2"
    | Sint32x3 -> "Sint32x3"
    | Sint32x4 -> "Sint32x4"
    | Unorm10__10__10__2 -> "Unorm10__10__10__2"
    | Unorm8x4_b_g_r_a -> "Unorm8x4_b_g_r_a"
  ;;
end

module Vertex_step_mode = struct
  include Wgpu_low.Vertex_step_mode

  let to_string = function
    | Vertex_buffer_not_used -> "Vertex_buffer_not_used"
    | Undefined -> "Undefined"
    | Vertex -> "Vertex"
    | Instance -> "Instance"
  ;;
end

module Wait_status = struct
  include Wgpu_low.Wait_status

  let to_string = function
    | Success -> "Success"
    | Timed_out -> "Timed_out"
    | Unsupported_timeout -> "Unsupported_timeout"
    | Unsupported_count -> "Unsupported_count"
    | Unsupported_mixed_sources -> "Unsupported_mixed_sources"
  ;;
end

module Wgsl_language_feature_name = struct
  include Wgpu_low.Wgsl_language_feature_name

  let to_string = function
    | Readonly_and_readwrite_storage_textures -> "Readonly_and_readwrite_storage_textures"
    | Packed4x8_integer_dot_product -> "Packed4x8_integer_dot_product"
    | Unrestricted_pointer_parameters -> "Unrestricted_pointer_parameters"
    | Pointer_composite_access -> "Pointer_composite_access"
  ;;
end
