(* Generated by gen_bindings - high-level OCaml interface *)

module Instance : sig
  type t

  (** Create a new wgpu instance *)
  val create : unit -> t

  (** Release an instance. After this call, the instance should not be used. *)
  val release : t -> unit
end
