(* Generated by gen_bindings - high-level OCaml bindings *)

module Adapter_Type = Wgpu_low.Adapter_Type

module Address_Mode = Wgpu_low.Address_Mode

module Backend_Type = Wgpu_low.Backend_Type

module Blend_Factor = Wgpu_low.Blend_Factor

module Blend_Operation = Wgpu_low.Blend_Operation

module Buffer_Binding_Type = Wgpu_low.Buffer_Binding_Type

module Buffer_Map_State = Wgpu_low.Buffer_Map_State

module Callback_Mode = Wgpu_low.Callback_Mode

module Compare_Function = Wgpu_low.Compare_Function

module Compilation_Info_Request_Status = Wgpu_low.Compilation_Info_Request_Status

module Compilation_Message_Type = Wgpu_low.Compilation_Message_Type

module Composite_Alpha_Mode = Wgpu_low.Composite_Alpha_Mode

module Create_Pipeline_Async_Status = Wgpu_low.Create_Pipeline_Async_Status

module Cull_Mode = Wgpu_low.Cull_Mode

module Device_Lost_Reason = Wgpu_low.Device_Lost_Reason

module Error_Filter = Wgpu_low.Error_Filter

module Error_Type = Wgpu_low.Error_Type

module Feature_Level = Wgpu_low.Feature_Level

module Feature_Name = Wgpu_low.Feature_Name

module Filter_Mode = Wgpu_low.Filter_Mode

module Front_Face = Wgpu_low.Front_Face

module Index_Format = Wgpu_low.Index_Format

module Load_Op = Wgpu_low.Load_Op

module Map_Async_Status = Wgpu_low.Map_Async_Status

module Mipmap_Filter_Mode = Wgpu_low.Mipmap_Filter_Mode

module Optional_Bool = Wgpu_low.Optional_Bool

module Pop_Error_Scope_Status = Wgpu_low.Pop_Error_Scope_Status

module Power_Preference = Wgpu_low.Power_Preference

module Present_Mode = Wgpu_low.Present_Mode

module Primitive_Topology = Wgpu_low.Primitive_Topology

module Query_Type = Wgpu_low.Query_Type

module Queue_Work_Done_Status = Wgpu_low.Queue_Work_Done_Status

module Request_Adapter_Status = Wgpu_low.Request_Adapter_Status

module Request_Device_Status = Wgpu_low.Request_Device_Status

module S_Type = Wgpu_low.S_Type

module Sampler_Binding_Type = Wgpu_low.Sampler_Binding_Type

module Status = Wgpu_low.Status

module Stencil_Operation = Wgpu_low.Stencil_Operation

module Storage_Texture_Access = Wgpu_low.Storage_Texture_Access

module Store_Op = Wgpu_low.Store_Op

module Surface_Get_Current_Texture_Status = Wgpu_low.Surface_Get_Current_Texture_Status

module Texture_Aspect = Wgpu_low.Texture_Aspect

module Texture_Dimension = Wgpu_low.Texture_Dimension

module Texture_Format = Wgpu_low.Texture_Format

module Texture_Sample_Type = Wgpu_low.Texture_Sample_Type

module Texture_View_Dimension = Wgpu_low.Texture_View_Dimension

module Vertex_Format = Wgpu_low.Vertex_Format

module Vertex_Step_Mode = Wgpu_low.Vertex_Step_Mode

module Wait_Status = Wgpu_low.Wait_Status

module WGSL_Language_Feature_Name = Wgpu_low.WGSL_Language_Feature_Name
module Buffer_Usage = Wgpu_low.Buffer_Usage

module Color_Write_Mask = Wgpu_low.Color_Write_Mask

module Map_Mode = Wgpu_low.Map_Mode

module Shader_Stage = Wgpu_low.Shader_Stage

module Texture_Usage = Wgpu_low.Texture_Usage
module Bind_Group = struct
  type t = { handle : Wgpu_low.bind_group }

  let release t = Wgpu_low.bind_group_release t.handle
end

module Bind_Group_Layout = struct
  type t = { handle : Wgpu_low.bind_group_layout }

  let release t = Wgpu_low.bind_group_layout_release t.handle
end

module Buffer = struct
  type t = { handle : Wgpu_low.buffer }

  let release t = Wgpu_low.buffer_release t.handle
end

module Command_Buffer = struct
  type t = { handle : Wgpu_low.command_buffer }

  let release t = Wgpu_low.command_buffer_release t.handle
end

module Command_Encoder = struct
  type t = { handle : Wgpu_low.command_encoder }

  let release t = Wgpu_low.command_encoder_release t.handle
end

module Compute_Pass_Encoder = struct
  type t = { handle : Wgpu_low.compute_pass_encoder }

  let release t = Wgpu_low.compute_pass_encoder_release t.handle
end

module Compute_Pipeline = struct
  type t = { handle : Wgpu_low.compute_pipeline }

  let release t = Wgpu_low.compute_pipeline_release t.handle
end

module Pipeline_Layout = struct
  type t = { handle : Wgpu_low.pipeline_layout }

  let release t = Wgpu_low.pipeline_layout_release t.handle
end

module Query_Set = struct
  type t = { handle : Wgpu_low.query_set }

  let release t = Wgpu_low.query_set_release t.handle
end

module Render_Bundle = struct
  type t = { handle : Wgpu_low.render_bundle }

  let release t = Wgpu_low.render_bundle_release t.handle
end

module Render_Bundle_Encoder = struct
  type t = { handle : Wgpu_low.render_bundle_encoder }

  let release t = Wgpu_low.render_bundle_encoder_release t.handle
end

module Render_Pass_Encoder = struct
  type t = { handle : Wgpu_low.render_pass_encoder }

  let release t = Wgpu_low.render_pass_encoder_release t.handle
end

module Render_Pipeline = struct
  type t = { handle : Wgpu_low.render_pipeline }

  let release t = Wgpu_low.render_pipeline_release t.handle
end

module Sampler = struct
  type t = { handle : Wgpu_low.sampler }

  let release t = Wgpu_low.sampler_release t.handle
end

module Shader_Module = struct
  type t = { handle : Wgpu_low.shader_module }

  let release t = Wgpu_low.shader_module_release t.handle
end

module Surface = struct
  type t = { handle : Wgpu_low.surface }

  let release t = Wgpu_low.surface_release t.handle
end

module Texture = struct
  type t = { handle : Wgpu_low.texture }

  let release t = Wgpu_low.texture_release t.handle
end

module Texture_View = struct
  type t = { handle : Wgpu_low.texture_view }

  let release t = Wgpu_low.texture_view_release t.handle
end
module Adapter_info = struct
  type t = Wgpu_low.adapter_info =
    { vendor : string
    ; architecture : string
    ; device : string
    ; description : string
    ; backend_type : int
    ; adapter_type : int
    }
end

module Queue = struct
  type t = { handle : Wgpu_low.queue }

  let release t = Wgpu_low.queue_release t.handle
end

module Device = struct
  type t = { handle : Wgpu_low.device }

  let release t = Wgpu_low.device_release t.handle
  let get_queue t = { Queue.handle = Wgpu_low.device_get_queue t.handle }
end

module Adapter = struct
  type t = { handle : Wgpu_low.adapter }

  let get_info t = Wgpu_low.adapter_get_info t.handle
  let release t = Wgpu_low.adapter_release t.handle
  let request_device t =
    let device = Wgpu_low.adapter_request_device_sync t.handle in
    { Device.handle = device }
end
module Instance = struct
  type t = { handle : Wgpu_low.instance }

  let create () = { handle = Wgpu_low.create_instance () }
  let release t = Wgpu_low.instance_release t.handle

  let request_adapter t =
    let adapter = Wgpu_low.instance_request_adapter_sync t.handle in
    { Adapter.handle = adapter }
end
