(* Generated by gen_bindings - high-level OCaml bindings *)

include Enums
include Bitsets

module Bind_group = struct
  type t = { handle : Wgpu_low.bind_group }

  let release t = Wgpu_low.bind_group_release t.handle
  let set_label t ~label = Wgpu_low.bind_group_set_label t.handle label
end

module Bind_group_layout = struct
  type t = { handle : Wgpu_low.bind_group_layout }

  let release t = Wgpu_low.bind_group_layout_release t.handle
  let set_label t ~label = Wgpu_low.bind_group_layout_set_label t.handle label
end

module Buffer = struct
  type t = { handle : Wgpu_low.buffer }

  let release t = Wgpu_low.buffer_release t.handle

  let get_mapped_range t ~offset ~size =
    Wgpu_low.buffer_get_mapped_range t.handle offset size
  ;;

  let get_const_mapped_range t ~offset ~size =
    Wgpu_low.buffer_get_const_mapped_range t.handle offset size
  ;;

  let set_label t ~label = Wgpu_low.buffer_set_label t.handle label
  let get_usage t = Wgpu_low.buffer_get_usage t.handle
  let get_size t = Wgpu_low.buffer_get_size t.handle
  let get_map_state t = Buffer_map_state.of_int (Wgpu_low.buffer_get_map_state t.handle)
  let unmap t = Wgpu_low.buffer_unmap t.handle
  let destroy t = Wgpu_low.buffer_destroy t.handle
end

module Command_buffer = struct
  type t = { handle : Wgpu_low.command_buffer }

  let release t = Wgpu_low.command_buffer_release t.handle
  let set_label t ~label = Wgpu_low.command_buffer_set_label t.handle label
end

module Pipeline_layout = struct
  type t = { handle : Wgpu_low.pipeline_layout }

  let release t = Wgpu_low.pipeline_layout_release t.handle
  let set_label t ~label = Wgpu_low.pipeline_layout_set_label t.handle label
end

module Query_set = struct
  type t = { handle : Wgpu_low.query_set }

  let release t = Wgpu_low.query_set_release t.handle
  let set_label t ~label = Wgpu_low.query_set_set_label t.handle label
  let get_type t = Query_type.of_int (Wgpu_low.query_set_get_type t.handle)
  let get_count t = Wgpu_low.query_set_get_count t.handle
  let destroy t = Wgpu_low.query_set_destroy t.handle
end

module Render_bundle = struct
  type t = { handle : Wgpu_low.render_bundle }

  let release t = Wgpu_low.render_bundle_release t.handle
  let set_label t ~label = Wgpu_low.render_bundle_set_label t.handle label
end

module Sampler = struct
  type t = { handle : Wgpu_low.sampler }

  let release t = Wgpu_low.sampler_release t.handle
  let set_label t ~label = Wgpu_low.sampler_set_label t.handle label
end

module Shader_module = struct
  type t = { handle : Wgpu_low.shader_module }

  let release t = Wgpu_low.shader_module_release t.handle
  let set_label t ~label = Wgpu_low.shader_module_set_label t.handle label
end

module Texture_view = struct
  type t = { handle : Wgpu_low.texture_view }

  let release t = Wgpu_low.texture_view_release t.handle
  let set_label t ~label = Wgpu_low.texture_view_set_label t.handle label
end

module Compute_pipeline = struct
  type t = { handle : Wgpu_low.compute_pipeline }

  let release t = Wgpu_low.compute_pipeline_release t.handle

  let get_bind_group_layout t ~group_index : Bind_group_layout.t =
    { Bind_group_layout.handle =
        Wgpu_low.compute_pipeline_get_bind_group_layout t.handle group_index
    }
  ;;

  let set_label t ~label = Wgpu_low.compute_pipeline_set_label t.handle label
end

module Render_pipeline = struct
  type t = { handle : Wgpu_low.render_pipeline }

  let release t = Wgpu_low.render_pipeline_release t.handle

  let get_bind_group_layout t ~group_index : Bind_group_layout.t =
    { Bind_group_layout.handle =
        Wgpu_low.render_pipeline_get_bind_group_layout t.handle group_index
    }
  ;;

  let set_label t ~label = Wgpu_low.render_pipeline_set_label t.handle label
end

module Texture = struct
  type t = { handle : Wgpu_low.texture }

  let release t = Wgpu_low.texture_release t.handle

  let create_view
    t
    ?(label = "")
    ~format
    ~dimension
    ~base_mip_level
    ~mip_level_count
    ~base_array_layer
    ~array_layer_count
    ~aspect
    ~usage
    ()
    =
    let desc_descriptor =
      Wgpu_low.Texture_view_descriptor.texture_view_descriptor_create ()
    in
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_label
      desc_descriptor
      label;
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_format
      desc_descriptor
      (Texture_format.to_int format);
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_dimension
      desc_descriptor
      (Texture_view_dimension.to_int dimension);
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_base_mip_level
      desc_descriptor
      base_mip_level;
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_mip_level_count
      desc_descriptor
      mip_level_count;
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_base_array_layer
      desc_descriptor
      base_array_layer;
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_array_layer_count
      desc_descriptor
      array_layer_count;
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_aspect
      desc_descriptor
      (Texture_aspect.to_int aspect);
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_set_usage
      desc_descriptor
      (Texture_usage.list_to_int usage);
    let result = Wgpu_low.texture_create_view t.handle desc_descriptor in
    Wgpu_low.Texture_view_descriptor.texture_view_descriptor_free desc_descriptor;
    ({ Texture_view.handle = result } : Texture_view.t)
  ;;

  let set_label t ~label = Wgpu_low.texture_set_label t.handle label
  let get_width t = Wgpu_low.texture_get_width t.handle
  let get_height t = Wgpu_low.texture_get_height t.handle
  let get_depth_or_array_layers t = Wgpu_low.texture_get_depth_or_array_layers t.handle
  let get_mip_level_count t = Wgpu_low.texture_get_mip_level_count t.handle
  let get_sample_count t = Wgpu_low.texture_get_sample_count t.handle
  let get_dimension t = Texture_dimension.of_int (Wgpu_low.texture_get_dimension t.handle)
  let get_format t = Texture_format.of_int (Wgpu_low.texture_get_format t.handle)
  let get_usage t = Wgpu_low.texture_get_usage t.handle
  let destroy t = Wgpu_low.texture_destroy t.handle
end

module Compute_pass_encoder = struct
  type t = { handle : Wgpu_low.compute_pass_encoder }

  let release t = Wgpu_low.compute_pass_encoder_release t.handle

  let insert_debug_marker t ~marker_label =
    Wgpu_low.compute_pass_encoder_insert_debug_marker t.handle marker_label
  ;;

  let pop_debug_group t = Wgpu_low.compute_pass_encoder_pop_debug_group t.handle

  let push_debug_group t ~group_label =
    Wgpu_low.compute_pass_encoder_push_debug_group t.handle group_label
  ;;

  let set_pipeline t ~pipeline =
    Wgpu_low.compute_pass_encoder_set_pipeline t.handle pipeline.Compute_pipeline.handle
  ;;

  let set_bind_group t ~group_index ~group ~dynamic_offsets =
    Wgpu_low.compute_pass_encoder_set_bind_group
      t.handle
      group_index
      group.Bind_group.handle
      (Array.of_list dynamic_offsets)
  ;;

  let dispatch_workgroups t ~workgroupCountX ~workgroupCountY ~workgroupCountZ =
    Wgpu_low.compute_pass_encoder_dispatch_workgroups
      t.handle
      workgroupCountX
      workgroupCountY
      workgroupCountZ
  ;;

  let dispatch_workgroups_indirect t ~indirect_buffer ~indirect_offset =
    Wgpu_low.compute_pass_encoder_dispatch_workgroups_indirect
      t.handle
      indirect_buffer.Buffer.handle
      indirect_offset
  ;;

  let end_ t = Wgpu_low.compute_pass_encoder_end t.handle
  let set_label t ~label = Wgpu_low.compute_pass_encoder_set_label t.handle label
end

module Render_bundle_encoder = struct
  type t = { handle : Wgpu_low.render_bundle_encoder }

  let release t = Wgpu_low.render_bundle_encoder_release t.handle

  let set_pipeline t ~pipeline =
    Wgpu_low.render_bundle_encoder_set_pipeline t.handle pipeline.Render_pipeline.handle
  ;;

  let set_bind_group t ~group_index ~group ~dynamic_offsets =
    Wgpu_low.render_bundle_encoder_set_bind_group
      t.handle
      group_index
      group.Bind_group.handle
      (Array.of_list dynamic_offsets)
  ;;

  let draw t ~vertex_count ~instance_count ~first_vertex ~first_instance =
    Wgpu_low.render_bundle_encoder_draw
      t.handle
      vertex_count
      instance_count
      first_vertex
      first_instance
  ;;

  let draw_indexed
    t
    ~index_count
    ~instance_count
    ~first_index
    ~base_vertex
    ~first_instance
    =
    Wgpu_low.render_bundle_encoder_draw_indexed
      t.handle
      index_count
      instance_count
      first_index
      base_vertex
      first_instance
  ;;

  let draw_indirect t ~indirect_buffer ~indirect_offset =
    Wgpu_low.render_bundle_encoder_draw_indirect
      t.handle
      indirect_buffer.Buffer.handle
      indirect_offset
  ;;

  let draw_indexed_indirect t ~indirect_buffer ~indirect_offset =
    Wgpu_low.render_bundle_encoder_draw_indexed_indirect
      t.handle
      indirect_buffer.Buffer.handle
      indirect_offset
  ;;

  let insert_debug_marker t ~marker_label =
    Wgpu_low.render_bundle_encoder_insert_debug_marker t.handle marker_label
  ;;

  let pop_debug_group t = Wgpu_low.render_bundle_encoder_pop_debug_group t.handle

  let push_debug_group t ~group_label =
    Wgpu_low.render_bundle_encoder_push_debug_group t.handle group_label
  ;;

  let set_vertex_buffer t ~slot ~buffer ~offset ~size =
    Wgpu_low.render_bundle_encoder_set_vertex_buffer
      t.handle
      slot
      buffer.Buffer.handle
      offset
      size
  ;;

  let set_index_buffer t ~buffer ~format ~offset ~size =
    Wgpu_low.render_bundle_encoder_set_index_buffer
      t.handle
      buffer.Buffer.handle
      (Index_format.to_int format)
      offset
      size
  ;;

  let finish t ?(label = "") () =
    let desc_descriptor =
      Wgpu_low.Render_bundle_descriptor.render_bundle_descriptor_create ()
    in
    Wgpu_low.Render_bundle_descriptor.render_bundle_descriptor_set_label
      desc_descriptor
      label;
    let result = Wgpu_low.render_bundle_encoder_finish t.handle desc_descriptor in
    Wgpu_low.Render_bundle_descriptor.render_bundle_descriptor_free desc_descriptor;
    ({ Render_bundle.handle = result } : Render_bundle.t)
  ;;

  let set_label t ~label = Wgpu_low.render_bundle_encoder_set_label t.handle label
end

module Render_pass_encoder = struct
  type t = { handle : Wgpu_low.render_pass_encoder }

  let release t = Wgpu_low.render_pass_encoder_release t.handle

  let set_pipeline t ~pipeline =
    Wgpu_low.render_pass_encoder_set_pipeline t.handle pipeline.Render_pipeline.handle
  ;;

  let set_bind_group t ~group_index ~group ~dynamic_offsets =
    Wgpu_low.render_pass_encoder_set_bind_group
      t.handle
      group_index
      group.Bind_group.handle
      (Array.of_list dynamic_offsets)
  ;;

  let draw t ~vertex_count ~instance_count ~first_vertex ~first_instance =
    Wgpu_low.render_pass_encoder_draw
      t.handle
      vertex_count
      instance_count
      first_vertex
      first_instance
  ;;

  let draw_indexed
    t
    ~index_count
    ~instance_count
    ~first_index
    ~base_vertex
    ~first_instance
    =
    Wgpu_low.render_pass_encoder_draw_indexed
      t.handle
      index_count
      instance_count
      first_index
      base_vertex
      first_instance
  ;;

  let draw_indirect t ~indirect_buffer ~indirect_offset =
    Wgpu_low.render_pass_encoder_draw_indirect
      t.handle
      indirect_buffer.Buffer.handle
      indirect_offset
  ;;

  let draw_indexed_indirect t ~indirect_buffer ~indirect_offset =
    Wgpu_low.render_pass_encoder_draw_indexed_indirect
      t.handle
      indirect_buffer.Buffer.handle
      indirect_offset
  ;;

  let execute_bundles t ~bundles =
    Wgpu_low.render_pass_encoder_execute_bundles
      t.handle
      (Array.of_list (List.map (fun x -> x.Render_bundle.handle) bundles))
  ;;

  let insert_debug_marker t ~marker_label =
    Wgpu_low.render_pass_encoder_insert_debug_marker t.handle marker_label
  ;;

  let pop_debug_group t = Wgpu_low.render_pass_encoder_pop_debug_group t.handle

  let push_debug_group t ~group_label =
    Wgpu_low.render_pass_encoder_push_debug_group t.handle group_label
  ;;

  let set_stencil_reference t ~reference =
    Wgpu_low.render_pass_encoder_set_stencil_reference t.handle reference
  ;;

  let set_blend_constant t ~r ~g ~b ~a () =
    let desc_color = Wgpu_low.Color.color_create () in
    Wgpu_low.Color.color_set_r desc_color r;
    Wgpu_low.Color.color_set_g desc_color g;
    Wgpu_low.Color.color_set_b desc_color b;
    Wgpu_low.Color.color_set_a desc_color a;
    Wgpu_low.render_pass_encoder_set_blend_constant t.handle desc_color;
    Wgpu_low.Color.color_free desc_color;
    ()
  ;;

  let set_viewport t ~x ~y ~width ~height ~min_depth ~max_depth =
    Wgpu_low.render_pass_encoder_set_viewport
      t.handle
      x
      y
      width
      height
      min_depth
      max_depth
  ;;

  let set_scissor_rect t ~x ~y ~width ~height =
    Wgpu_low.render_pass_encoder_set_scissor_rect t.handle x y width height
  ;;

  let set_vertex_buffer t ~slot ~buffer ~offset ~size =
    Wgpu_low.render_pass_encoder_set_vertex_buffer
      t.handle
      slot
      buffer.Buffer.handle
      offset
      size
  ;;

  let set_index_buffer t ~buffer ~format ~offset ~size =
    Wgpu_low.render_pass_encoder_set_index_buffer
      t.handle
      buffer.Buffer.handle
      (Index_format.to_int format)
      offset
      size
  ;;

  let begin_occlusion_query t ~query_index =
    Wgpu_low.render_pass_encoder_begin_occlusion_query t.handle query_index
  ;;

  let end_occlusion_query t = Wgpu_low.render_pass_encoder_end_occlusion_query t.handle
  let end_ t = Wgpu_low.render_pass_encoder_end t.handle
  let set_label t ~label = Wgpu_low.render_pass_encoder_set_label t.handle label
end

module Surface = struct
  type t = { handle : Wgpu_low.surface }

  type surface_capabilities =
    { usages : Texture_usage.Item.t list
    ; formats : Texture_format.t list
    ; present_modes : Present_mode.t list
    ; alpha_modes : Composite_alpha_mode.t list
    }

  type surface_texture =
    { texture : Texture.t
    ; status : Surface_get_current_texture_status.t
    }

  let release t = Wgpu_low.surface_release t.handle

  let get_current_texture t =
    let output = Wgpu_low.Surface_texture.surface_texture_create () in
    let _status = Wgpu_low.surface_get_current_texture t.handle output in
    let texture =
      ({ Texture.handle = Wgpu_low.Surface_texture.surface_texture_get_texture output }
       : Texture.t)
    in
    let status =
      Surface_get_current_texture_status.of_int
        (Wgpu_low.Surface_texture.surface_texture_get_status output)
    in
    let result = { texture; status } in
    Wgpu_low.Surface_texture.surface_texture_free output;
    result
  ;;

  let present t = Status.of_int (Wgpu_low.surface_present t.handle)
  let unconfigure t = Wgpu_low.surface_unconfigure t.handle
  let set_label t ~label = Wgpu_low.surface_set_label t.handle label
end

module Command_encoder = struct
  type t = { handle : Wgpu_low.command_encoder }

  let release t = Wgpu_low.command_encoder_release t.handle

  let finish t ?(label = "") () =
    let desc_descriptor =
      Wgpu_low.Command_buffer_descriptor.command_buffer_descriptor_create ()
    in
    Wgpu_low.Command_buffer_descriptor.command_buffer_descriptor_set_label
      desc_descriptor
      label;
    let result = Wgpu_low.command_encoder_finish t.handle desc_descriptor in
    Wgpu_low.Command_buffer_descriptor.command_buffer_descriptor_free desc_descriptor;
    ({ Command_buffer.handle = result } : Command_buffer.t)
  ;;

  let copy_buffer_to_buffer
    t
    ~source
    ~source_offset
    ~destination
    ~destination_offset
    ~size
    =
    Wgpu_low.command_encoder_copy_buffer_to_buffer
      t.handle
      source.Buffer.handle
      source_offset
      destination.Buffer.handle
      destination_offset
      size
  ;;

  let copy_buffer_to_texture
    t
    ~source_layout_offset
    ~source_layout_bytes_per_row
    ~source_layout_rows_per_image
    ~source_buffer
    ~destination_texture
    ~destination_mip_level
    ~destination_origin_x
    ~destination_origin_y
    ~destination_origin_z
    ~destination_aspect
    ~copy_size_width
    ~copy_size_height
    ~copy_size_depth_or_array_layers
    ()
    =
    let source_layout_nested =
      Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_create ()
    in
    let desc_source = Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_create () in
    let destination_origin_nested = Wgpu_low.Origin_3d.origin_3D_create () in
    let desc_destination =
      Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_create ()
    in
    let desc_copy_size = Wgpu_low.Extent_3d.extent_3D_create () in
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_set_offset
      source_layout_nested
      source_layout_offset;
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_set_bytes_per_row
      source_layout_nested
      source_layout_bytes_per_row;
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_set_rows_per_image
      source_layout_nested
      source_layout_rows_per_image;
    Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_set_layout
      desc_source
      source_layout_nested;
    Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_set_buffer
      desc_source
      source_buffer.Buffer.handle;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_texture
      desc_destination
      destination_texture.Texture.handle;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_mip_level
      desc_destination
      destination_mip_level;
    Wgpu_low.Origin_3d.origin_3D_set_x destination_origin_nested destination_origin_x;
    Wgpu_low.Origin_3d.origin_3D_set_y destination_origin_nested destination_origin_y;
    Wgpu_low.Origin_3d.origin_3D_set_z destination_origin_nested destination_origin_z;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_origin
      desc_destination
      destination_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_aspect
      desc_destination
      (Texture_aspect.to_int destination_aspect);
    Wgpu_low.Extent_3d.extent_3D_set_width desc_copy_size copy_size_width;
    Wgpu_low.Extent_3d.extent_3D_set_height desc_copy_size copy_size_height;
    Wgpu_low.Extent_3d.extent_3D_set_depth_or_array_layers
      desc_copy_size
      copy_size_depth_or_array_layers;
    Wgpu_low.command_encoder_copy_buffer_to_texture
      t.handle
      desc_source
      desc_destination
      desc_copy_size;
    Wgpu_low.Extent_3d.extent_3D_free desc_copy_size;
    Wgpu_low.Origin_3d.origin_3D_free destination_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_free desc_destination;
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_free source_layout_nested;
    Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_free desc_source;
    ()
  ;;

  let copy_texture_to_buffer
    t
    ~source_texture
    ~source_mip_level
    ~source_origin_x
    ~source_origin_y
    ~source_origin_z
    ~source_aspect
    ~destination_layout_offset
    ~destination_layout_bytes_per_row
    ~destination_layout_rows_per_image
    ~destination_buffer
    ~copy_size_width
    ~copy_size_height
    ~copy_size_depth_or_array_layers
    ()
    =
    let source_origin_nested = Wgpu_low.Origin_3d.origin_3D_create () in
    let desc_source =
      Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_create ()
    in
    let destination_layout_nested =
      Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_create ()
    in
    let desc_destination =
      Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_create ()
    in
    let desc_copy_size = Wgpu_low.Extent_3d.extent_3D_create () in
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_texture
      desc_source
      source_texture.Texture.handle;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_mip_level
      desc_source
      source_mip_level;
    Wgpu_low.Origin_3d.origin_3D_set_x source_origin_nested source_origin_x;
    Wgpu_low.Origin_3d.origin_3D_set_y source_origin_nested source_origin_y;
    Wgpu_low.Origin_3d.origin_3D_set_z source_origin_nested source_origin_z;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_origin
      desc_source
      source_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_aspect
      desc_source
      (Texture_aspect.to_int source_aspect);
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_set_offset
      destination_layout_nested
      destination_layout_offset;
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_set_bytes_per_row
      destination_layout_nested
      destination_layout_bytes_per_row;
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_set_rows_per_image
      destination_layout_nested
      destination_layout_rows_per_image;
    Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_set_layout
      desc_destination
      destination_layout_nested;
    Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_set_buffer
      desc_destination
      destination_buffer.Buffer.handle;
    Wgpu_low.Extent_3d.extent_3D_set_width desc_copy_size copy_size_width;
    Wgpu_low.Extent_3d.extent_3D_set_height desc_copy_size copy_size_height;
    Wgpu_low.Extent_3d.extent_3D_set_depth_or_array_layers
      desc_copy_size
      copy_size_depth_or_array_layers;
    Wgpu_low.command_encoder_copy_texture_to_buffer
      t.handle
      desc_source
      desc_destination
      desc_copy_size;
    Wgpu_low.Extent_3d.extent_3D_free desc_copy_size;
    Wgpu_low.Texel_copy_buffer_layout.texel_copy_buffer_layout_free
      destination_layout_nested;
    Wgpu_low.Texel_copy_buffer_info.texel_copy_buffer_info_free desc_destination;
    Wgpu_low.Origin_3d.origin_3D_free source_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_free desc_source;
    ()
  ;;

  let copy_texture_to_texture
    t
    ~source_texture
    ~source_mip_level
    ~source_origin_x
    ~source_origin_y
    ~source_origin_z
    ~source_aspect
    ~destination_texture
    ~destination_mip_level
    ~destination_origin_x
    ~destination_origin_y
    ~destination_origin_z
    ~destination_aspect
    ~copy_size_width
    ~copy_size_height
    ~copy_size_depth_or_array_layers
    ()
    =
    let source_origin_nested = Wgpu_low.Origin_3d.origin_3D_create () in
    let desc_source =
      Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_create ()
    in
    let destination_origin_nested = Wgpu_low.Origin_3d.origin_3D_create () in
    let desc_destination =
      Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_create ()
    in
    let desc_copy_size = Wgpu_low.Extent_3d.extent_3D_create () in
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_texture
      desc_source
      source_texture.Texture.handle;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_mip_level
      desc_source
      source_mip_level;
    Wgpu_low.Origin_3d.origin_3D_set_x source_origin_nested source_origin_x;
    Wgpu_low.Origin_3d.origin_3D_set_y source_origin_nested source_origin_y;
    Wgpu_low.Origin_3d.origin_3D_set_z source_origin_nested source_origin_z;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_origin
      desc_source
      source_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_aspect
      desc_source
      (Texture_aspect.to_int source_aspect);
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_texture
      desc_destination
      destination_texture.Texture.handle;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_mip_level
      desc_destination
      destination_mip_level;
    Wgpu_low.Origin_3d.origin_3D_set_x destination_origin_nested destination_origin_x;
    Wgpu_low.Origin_3d.origin_3D_set_y destination_origin_nested destination_origin_y;
    Wgpu_low.Origin_3d.origin_3D_set_z destination_origin_nested destination_origin_z;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_origin
      desc_destination
      destination_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_set_aspect
      desc_destination
      (Texture_aspect.to_int destination_aspect);
    Wgpu_low.Extent_3d.extent_3D_set_width desc_copy_size copy_size_width;
    Wgpu_low.Extent_3d.extent_3D_set_height desc_copy_size copy_size_height;
    Wgpu_low.Extent_3d.extent_3D_set_depth_or_array_layers
      desc_copy_size
      copy_size_depth_or_array_layers;
    Wgpu_low.command_encoder_copy_texture_to_texture
      t.handle
      desc_source
      desc_destination
      desc_copy_size;
    Wgpu_low.Extent_3d.extent_3D_free desc_copy_size;
    Wgpu_low.Origin_3d.origin_3D_free destination_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_free desc_destination;
    Wgpu_low.Origin_3d.origin_3D_free source_origin_nested;
    Wgpu_low.Texel_copy_texture_info.texel_copy_texture_info_free desc_source;
    ()
  ;;

  let clear_buffer t ~buffer ~offset ~size =
    Wgpu_low.command_encoder_clear_buffer t.handle buffer.Buffer.handle offset size
  ;;

  let insert_debug_marker t ~marker_label =
    Wgpu_low.command_encoder_insert_debug_marker t.handle marker_label
  ;;

  let pop_debug_group t = Wgpu_low.command_encoder_pop_debug_group t.handle

  let push_debug_group t ~group_label =
    Wgpu_low.command_encoder_push_debug_group t.handle group_label
  ;;

  let resolve_query_set
    t
    ~query_set
    ~first_query
    ~query_count
    ~destination
    ~destination_offset
    =
    Wgpu_low.command_encoder_resolve_query_set
      t.handle
      query_set.Query_set.handle
      first_query
      query_count
      destination.Buffer.handle
      destination_offset
  ;;

  let write_timestamp t ~query_set ~query_index =
    Wgpu_low.command_encoder_write_timestamp
      t.handle
      query_set.Query_set.handle
      query_index
  ;;

  let set_label t ~label = Wgpu_low.command_encoder_set_label t.handle label
end

module Bind_group_entry = struct
  type t =
    { binding : int
    ; buffer : Buffer.t option
    ; offset : int64
    ; size : int64
    ; sampler : Sampler.t option
    ; texture_view : Texture_view.t option
    }
end

module Bind_group_layout_entry = struct
  module Buffer_binding_layout = struct
    type t =
      { type_ : Buffer_binding_type.t
      ; has_dynamic_offset : bool
      ; min_binding_size : int64
      }
  end

  module Sampler_binding_layout = struct
    type t = { type_ : Sampler_binding_type.t }
  end

  module Storage_texture_binding_layout = struct
    type t =
      { access : Storage_texture_access.t
      ; format : Texture_format.t
      ; view_dimension : Texture_view_dimension.t
      }
  end

  module Texture_binding_layout = struct
    type t =
      { sample_type : Texture_sample_type.t
      ; view_dimension : Texture_view_dimension.t
      ; multisampled : bool
      }
  end

  type t =
    { binding : int
    ; visibility : Shader_stage.Item.t list
    ; buffer : Buffer_binding_layout.t option
    ; sampler : Sampler_binding_layout.t option
    ; texture : Texture_binding_layout.t option
    ; storage_texture : Storage_texture_binding_layout.t option
    }
end

module Color_target_state = struct
  type t =
    { format : Texture_format.t
    ; blend : nativeint
    ; write_mask : Color_write_mask.Item.t list
    }
end

module Compilation_message = struct
  type t =
    { message : string
    ; type_ : Compilation_message_type.t
    ; line_num : int64
    ; line_pos : int64
    ; offset : int64
    ; length : int64
    }
end

module Constant_entry = struct
  type t =
    { key : string
    ; value : float
    }
end

module Render_pass_color_attachment = struct
  module Color = struct
    type t =
      { r : float
      ; g : float
      ; b : float
      ; a : float
      }
  end

  type t =
    { view : Texture_view.t option
    ; depth_slice : int
    ; resolve_target : Texture_view.t option
    ; load_op : Load_op.t
    ; store_op : Store_op.t
    ; clear_value : Color.t option
    }
end

module Vertex_attribute = struct
  type t =
    { format : Vertex_format.t
    ; offset : int64
    ; shader_location : int
    }
end

module Vertex_buffer_layout = struct
  type t =
    { step_mode : Vertex_step_mode.t
    ; array_stride : int64
    ; attributes : Vertex_attribute.t list
    }
end

module Adapter_info = struct
  type t =
    { vendor : string
    ; architecture : string
    ; device : string
    ; description : string
    ; backend_type : Backend_type.t
    ; adapter_type : Adapter_type.t
    }

  let of_low (info : Wgpu_low.adapter_info) : t =
    { vendor = info.vendor
    ; architecture = info.architecture
    ; device = info.device
    ; description = info.description
    ; backend_type = Backend_type.of_int info.backend_type
    ; adapter_type = Adapter_type.of_int info.adapter_type
    }
  ;;
end

module Queue = struct
  type t = { handle : Wgpu_low.queue }

  let release t = Wgpu_low.queue_release t.handle
  let set_label t ~label = Wgpu_low.queue_set_label t.handle label

  let submit t ~command_buffers =
    let handles = List.map (fun (cb : Command_buffer.t) -> cb.handle) command_buffers in
    Wgpu_low.queue_submit t.handle (Array.of_list handles)
  ;;

  let write_buffer t ~buffer ~offset ~data =
    Wgpu_low.queue_write_buffer_bigarray t.handle buffer.Buffer.handle offset data
  ;;
end

module Device = struct
  type t = { handle : Wgpu_low.device }

  let release t = Wgpu_low.device_release t.handle

  let create_shader_module' t ?(label = "") ~wgsl () =
    (* Create the WGSL source extension struct *)
    let wgsl_source = Wgpu_low.Shader_source_wgsl.shader_source_WGSL_create () in
    Wgpu_low.Shader_source_wgsl.shader_source_WGSL_set_code wgsl_source wgsl;
    Wgpu_low.Shader_source_wgsl.shader_source_WGSL_set_chain_stype
      wgsl_source
      (S_type.to_int S_type.Shader_source_wgsl);
    (* Create the shader module descriptor and chain the extension *)
    let desc = Wgpu_low.Shader_module_descriptor.shader_module_descriptor_create () in
    Wgpu_low.Shader_module_descriptor.shader_module_descriptor_set_label desc label;
    let chained = Wgpu_low.Shader_source_wgsl.shader_source_WGSL_as_chained wgsl_source in
    Wgpu_low.Shader_module_descriptor.shader_module_descriptor_set_next_in_chain
      desc
      chained;
    (* Create the shader module *)
    let shader = Wgpu_low.device_create_shader_module t.handle desc in
    (* Free the descriptor structs *)
    Wgpu_low.Shader_module_descriptor.shader_module_descriptor_free desc;
    Wgpu_low.Shader_source_wgsl.shader_source_WGSL_free wgsl_source;
    ({ Shader_module.handle = shader } : Shader_module.t)
  ;;

  let create_compute_pipeline t ?(label = "") ~layout ~module_ ~entry_point () =
    let stage_desc =
      Wgpu_low.Programmable_stage_descriptor.programmable_stage_descriptor_create ()
    in
    Wgpu_low.Programmable_stage_descriptor.programmable_stage_descriptor_set_module
      stage_desc
      module_.Shader_module.handle;
    Wgpu_low.Programmable_stage_descriptor.programmable_stage_descriptor_set_entry_point
      stage_desc
      entry_point;
    Wgpu_low.Programmable_stage_descriptor.programmable_stage_descriptor_set_constants
      stage_desc
      [||];
    let desc =
      Wgpu_low.Compute_pipeline_descriptor.compute_pipeline_descriptor_create ()
    in
    Wgpu_low.Compute_pipeline_descriptor.compute_pipeline_descriptor_set_label desc label;
    Wgpu_low.Compute_pipeline_descriptor.compute_pipeline_descriptor_set_layout
      desc
      layout.Pipeline_layout.handle;
    Wgpu_low.Compute_pipeline_descriptor.compute_pipeline_descriptor_set_compute
      desc
      stage_desc;
    let pipeline = Wgpu_low.device_create_compute_pipeline t.handle desc in
    Wgpu_low.Programmable_stage_descriptor.programmable_stage_descriptor_free stage_desc;
    Wgpu_low.Compute_pipeline_descriptor.compute_pipeline_descriptor_free desc;
    ({ Compute_pipeline.handle = pipeline } : Compute_pipeline.t)
  ;;

  let create_render_pipeline
    t
    ?(label = "")
    ~shader_module
    ~vertex_entry_point
    ~fragment_entry_point
    ~color_format
    ?(topology = Primitive_topology.Triangle_list)
    ?(front_face = Front_face.Ccw)
    ?(cull_mode = Cull_mode.None)
    ?(blend :
        (Blend_factor.t
        * Blend_factor.t
        * Blend_operation.t
        * Blend_factor.t
        * Blend_factor.t
        * Blend_operation.t)
          option)
    ?(write_mask = [ Color_write_mask.Item.All ])
    ()
    =
    let blend_enabled, color_src, color_dst, color_op, alpha_src, alpha_dst, alpha_op =
      match blend with
      | None ->
        ( false
        , Blend_factor.One
        , Blend_factor.Zero
        , Blend_operation.Add
        , Blend_factor.One
        , Blend_factor.Zero
        , Blend_operation.Add )
      | Some (cs, cd, co, as_, ad, ao) -> true, cs, cd, co, as_, ad, ao
    in
    let pipeline =
      Wgpu_low.device_create_render_pipeline_full
        t.handle
        label
        shader_module.Shader_module.handle
        vertex_entry_point
        fragment_entry_point
        (Texture_format.to_int color_format)
        (Primitive_topology.to_int topology)
        (Front_face.to_int front_face)
        (Cull_mode.to_int cull_mode)
        blend_enabled
        (Blend_factor.to_int color_src)
        (Blend_factor.to_int color_dst)
        (Blend_operation.to_int color_op)
        (Blend_factor.to_int alpha_src)
        (Blend_factor.to_int alpha_dst)
        (Blend_operation.to_int alpha_op)
        (Color_write_mask.list_to_int write_mask)
    in
    ({ Render_pipeline.handle = pipeline } : Render_pipeline.t)
  ;;

  let create_bind_group_layout_for_storage_buffer
    t
    ?(label = "")
    ~binding
    ?(read_only = false)
    ()
    =
    let layout =
      Wgpu_low.device_create_bind_group_layout_storage t.handle label binding read_only
    in
    ({ Bind_group_layout.handle = layout } : Bind_group_layout.t)
  ;;

  (* AUTO-GENERATED DEVICE METHODS INJECTED HERE *)
  type limits =
    { max_texture_dimension_1D : int
    ; max_texture_dimension_2D : int
    ; max_texture_dimension_3D : int
    ; max_texture_array_layers : int
    ; max_bind_groups : int
    ; max_bind_groups_plus_vertex_buffers : int
    ; max_bindings_per_bind_group : int
    ; max_dynamic_uniform_buffers_per_pipeline_layout : int
    ; max_dynamic_storage_buffers_per_pipeline_layout : int
    ; max_sampled_textures_per_shader_stage : int
    ; max_samplers_per_shader_stage : int
    ; max_storage_buffers_per_shader_stage : int
    ; max_storage_textures_per_shader_stage : int
    ; max_uniform_buffers_per_shader_stage : int
    ; max_uniform_buffer_binding_size : int64
    ; max_storage_buffer_binding_size : int64
    ; min_uniform_buffer_offset_alignment : int
    ; min_storage_buffer_offset_alignment : int
    ; max_vertex_buffers : int
    ; max_buffer_size : int64
    ; max_vertex_attributes : int
    ; max_vertex_buffer_array_stride : int
    ; max_inter_stage_shader_variables : int
    ; max_color_attachments : int
    ; max_color_attachment_bytes_per_sample : int
    ; max_compute_workgroup_storage_size : int
    ; max_compute_invocations_per_workgroup : int
    ; max_compute_workgroup_size_x : int
    ; max_compute_workgroup_size_y : int
    ; max_compute_workgroup_size_z : int
    ; max_compute_workgroups_per_dimension : int
    }

  let create_bind_group t ?(label = "") ~layout ?(entries = []) () =
    let desc_descriptor =
      Wgpu_low.Bind_group_descriptor.bind_group_descriptor_create ()
    in
    Wgpu_low.Bind_group_descriptor.bind_group_descriptor_set_label desc_descriptor label;
    Wgpu_low.Bind_group_descriptor.bind_group_descriptor_set_layout
      desc_descriptor
      layout.Bind_group_layout.handle;
    let entries_structs =
      List.map
        (fun (entry : Bind_group_entry.t) ->
          let e = Wgpu_low.Bind_group_entry.bind_group_entry_create () in
          Wgpu_low.Bind_group_entry.bind_group_entry_set_binding e entry.binding;
          Wgpu_low.Bind_group_entry.bind_group_entry_set_buffer
            e
            (match entry.buffer with
             | Some x -> x.Buffer.handle
             | None -> 0n);
          Wgpu_low.Bind_group_entry.bind_group_entry_set_offset e entry.offset;
          Wgpu_low.Bind_group_entry.bind_group_entry_set_size e entry.size;
          Wgpu_low.Bind_group_entry.bind_group_entry_set_sampler
            e
            (match entry.sampler with
             | Some x -> x.Sampler.handle
             | None -> 0n);
          Wgpu_low.Bind_group_entry.bind_group_entry_set_texture_view
            e
            (match entry.texture_view with
             | Some x -> x.Texture_view.handle
             | None -> 0n);
          e)
        entries
    in
    let entries_array = Array.of_list entries_structs in
    Wgpu_low.Bind_group_descriptor.bind_group_descriptor_set_entries
      desc_descriptor
      entries_array;
    let result = Wgpu_low.device_create_bind_group t.handle desc_descriptor in
    List.iter (fun e -> Wgpu_low.Bind_group_entry.bind_group_entry_free e) entries_structs;
    Wgpu_low.Bind_group_descriptor.bind_group_descriptor_free desc_descriptor;
    ({ Bind_group.handle = result } : Bind_group.t)
  ;;

  let create_bind_group_layout t ?(label = "") ?(entries = []) () =
    let desc_descriptor =
      Wgpu_low.Bind_group_layout_descriptor.bind_group_layout_descriptor_create ()
    in
    Wgpu_low.Bind_group_layout_descriptor.bind_group_layout_descriptor_set_label
      desc_descriptor
      label;
    let entries_structs =
      List.map
        (fun (entry : Bind_group_layout_entry.t) ->
          let e = Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_create () in
          Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_set_binding
            e
            entry.binding;
          Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_set_visibility
            e
            (Shader_stage.list_to_int entry.visibility);
          (match entry.buffer with
           | Some buffer_rec ->
             let nested_buffer =
               Wgpu_low.Buffer_binding_layout.buffer_binding_layout_create ()
             in
             Wgpu_low.Buffer_binding_layout.buffer_binding_layout_set_type
               nested_buffer
               (Buffer_binding_type.to_int buffer_rec.type_);
             Wgpu_low.Buffer_binding_layout.buffer_binding_layout_set_has_dynamic_offset
               nested_buffer
               buffer_rec.has_dynamic_offset;
             Wgpu_low.Buffer_binding_layout.buffer_binding_layout_set_min_binding_size
               nested_buffer
               buffer_rec.min_binding_size;
             Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_set_buffer
               e
               nested_buffer
           | None -> ());
          (match entry.sampler with
           | Some sampler_rec ->
             let nested_sampler =
               Wgpu_low.Sampler_binding_layout.sampler_binding_layout_create ()
             in
             Wgpu_low.Sampler_binding_layout.sampler_binding_layout_set_type
               nested_sampler
               (Sampler_binding_type.to_int sampler_rec.type_);
             Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_set_sampler
               e
               nested_sampler
           | None -> ());
          (match entry.texture with
           | Some texture_rec ->
             let nested_texture =
               Wgpu_low.Texture_binding_layout.texture_binding_layout_create ()
             in
             Wgpu_low.Texture_binding_layout.texture_binding_layout_set_sample_type
               nested_texture
               (Texture_sample_type.to_int texture_rec.sample_type);
             Wgpu_low.Texture_binding_layout.texture_binding_layout_set_view_dimension
               nested_texture
               (Texture_view_dimension.to_int texture_rec.view_dimension);
             Wgpu_low.Texture_binding_layout.texture_binding_layout_set_multisampled
               nested_texture
               texture_rec.multisampled;
             Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_set_texture
               e
               nested_texture
           | None -> ());
          (match entry.storage_texture with
           | Some storage_texture_rec ->
             let nested_storage_texture =
               Wgpu_low.Storage_texture_binding_layout
               .storage_texture_binding_layout_create
                 ()
             in
             Wgpu_low.Storage_texture_binding_layout
             .storage_texture_binding_layout_set_access
               nested_storage_texture
               (Storage_texture_access.to_int storage_texture_rec.access);
             Wgpu_low.Storage_texture_binding_layout
             .storage_texture_binding_layout_set_format
               nested_storage_texture
               (Texture_format.to_int storage_texture_rec.format);
             Wgpu_low.Storage_texture_binding_layout
             .storage_texture_binding_layout_set_view_dimension
               nested_storage_texture
               (Texture_view_dimension.to_int storage_texture_rec.view_dimension);
             Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_set_storage_texture
               e
               nested_storage_texture
           | None -> ());
          e)
        entries
    in
    let entries_array = Array.of_list entries_structs in
    Wgpu_low.Bind_group_layout_descriptor.bind_group_layout_descriptor_set_entries
      desc_descriptor
      entries_array;
    let result = Wgpu_low.device_create_bind_group_layout t.handle desc_descriptor in
    List.iter
      (fun e -> Wgpu_low.Bind_group_layout_entry.bind_group_layout_entry_free e)
      entries_structs;
    Wgpu_low.Bind_group_layout_descriptor.bind_group_layout_descriptor_free
      desc_descriptor;
    ({ Bind_group_layout.handle = result } : Bind_group_layout.t)
  ;;

  let create_buffer t ?(label = "") ~usage ~size ~mapped_at_creation () =
    let desc_descriptor = Wgpu_low.Buffer_descriptor.buffer_descriptor_create () in
    Wgpu_low.Buffer_descriptor.buffer_descriptor_set_label desc_descriptor label;
    Wgpu_low.Buffer_descriptor.buffer_descriptor_set_usage
      desc_descriptor
      (Buffer_usage.list_to_int usage);
    Wgpu_low.Buffer_descriptor.buffer_descriptor_set_size desc_descriptor size;
    Wgpu_low.Buffer_descriptor.buffer_descriptor_set_mapped_at_creation
      desc_descriptor
      mapped_at_creation;
    let result = Wgpu_low.device_create_buffer t.handle desc_descriptor in
    Wgpu_low.Buffer_descriptor.buffer_descriptor_free desc_descriptor;
    ({ Buffer.handle = result } : Buffer.t)
  ;;

  let create_command_encoder t ?(label = "") () =
    let desc_descriptor =
      Wgpu_low.Command_encoder_descriptor.command_encoder_descriptor_create ()
    in
    Wgpu_low.Command_encoder_descriptor.command_encoder_descriptor_set_label
      desc_descriptor
      label;
    let result = Wgpu_low.device_create_command_encoder t.handle desc_descriptor in
    Wgpu_low.Command_encoder_descriptor.command_encoder_descriptor_free desc_descriptor;
    ({ Command_encoder.handle = result } : Command_encoder.t)
  ;;

  let create_pipeline_layout t ?(label = "") ?(bind_group_layouts = []) () =
    let desc_descriptor =
      Wgpu_low.Pipeline_layout_descriptor.pipeline_layout_descriptor_create ()
    in
    Wgpu_low.Pipeline_layout_descriptor.pipeline_layout_descriptor_set_label
      desc_descriptor
      label;
    Wgpu_low.Pipeline_layout_descriptor.pipeline_layout_descriptor_set_bind_group_layouts
      desc_descriptor
      (Array.of_list (List.map (fun x -> x.Bind_group_layout.handle) bind_group_layouts));
    let result = Wgpu_low.device_create_pipeline_layout t.handle desc_descriptor in
    Wgpu_low.Pipeline_layout_descriptor.pipeline_layout_descriptor_free desc_descriptor;
    ({ Pipeline_layout.handle = result } : Pipeline_layout.t)
  ;;

  let create_query_set t ?(label = "") ~type_ ~count () =
    let desc_descriptor = Wgpu_low.Query_set_descriptor.query_set_descriptor_create () in
    Wgpu_low.Query_set_descriptor.query_set_descriptor_set_label desc_descriptor label;
    Wgpu_low.Query_set_descriptor.query_set_descriptor_set_type
      desc_descriptor
      (Query_type.to_int type_);
    Wgpu_low.Query_set_descriptor.query_set_descriptor_set_count desc_descriptor count;
    let result = Wgpu_low.device_create_query_set t.handle desc_descriptor in
    Wgpu_low.Query_set_descriptor.query_set_descriptor_free desc_descriptor;
    ({ Query_set.handle = result } : Query_set.t)
  ;;

  let create_render_bundle_encoder
    t
    ?(label = "")
    ?(color_formats = [])
    ~depth_stencil_format
    ~sample_count
    ~depth_read_only
    ~stencil_read_only
    ()
    =
    let desc_descriptor =
      Wgpu_low.Render_bundle_encoder_descriptor.render_bundle_encoder_descriptor_create ()
    in
    Wgpu_low.Render_bundle_encoder_descriptor.render_bundle_encoder_descriptor_set_label
      desc_descriptor
      label;
    Wgpu_low.Render_bundle_encoder_descriptor
    .render_bundle_encoder_descriptor_set_color_formats
      desc_descriptor
      (Array.of_list (List.map Texture_format.to_int color_formats));
    Wgpu_low.Render_bundle_encoder_descriptor
    .render_bundle_encoder_descriptor_set_depth_stencil_format
      desc_descriptor
      (Texture_format.to_int depth_stencil_format);
    Wgpu_low.Render_bundle_encoder_descriptor
    .render_bundle_encoder_descriptor_set_sample_count
      desc_descriptor
      sample_count;
    Wgpu_low.Render_bundle_encoder_descriptor
    .render_bundle_encoder_descriptor_set_depth_read_only
      desc_descriptor
      depth_read_only;
    Wgpu_low.Render_bundle_encoder_descriptor
    .render_bundle_encoder_descriptor_set_stencil_read_only
      desc_descriptor
      stencil_read_only;
    let result = Wgpu_low.device_create_render_bundle_encoder t.handle desc_descriptor in
    Wgpu_low.Render_bundle_encoder_descriptor.render_bundle_encoder_descriptor_free
      desc_descriptor;
    ({ Render_bundle_encoder.handle = result } : Render_bundle_encoder.t)
  ;;

  let create_sampler
    t
    ?(label = "")
    ~address_mode_u
    ~address_mode_v
    ~address_mode_w
    ~mag_filter
    ~min_filter
    ~mipmap_filter
    ~lod_min_clamp
    ~lod_max_clamp
    ~compare
    ~max_anisotropy
    ()
    =
    let desc_descriptor = Wgpu_low.Sampler_descriptor.sampler_descriptor_create () in
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_label desc_descriptor label;
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_address_mode_u
      desc_descriptor
      (Address_mode.to_int address_mode_u);
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_address_mode_v
      desc_descriptor
      (Address_mode.to_int address_mode_v);
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_address_mode_w
      desc_descriptor
      (Address_mode.to_int address_mode_w);
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_mag_filter
      desc_descriptor
      (Filter_mode.to_int mag_filter);
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_min_filter
      desc_descriptor
      (Filter_mode.to_int min_filter);
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_mipmap_filter
      desc_descriptor
      (Mipmap_filter_mode.to_int mipmap_filter);
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_lod_min_clamp
      desc_descriptor
      lod_min_clamp;
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_lod_max_clamp
      desc_descriptor
      lod_max_clamp;
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_compare
      desc_descriptor
      (Compare_function.to_int compare);
    Wgpu_low.Sampler_descriptor.sampler_descriptor_set_max_anisotropy
      desc_descriptor
      max_anisotropy;
    let result = Wgpu_low.device_create_sampler t.handle desc_descriptor in
    Wgpu_low.Sampler_descriptor.sampler_descriptor_free desc_descriptor;
    ({ Sampler.handle = result } : Sampler.t)
  ;;

  let create_texture
    t
    ?(label = "")
    ~usage
    ~dimension
    ~size_width
    ~size_height
    ~size_depth_or_array_layers
    ~format
    ~mip_level_count
    ~sample_count
    ?(view_formats = [])
    ()
    =
    let size_nested = Wgpu_low.Extent_3d.extent_3D_create () in
    let desc_descriptor = Wgpu_low.Texture_descriptor.texture_descriptor_create () in
    Wgpu_low.Texture_descriptor.texture_descriptor_set_label desc_descriptor label;
    Wgpu_low.Texture_descriptor.texture_descriptor_set_usage
      desc_descriptor
      (Texture_usage.list_to_int usage);
    Wgpu_low.Texture_descriptor.texture_descriptor_set_dimension
      desc_descriptor
      (Texture_dimension.to_int dimension);
    Wgpu_low.Extent_3d.extent_3D_set_width size_nested size_width;
    Wgpu_low.Extent_3d.extent_3D_set_height size_nested size_height;
    Wgpu_low.Extent_3d.extent_3D_set_depth_or_array_layers
      size_nested
      size_depth_or_array_layers;
    Wgpu_low.Texture_descriptor.texture_descriptor_set_size desc_descriptor size_nested;
    Wgpu_low.Texture_descriptor.texture_descriptor_set_format
      desc_descriptor
      (Texture_format.to_int format);
    Wgpu_low.Texture_descriptor.texture_descriptor_set_mip_level_count
      desc_descriptor
      mip_level_count;
    Wgpu_low.Texture_descriptor.texture_descriptor_set_sample_count
      desc_descriptor
      sample_count;
    Wgpu_low.Texture_descriptor.texture_descriptor_set_view_formats
      desc_descriptor
      (Array.of_list (List.map Texture_format.to_int view_formats));
    let result = Wgpu_low.device_create_texture t.handle desc_descriptor in
    Wgpu_low.Extent_3d.extent_3D_free size_nested;
    Wgpu_low.Texture_descriptor.texture_descriptor_free desc_descriptor;
    ({ Texture.handle = result } : Texture.t)
  ;;

  let destroy t = Wgpu_low.device_destroy t.handle

  let get_limits t =
    let output = Wgpu_low.Limits.limits_create () in
    let _status = Wgpu_low.device_get_limits t.handle output in
    let max_texture_dimension_1D =
      Wgpu_low.Limits.limits_get_max_texture_dimension_1D output
    in
    let max_texture_dimension_2D =
      Wgpu_low.Limits.limits_get_max_texture_dimension_2D output
    in
    let max_texture_dimension_3D =
      Wgpu_low.Limits.limits_get_max_texture_dimension_3D output
    in
    let max_texture_array_layers =
      Wgpu_low.Limits.limits_get_max_texture_array_layers output
    in
    let max_bind_groups = Wgpu_low.Limits.limits_get_max_bind_groups output in
    let max_bind_groups_plus_vertex_buffers =
      Wgpu_low.Limits.limits_get_max_bind_groups_plus_vertex_buffers output
    in
    let max_bindings_per_bind_group =
      Wgpu_low.Limits.limits_get_max_bindings_per_bind_group output
    in
    let max_dynamic_uniform_buffers_per_pipeline_layout =
      Wgpu_low.Limits.limits_get_max_dynamic_uniform_buffers_per_pipeline_layout output
    in
    let max_dynamic_storage_buffers_per_pipeline_layout =
      Wgpu_low.Limits.limits_get_max_dynamic_storage_buffers_per_pipeline_layout output
    in
    let max_sampled_textures_per_shader_stage =
      Wgpu_low.Limits.limits_get_max_sampled_textures_per_shader_stage output
    in
    let max_samplers_per_shader_stage =
      Wgpu_low.Limits.limits_get_max_samplers_per_shader_stage output
    in
    let max_storage_buffers_per_shader_stage =
      Wgpu_low.Limits.limits_get_max_storage_buffers_per_shader_stage output
    in
    let max_storage_textures_per_shader_stage =
      Wgpu_low.Limits.limits_get_max_storage_textures_per_shader_stage output
    in
    let max_uniform_buffers_per_shader_stage =
      Wgpu_low.Limits.limits_get_max_uniform_buffers_per_shader_stage output
    in
    let max_uniform_buffer_binding_size =
      Wgpu_low.Limits.limits_get_max_uniform_buffer_binding_size output
    in
    let max_storage_buffer_binding_size =
      Wgpu_low.Limits.limits_get_max_storage_buffer_binding_size output
    in
    let min_uniform_buffer_offset_alignment =
      Wgpu_low.Limits.limits_get_min_uniform_buffer_offset_alignment output
    in
    let min_storage_buffer_offset_alignment =
      Wgpu_low.Limits.limits_get_min_storage_buffer_offset_alignment output
    in
    let max_vertex_buffers = Wgpu_low.Limits.limits_get_max_vertex_buffers output in
    let max_buffer_size = Wgpu_low.Limits.limits_get_max_buffer_size output in
    let max_vertex_attributes = Wgpu_low.Limits.limits_get_max_vertex_attributes output in
    let max_vertex_buffer_array_stride =
      Wgpu_low.Limits.limits_get_max_vertex_buffer_array_stride output
    in
    let max_inter_stage_shader_variables =
      Wgpu_low.Limits.limits_get_max_inter_stage_shader_variables output
    in
    let max_color_attachments = Wgpu_low.Limits.limits_get_max_color_attachments output in
    let max_color_attachment_bytes_per_sample =
      Wgpu_low.Limits.limits_get_max_color_attachment_bytes_per_sample output
    in
    let max_compute_workgroup_storage_size =
      Wgpu_low.Limits.limits_get_max_compute_workgroup_storage_size output
    in
    let max_compute_invocations_per_workgroup =
      Wgpu_low.Limits.limits_get_max_compute_invocations_per_workgroup output
    in
    let max_compute_workgroup_size_x =
      Wgpu_low.Limits.limits_get_max_compute_workgroup_size_x output
    in
    let max_compute_workgroup_size_y =
      Wgpu_low.Limits.limits_get_max_compute_workgroup_size_y output
    in
    let max_compute_workgroup_size_z =
      Wgpu_low.Limits.limits_get_max_compute_workgroup_size_z output
    in
    let max_compute_workgroups_per_dimension =
      Wgpu_low.Limits.limits_get_max_compute_workgroups_per_dimension output
    in
    let result =
      { max_texture_dimension_1D
      ; max_texture_dimension_2D
      ; max_texture_dimension_3D
      ; max_texture_array_layers
      ; max_bind_groups
      ; max_bind_groups_plus_vertex_buffers
      ; max_bindings_per_bind_group
      ; max_dynamic_uniform_buffers_per_pipeline_layout
      ; max_dynamic_storage_buffers_per_pipeline_layout
      ; max_sampled_textures_per_shader_stage
      ; max_samplers_per_shader_stage
      ; max_storage_buffers_per_shader_stage
      ; max_storage_textures_per_shader_stage
      ; max_uniform_buffers_per_shader_stage
      ; max_uniform_buffer_binding_size
      ; max_storage_buffer_binding_size
      ; min_uniform_buffer_offset_alignment
      ; min_storage_buffer_offset_alignment
      ; max_vertex_buffers
      ; max_buffer_size
      ; max_vertex_attributes
      ; max_vertex_buffer_array_stride
      ; max_inter_stage_shader_variables
      ; max_color_attachments
      ; max_color_attachment_bytes_per_sample
      ; max_compute_workgroup_storage_size
      ; max_compute_invocations_per_workgroup
      ; max_compute_workgroup_size_x
      ; max_compute_workgroup_size_y
      ; max_compute_workgroup_size_z
      ; max_compute_workgroups_per_dimension
      }
    in
    Wgpu_low.Limits.limits_free output;
    result
  ;;

  let has_feature t ~feature =
    Wgpu_low.device_has_feature t.handle (Feature_name.to_int feature)
  ;;

  let get_queue t : Queue.t = { Queue.handle = Wgpu_low.device_get_queue t.handle }

  let push_error_scope t ~filter =
    Wgpu_low.device_push_error_scope t.handle (Error_filter.to_int filter)
  ;;

  let set_label t ~label = Wgpu_low.device_set_label t.handle label
  let poll t ?(wait = false) () = Wgpu_low.device_poll t.handle wait
end

module Adapter = struct
  type t = { handle : Wgpu_low.adapter }

  let get_info t = Adapter_info.of_low (Wgpu_low.adapter_get_info t.handle)
  let release t = Wgpu_low.adapter_release t.handle

  let request_device t =
    let device = Wgpu_low.adapter_request_device_sync t.handle in
    { Device.handle = device }
  ;;

  let has_feature t ~feature =
    Wgpu_low.adapter_has_feature t.handle (Feature_name.to_int feature)
  ;;
end

module Instance = struct
  type t = { handle : Wgpu_low.instance }

  let create () = { handle = Wgpu_low.create_instance () }
  let release t = Wgpu_low.instance_release t.handle

  let request_adapter
    t
    ?(power_preference = Power_preference.Undefined)
    ?(backend_type = Backend_type.Undefined)
    ()
    =
    let adapter =
      Wgpu_low.instance_request_adapter_sync
        t.handle
        (Power_preference.to_int power_preference)
        (Backend_type.to_int backend_type)
    in
    { Adapter.handle = adapter }
  ;;
end

(* Convenience functions for methods that take complex descriptors *)

let begin_compute_pass (encoder : Command_encoder.t) ?(label = "") () =
  let desc = Wgpu_low.Compute_pass_descriptor.compute_pass_descriptor_create () in
  Wgpu_low.Compute_pass_descriptor.compute_pass_descriptor_set_label desc label;
  let pass = Wgpu_low.command_encoder_begin_compute_pass encoder.handle desc in
  Wgpu_low.Compute_pass_descriptor.compute_pass_descriptor_free desc;
  ({ Compute_pass_encoder.handle = pass } : Compute_pass_encoder.t)
;;

let begin_render_pass
  (encoder : Command_encoder.t)
  ?(label = "")
  ~color_view
  ?(load_op = Load_op.Clear)
  ?(store_op = Store_op.Store)
  ~clear_color
  ()
  =
  let r, g, b, a = clear_color in
  let pass =
    Wgpu_low.command_encoder_begin_render_pass_configurable
      encoder.handle
      label
      color_view.Texture_view.handle
      (Load_op.to_int load_op)
      (Store_op.to_int store_op)
      r
      g
      b
      a
  in
  ({ Render_pass_encoder.handle = pass } : Render_pass_encoder.t)
;;

let finish (encoder : Command_encoder.t) ?(label = "") () =
  Command_encoder.finish encoder ~label ()
;;

let set_bind_group (pass : Compute_pass_encoder.t) ~index ~bind_group =
  Compute_pass_encoder.set_bind_group
    pass
    ~group_index:index
    ~group:bind_group
    ~dynamic_offsets:[]
;;

let set_bind_group_render (pass : Render_pass_encoder.t) ~index ~bind_group =
  Render_pass_encoder.set_bind_group
    pass
    ~group_index:index
    ~group:bind_group
    ~dynamic_offsets:[]
;;

let copy_texture_to_buffer
  (encoder : Command_encoder.t)
  ~texture
  ~buffer
  ~size
  ~bytes_per_row
  ()
  =
  let width, height = size in
  Command_encoder.copy_texture_to_buffer
    encoder
    ~source_texture:texture
    ~source_mip_level:0
    ~source_origin_x:0
    ~source_origin_y:0
    ~source_origin_z:0
    ~source_aspect:Texture_aspect.All
    ~destination_layout_offset:0L
    ~destination_layout_bytes_per_row:bytes_per_row
    ~destination_layout_rows_per_image:height
    ~destination_buffer:buffer
    ~copy_size_width:width
    ~copy_size_height:height
    ~copy_size_depth_or_array_layers:1
    ()
;;

let map_buffer (buffer : Buffer.t) ~mode ~offset ~size =
  ignore
    (Wgpu_low.buffer_map_sync buffer.handle (Map_mode.list_to_int mode) offset size : int)
;;

let get_mapped_range (buffer : Buffer.t) ~offset ~size =
  Wgpu_low.buffer_get_mapped_range_bigarray buffer.handle offset size
;;

let get_const_mapped_range (buffer : Buffer.t) ~offset ~size =
  Wgpu_low.buffer_get_const_mapped_range_bigarray buffer.handle offset size
;;

let create_texture_view
  (texture : Texture.t)
  ?(label = "")
  ?(format = Texture_format.Undefined)
  ?(dimension = Texture_view_dimension.Undefined)
  ?(aspect = Texture_aspect.All)
  ?(base_mip_level = 0)
  ?(mip_level_count = 0xFFFFFFFF)
  (* WGPU_MIP_LEVEL_COUNT_UNDEFINED *)
  ?(base_array_layer = 0)
  ?(array_layer_count = 0xFFFFFFFF)
  (* WGPU_ARRAY_LAYER_COUNT_UNDEFINED *)
    ()
  =
  let view =
    Wgpu_low.texture_create_view_configurable
      texture.handle
      label
      (Texture_format.to_int format)
      (Texture_view_dimension.to_int dimension)
      (Texture_aspect.to_int aspect)
      base_mip_level
      mip_level_count
      base_array_layer
      array_layer_count
  in
  ({ Texture_view.handle = view } : Texture_view.t)
;;
