open! Core

module Kind = struct
  type t =
    | C
    | Ml
    | Mli

  let arg =
    Command.Arg_type.create (fun s ->
      match String.lowercase s with
      | "c" -> C
      | "ml" -> Ml
      | "mli" -> Mli
      | _ -> failwith "kind must be 'c', 'ml' or 'mli'")
  ;;
end

module Level = struct
  type t =
    | High
    | Low

  let arg =
    Command.Arg_type.create (fun s ->
      match String.lowercase s with
      | "high" -> High
      | "low" -> Low
      | _ -> failwith "level must be 'high' or 'low'")
  ;;
end

let low_level_c_stubs =
  {|/* Generated by gen_bindings - low-level C stubs */
#include <caml/mlvalues.h>
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/custom.h>
#include <caml/fail.h>

#include "webgpu.h"
#include "wgpu.h"

/* Minimal test stub: create a wgpu instance */
CAMLprim value caml_wgpu_create_instance(value unit) {
  CAMLparam1(unit);
  WGPUInstanceDescriptor desc = {
    .nextInChain = NULL,
  };
  WGPUInstance instance = wgpuCreateInstance(&desc);
  /* For now, just return the pointer as a nativeint */
  CAMLreturn(caml_copy_nativeint((intnat)instance));
}

/* Release an instance */
CAMLprim value caml_wgpu_instance_release(value instance_val) {
  CAMLparam1(instance_val);
  WGPUInstance instance = (WGPUInstance)Nativeint_val(instance_val);
  if (instance != NULL) {
    wgpuInstanceRelease(instance);
  }
  CAMLreturn(Val_unit);
}
|}
;;

let low_level_ml =
  {|(* Generated by gen_bindings - low-level OCaml bindings *)

(** Raw instance handle *)
type instance = nativeint

(** Create a new wgpu instance with default settings *)
external create_instance : unit -> instance = "caml_wgpu_create_instance"

(** Release an instance *)
external instance_release : instance -> unit = "caml_wgpu_instance_release"
|}
;;

let low_level_mli =
  {|(* Generated by gen_bindings - low-level OCaml interface *)

(** Raw instance handle *)
type instance = nativeint

(** Create a new wgpu instance with default settings *)
val create_instance : unit -> instance

(** Release an instance *)
val instance_release : instance -> unit
|}
;;

let high_level_ml =
  {|(* Generated by gen_bindings - high-level OCaml bindings *)

module Instance : sig
  type t

  val create : unit -> t
  val release : t -> unit
end = struct
  type t = { handle : Wgpu_low.instance }

  let create () = { handle = Wgpu_low.create_instance () }
  let release t = Wgpu_low.instance_release t.handle
end
|}
;;

let high_level_mli =
  {|(* Generated by gen_bindings - high-level OCaml interface *)

module Instance : sig
  type t

  (** Create a new wgpu instance *)
  val create : unit -> t

  (** Release an instance. After this call, the instance should not be used. *)
  val release : t -> unit
end
|}
;;

let command =
  Command.basic
    ~summary:"Generate wgpu OCaml bindings"
    (let%map_open.Command level = anon ("LEVEL" %: Level.arg)
     and kind = anon ("KIND" %: Kind.arg) in
     fun () ->
       (* TODO: implement data model parsing in separate .ml file, and then put low level and high level code generation in their own files too. *)
       match kind, level with
       | Ml, Low -> print_string low_level_ml
       | Mli, Low -> print_string low_level_mli
       | Ml, High -> print_string high_level_ml
       | Mli, High -> print_string high_level_mli
       | C, Low -> print_string low_level_c_stubs
       | C, High -> failwith "no c bindings in high level module")
;;

let () = Command_unix.run command
